/*
 * Project Z skin engine: the "Pixel Quest relief" look of the UI kit, plus the layout scale helpers every
 * widget uses (uiScale, hairline, text sizes, border widths).
 *
 * How a surface is drawn
 * ----------------------
 * Each panel, button, well, strip or chip is a normal GuiObject with a stack of 9-slice ImageLabels behind
 * its content ("skin layers", ZIndex < 0 so they sit under every child the screens add). The textures
 * (design/ui-skin, generated by tools/gen-ui-skin.mjs) are GREYSCALE + ALPHA and are tinted with
 * ImageColor3 = an EXACT theme token, so the colour audit still only ever sees tokens:
 *
 *   raised control  face (variant colour) + shade (background: outline + bottom base) + light (foreground: top highlight)
 *   panel           fill (panel background) + frame (frame colour) + edge (background: 1 px outer line)
 *   well / chip     fill (background or another token) + border (border colour)
 *   title strip     strip (frame colour, with its own dark rule)
 *
 * Pixel grid: the textures are authored at 1 texel = 1 "skin pixel" and upscaled by SKIN_UNIT, so
 * SliceScale = skinPx() / SKIN_UNIT keeps every authored pixel an integer block of screen pixels, and
 * ResamplerMode.Pixelated keeps it hard-edged at any scale (including fractional UI scales).
 *
 * Fallback: when a texture has no asset id (skinAssets.ts) or the client fails to fetch one, every surface
 * repaints itself as the previous flat look (BackgroundColor3 + UIStroke + UICorner). The UI is never blank.
 */
import { SKIN_TEXTURES, SKIN_TEXTURE_NAMES, SKIN_UNIT, SkinTextureName } from "./skinAssets";
import { BORDER, RADIUS, THEME } from "./theme";

const ContentProvider = game.GetService("ContentProvider");
const GuiService = game.GetService("GuiService");
const TweenService = game.GetService("TweenService");
const Workspace = game.GetService("Workspace");

export const DESIGN_W = 1120;
export const DESIGN_H = 630;

/** how far a pressed face drops (skin pixels), matching btnFacePress / btnShadePress */
export const PRESS_DROP = 2;

// ---------------------------------------------------------------- safe area & scale

/** height (px) covered by the Roblox top bar; our ScreenGui ignores the inset, so we keep clear of it */
export function topInset(): number {
	const [topLeft] = GuiService.GetGuiInset();
	let inset = topLeft.Y;
	const [ok, value] = pcall(() => GuiService.TopbarInset);
	if (ok) {
		const rect = value as Rect;
		if (rect.Height > 0) inset = math.max(inset, rect.Max.Y);
	}
	return math.max(0, inset);
}

export function viewportSize(): Vector2 {
	const cam = Workspace.CurrentCamera;
	if (cam !== undefined && cam.ViewportSize.X > 1 && cam.ViewportSize.Y > 1) return cam.ViewportSize;
	return new Vector2(DESIGN_W, DESIGN_H);
}

/** pixels per design unit of a letterboxed 1120x630 layout on the current screen */
export function uiScale(): number {
	const v = viewportSize();
	return math.max(0.35, math.min(v.X / DESIGN_W, (v.Y - topInset()) / DESIGN_H));
}

/** screen px for a border of `width` design px: 1 px up to ~1440p, thicker on 4K (like CSS px on a HiDPI screen) */
export function hairline(width: number): number {
	if (width <= 0) return 0;
	return math.max(1, math.round((width * uiScale()) / 1.6));
}

/**
 * Screen pixels per skin pixel: always an integer, so the pixel art never lands between screen pixels.
 * 720p -> 1, 1080p / 1440p -> 2, 4K -> 3, phones -> 1.
 */
export function skinPx(): number {
	return math.max(1, math.round(uiScale()));
}

// ---------------------------------------------------------------- refresh registries

const textConstraints = new Map<UITextSizeConstraint, number>();
/** text drawn at a fixed size (no TextScaled): object -> design size */
const fixedTexts = new Map<TextLabel | TextButton, number>();
const strokeWidths = new Map<UIStroke, number>();
const pixelStrokes = new Map<UIStroke, number>();
const skinLayers = new Set<ImageLabel>();
const insetListeners = new Set<() => void>();
/** frames whose BackgroundTransparency is a DESIGN value scaled by the player's transparency preference */
const worldFrames = new Map<GuiObject, number>();
/** the same for UIStroke.Transparency */
const worldStrokes = new Map<UIStroke, number>();

// ---------------------------------------------------------------- system accessibility preferences

/*
 * Three settings in the Roblox menu the player expects us to honour (docs/research/ui.md 4.2, 6.1, 6.2):
 * Background Transparency, Reduce Motion and Text Size. All three are read once, cached, and re-read through
 * GetPropertyChangedSignal; a change re-runs the same refreshAll() that already rebuilds text sizes and
 * stroke widths, and repaints every live surface (see the wiring at the end of this file).
 *
 * Every read is inside a pcall: an old client -- and the Node test harnesses -- may not have the property,
 * and the defaults below are exactly "behave as before".
 */

/** GuiService.PreferredTransparency: 1 = draw our transparency as designed, 0 = the player wants it opaque */
let preferredT = 1;
/** GuiService.ReducedMotionEnabled */
let reduceMotion = false;
/** text size multiplier derived from GuiService.PreferredTextSize */
let textPref = 1;

/**
 * Our multipliers for GuiService.PreferredTextSize. The engine publishes the enum but NOT what each step is
 * worth, so these numbers are ours. They are deliberately modest and capped at 1.4: the kit is TextScaled
 * inside a letterboxed design space, so above the cap a tight label overflows its box instead of reflowing
 * (the same trade MIN_TEXT_PX below already makes).
 */
function textPrefScale(size: Enum.PreferredTextSize): number {
	if (size === Enum.PreferredTextSize.Large) return 1.1;
	if (size === Enum.PreferredTextSize.Larger) return 1.25;
	if (size === Enum.PreferredTextSize.Largest) return 1.4;
	return 1;
}

function readPreferences(): void {
	pcall(() => {
		preferredT = math.clamp(GuiService.PreferredTransparency, 0, 1);
	});
	pcall(() => {
		reduceMotion = GuiService.ReducedMotionEnabled;
	});
	pcall(() => {
		textPref = textPrefScale(GuiService.PreferredTextSize);
	});
}
readPreferences();

/**
 * A design transparency, scaled by the player's preference -- the multiplication the accessibility doc asks
 * for. 0 (opaque) and 1 (not drawn at all: a hidden stroke, the invisible fallback fill of a focus ring) are
 * structural values, not "see the world through this", so they are left alone.
 */
export function worldTransparency(base: number): number {
	if (base <= 0 || base >= 1) return base;
	return base * preferredT;
}

/** true when the player asked for reduced motion */
export function reducedMotion(): boolean {
	return reduceMotion;
}

/** tween duration, honouring Reduce Motion (0 = the tween lands on its final value immediately) */
export function motionTime(time: number): number {
	return reduceMotion ? 0 : time;
}

/** multiplier the player's Text Size setting asks for (see textPrefScale) */
export function preferredTextScale(): number {
	return textPref;
}

/**
 * Sets a frame's background transparency as a DESIGN value and keeps it in sync with the player's preference.
 *
 * Only a PARTIAL value is remembered. 0 and 1 are not affected by the preference anyway, and not remembering
 * them matters: a screen that creates an element hidden (1) or opaque (0) and then animates its transparency
 * by hand stays its own owner, instead of being snapped back by the next screen-size refresh.
 */
export function setWorldTransparency(obj: GuiObject, base: number): void {
	obj.BackgroundTransparency = worldTransparency(base);
	if (base <= 0 || base >= 1) return;
	if (!worldFrames.has(obj)) obj.Destroying.Connect(() => worldFrames.delete(obj));
	worldFrames.set(obj, base);
}

/** the same for a UIStroke */
export function setWorldStrokeTransparency(s: UIStroke, base: number): void {
	s.Transparency = worldTransparency(base);
	if (base <= 0 || base >= 1) return;
	if (!worldStrokes.has(s)) s.Destroying.Connect(() => worldStrokes.delete(s));
	worldStrokes.set(s, base);
}

/**
 * Smallest text the interface is allowed to draw, in screen pixels.
 *
 * Roblox's accessibility guidance puts the floor here, and we were under it by half: on a 844x390 phone
 * uiScale lands at 0.53, so a 12-unit caption came out at 6 px and was allowed to shrink to 5. That is not
 * small text, it is text nobody reads -- and the letterboxed design space means the SMALLER the phone, the
 * worse it got, which is backwards.
 *
 * Raising the floor has a cost and it is deliberate: a label that no longer fits its box will now overflow
 * instead of shrinking away, so a tight string has to be shortened, truncated or given room. Unreadable is
 * worse than tight.
 */
const MIN_TEXT_PX = 9;

/*
 * The player's Text Size setting is applied HERE, to the constraint, and not by the engine.
 *
 * The accessibility doc is explicit about why: "When TextScaled is enabled [...] the element's text will not
 * be scaled by the PreferredTextSize value", and a UITextSizeConstraint "will not [...] expand above the set
 * MaxTextSize, regardless of the player's text size setting". scaleText() does both, so the setting would do
 * nothing at all in this kit. Scaling the cap ourselves gives it back for every label that FITS its box:
 * MinTextSize follows from the cap, so it moves too.
 *
 * What it still cannot do (and this is the honest limit, not an oversight): a label that is already being
 * shrunk by TextScaled to fit is pinned by its box, not by the cap, so a larger preference does not move it.
 * Only AutomaticSize would, and that is the structural fix in docs/research/ui.md 2.3.
 */
function applyTextSize(c: UITextSizeConstraint, designSize: number): void {
	const max = math.clamp(math.round(designSize * uiScale() * textPref), MIN_TEXT_PX, 100);
	c.MaxTextSize = max;
	c.MinTextSize = math.clamp(math.floor(max * 0.5), MIN_TEXT_PX, max);
}

/** TextScaled with a design-size cap (kept in sync with the screen size) */
export function scaleText(obj: TextLabel | TextButton | TextBox, designSize: number): UITextSizeConstraint {
	obj.TextScaled = true;
	let c = obj.FindFirstChildOfClass("UITextSizeConstraint");
	if (c === undefined) {
		c = new Instance("UITextSizeConstraint");
		const created = c;
		created.Destroying.Connect(() => textConstraints.delete(created));
		c.Parent = obj;
	}
	textConstraints.set(c, designSize);
	applyTextSize(c, designSize);
	return c;
}

/** screen px of a design text size drawn WITHOUT TextScaled: the UI scale, never below MIN_TEXT_PX */
export function fixedTextPx(designSize: number): number {
	return math.clamp(math.round(designSize * uiScale()), MIN_TEXT_PX, 100);
}

/**
 * The opposite of scaleText: the text keeps its size and its BOX has to grow (AutomaticSize) -- it never gets
 * squeezed. That squeezing is what turned the How-to-play key legends into a blur: TextScaled fits the string
 * into a fixed box by shrinking it, down to the floor. Kept in sync with the screen size like scaleText.
 *
 * Not multiplied by the player's Text Size setting: without TextScaled and without a UITextSizeConstraint the
 * ENGINE applies that setting itself, and an AutomaticSize box grows with it (the accessibility doc).
 */
export function fixedText(obj: TextLabel | TextButton, designSize: number): void {
	obj.TextScaled = false;
	if (!fixedTexts.has(obj)) obj.Destroying.Connect(() => fixedTexts.delete(obj));
	fixedTexts.set(obj, designSize);
	obj.TextSize = fixedTextPx(designSize);
}

/** sets a kit stroke's width in design px (kept in sync with the screen size) */
export function setStrokeWidth(s: UIStroke, width: number): void {
	if (!strokeWidths.has(s)) s.Destroying.Connect(() => strokeWidths.delete(s));
	pixelStrokes.delete(s);
	strokeWidths.set(s, width);
	s.Thickness = hairline(width);
}

/** sets a stroke's width in SKIN pixels (pixel borders follow the skin grid) */
export function setPixelStroke(s: UIStroke, pixels: number): void {
	if (!pixelStrokes.has(s)) s.Destroying.Connect(() => pixelStrokes.delete(s));
	strokeWidths.delete(s);
	pixelStrokes.set(s, pixels);
	s.Thickness = pixels * skinPx();
}

function refreshAll(): void {
	for (const [c, size] of textConstraints) {
		if (c.Parent === undefined) textConstraints.delete(c);
		else applyTextSize(c, size);
	}
	for (const [obj, size] of fixedTexts) {
		if (obj.Parent === undefined) fixedTexts.delete(obj);
		else obj.TextSize = fixedTextPx(size);
	}
	for (const [s, width] of strokeWidths) {
		if (s.Parent === undefined) strokeWidths.delete(s);
		else s.Thickness = hairline(width);
	}
	const px = skinPx();
	for (const [s, pixels] of pixelStrokes) {
		if (s.Parent === undefined) pixelStrokes.delete(s);
		else s.Thickness = pixels * px;
	}
	const slice = px / SKIN_UNIT;
	for (const label of skinLayers) {
		if (label.Parent === undefined) skinLayers.delete(label);
		else label.SliceScale = slice;
	}
	for (const [obj, base] of worldFrames) {
		if (obj.Parent === undefined) worldFrames.delete(obj);
		else obj.BackgroundTransparency = worldTransparency(base);
	}
	for (const [s, base] of worldStrokes) {
		if (s.Parent === undefined) worldStrokes.delete(s);
		else s.Transparency = worldTransparency(base);
	}
	for (const fn of insetListeners) fn();
}

let refreshQueued = false;
function queueRefresh(): void {
	if (refreshQueued) return;
	refreshQueued = true;
	task.defer(() => {
		refreshQueued = false;
		refreshAll();
	});
}

let watchedCamera: Camera | undefined;
let cameraConn: RBXScriptConnection | undefined;
function watchCamera(): void {
	const cam = Workspace.CurrentCamera;
	if (cam === watchedCamera) return;
	watchedCamera = cam;
	cameraConn?.Disconnect();
	cameraConn = cam?.GetPropertyChangedSignal("ViewportSize").Connect(queueRefresh);
	queueRefresh();
}
watchCamera();
Workspace.GetPropertyChangedSignal("CurrentCamera").Connect(watchCamera);
pcall(() => GuiService.GetPropertyChangedSignal("TopbarInset").Connect(queueRefresh));

/** runs `fn` now and whenever the screen size / top bar changes, until `owner` is destroyed */
export function onLayoutChange(owner: Instance, fn: () => void): void {
	insetListeners.add(fn);
	owner.Destroying.Connect(() => insetListeners.delete(fn));
	fn();
}

// ---------------------------------------------------------------- text: never outlined

/*
 * DESIGN_RULES UI-04: no text in the game carries a contour -- no UIStroke on a TextLabel / TextButton /
 * TextBox, and no TextStroke. It is the owner's call ("it makes it ugly"), and it undoes something the old kit
 * did without anyone asking: every button label and every title used to get a 1 skin px dark outline here.
 * Readability comes from the surface behind the text instead (UI-05, measured by `npm run test:contrast`).
 */

/**
 * Removes a contour from a text object: a glyph-outline UIStroke (the old "TextOutline", or any stroke in
 * Contextual mode) and the legacy TextStroke.
 */
export function clearTextOutline(label: TextLabel | TextButton | TextBox): void {
	for (const child of label.GetChildren()) {
		if (!child.IsA("UIStroke")) continue;
		if (child.Name === "TextOutline" || child.ApplyStrokeMode === Enum.ApplyStrokeMode.Contextual) child.Destroy();
	}
	label.TextStrokeTransparency = 1;
}

/**
 * The old name, kept only because call sites outside the kit still use it (admin/controls.ts). It no longer
 * draws anything: it CLEARS the contour, so an old call can never bring one back.
 */
export function textOutline(label: TextLabel | TextButton): void {
	clearTextOutline(label);
}

/** fades a text object */
export function fadeText(label: TextLabel | TextButton, time: number, transparency: number): void {
	tweenTo(label, time, { TextTransparency: transparency });
}

// ---------------------------------------------------------------- box strokes (frames only)

/**
 * Where a box stroke may live. A UIStroke parented to a text object contours its GLYPHS by default, and UI-04
 * forbids any UIStroke on text at all, so for a text host -- the kit's buttons are TextButtons -- the stroke
 * goes on a transparent child frame that covers it exactly. Created on demand: with the skin on, buttons never
 * need one.
 */
function strokeHost(g: GuiObject): GuiObject {
	if (!(g.IsA("TextLabel") || g.IsA("TextButton") || g.IsA("TextBox"))) return g;
	const found = g.FindFirstChild("StrokeHost");
	if (found !== undefined && found.IsA("Frame")) return found;
	const f = new Instance("Frame");
	f.Name = "StrokeHost";
	f.BackgroundTransparency = 1;
	f.BackgroundColor3 = THEME.background;
	f.BorderSizePixel = 0;
	f.Size = UDim2.fromScale(1, 1);
	f.Active = false;
	f.Selectable = false;
	f.ZIndex = g.ZIndex;
	f.Parent = g;
	return f;
}

/**
 * The kit's ONE way to create a UIStroke: a border around a box (ApplyStrokeMode.Border), parented to a frame
 * -- never a text contour. `npm run test:contrast` fails if skin.ts / widgets.ts create a UIStroke anywhere else.
 */
export function boxStroke(target: GuiObject, name = "Stroke"): UIStroke {
	const s = new Instance("UIStroke");
	s.Name = name;
	s.ApplyStrokeMode = Enum.ApplyStrokeMode.Border;
	s.Parent = strokeHost(target);
	return s;
}

/** a box stroke made by boxStroke(target, name), wherever it lives (on the target or on its StrokeHost) */
function findBoxStroke(target: GuiObject, name: string): UIStroke | undefined {
	const direct = target.FindFirstChild(name);
	if (direct !== undefined && direct.IsA("UIStroke")) return direct;
	const nested = target.FindFirstChild("StrokeHost")?.FindFirstChild(name);
	return nested !== undefined && nested.IsA("UIStroke") ? nested : undefined;
}

/** every fade of the kit lands here; `motionTime` is what makes Reduce Motion cut them to an instant jump */
function tweenTo<T extends Instance>(obj: T, time: number, props: Partial<ExtractMembers<T, Tweenable>>): Tween {
	const info = new TweenInfo(motionTime(time), Enum.EasingStyle.Quad, Enum.EasingDirection.Out);
	const t = TweenService.Create(obj, info, props);
	t.Play();
	return t;
}

/** a missed texture fetch is often transient; this is how long we wait before asking again */
const RETRY_DELAY = 1;

// ---------------------------------------------------------------- skin state (assets / fallback)

function hasTexture(name: SkinTextureName): boolean {
	return SKIN_TEXTURES[name].id !== "";
}

/** true while the textures are usable; a failed fetch flips it off and repaints every live surface flat */
let skinOn = hasTexture("btnFace") && hasTexture("panelFill") && hasTexture("wellFill");

export function skinEnabled(): boolean {
	return skinOn;
}

// ---------------------------------------------------------------- surfaces

export interface SkinLayerSpec {
	tex: SkinTextureName;
	/** ImageColor3: always an exact theme token */
	tint: Color3;
	/** 0 = opaque (default) */
	transparency?: number;
}

export interface SurfaceSpec {
	/** skin layers, bottom first */
	layers: Array<SkinLayerSpec>;
	/** flat fallback: background colour and transparency */
	bg: Color3;
	bgT: number;
	/** flat fallback: border */
	stroke?: Color3;
	strokeT?: number;
	/** border width in design px (default BORDER.width) */
	strokeW?: number;
	/** flat fallback: corner radius in design units (default RADIUS.lg) */
	radius?: number;
}

interface LiveSurface {
	spec: SurfaceSpec;
	labels: Array<ImageLabel>;
	/** extra transparency on top of the spec (HUD surfaces over the world, fades) */
	extraT: number;
}

const surfaces = new Map<GuiObject, LiveSurface>();

function combine(base: number, extra: number): number {
	if (extra <= 0) return base;
	return 1 - (1 - base) * (1 - extra);
}

function fallbackStroke(host: GuiObject, spec: SurfaceSpec, on: boolean): void {
	let s = findBoxStroke(host, "SurfaceBorder");
	if (!on || spec.stroke === undefined) {
		if (s !== undefined) s.Enabled = false;
		return;
	}
	if (s === undefined) {
		s = boxStroke(host, "SurfaceBorder");
		s.LineJoinMode = Enum.LineJoinMode.Miter;
	}
	s.Enabled = true;
	s.Color = spec.stroke;
	s.Transparency = combine(worldTransparency(spec.strokeT ?? 0), surfaces.get(host)?.extraT ?? 0);
	setStrokeWidth(s, spec.strokeW ?? BORDER.width);
}

function setCorner(obj: GuiObject, radius: number): void {
	let c = obj.FindFirstChildOfClass("UICorner");
	if (radius <= 0) {
		if (c !== undefined) c.CornerRadius = new UDim();
		return;
	}
	if (c === undefined) {
		c = new Instance("UICorner");
		c.Parent = obj;
	}
	// in screen px (Roblox clamps it to half the shorter side), so it works before the first layout pass
	c.CornerRadius = new UDim(0, math.round(radius * uiScale()));
}

function fallbackCorner(host: GuiObject, radius: number): void {
	setCorner(host, radius);
	// a text host keeps its border on a child frame (see strokeHost): that frame needs the same corners
	const strokeFrame = host.FindFirstChild("StrokeHost");
	if (strokeFrame !== undefined && strokeFrame.IsA("Frame")) setCorner(strokeFrame, radius);
}

function applySurface(host: GuiObject, live: LiveSurface): void {
	const spec = live.spec;
	const extra = live.extraT;
	if (!skinOn) {
		for (const l of live.labels) l.Destroy();
		live.labels.clear();
		host.BackgroundColor3 = spec.bg;
		host.BackgroundTransparency = combine(worldTransparency(spec.bgT), extra);
		fallbackStroke(host, spec, true);
		fallbackCorner(host, spec.radius ?? RADIUS.lg);
		return;
	}
	host.BackgroundColor3 = spec.bg;
	host.BackgroundTransparency = 1;
	fallbackStroke(host, spec, false);
	fallbackCorner(host, 0);
	const wanted = spec.layers.size();
	while (live.labels.size() > wanted) live.labels.pop()?.Destroy();
	for (let i = 0; i < wanted; i++) {
		const layer = spec.layers[i];
		const tex = SKIN_TEXTURES[layer.tex];
		let label = live.labels[i];
		if (label === undefined) {
			label = new Instance("ImageLabel");
			label.Name = `Skin${i + 1}`;
			label.BackgroundTransparency = 1;
			label.BackgroundColor3 = THEME.background;
			label.BorderSizePixel = 0;
			label.Size = UDim2.fromScale(1, 1);
			label.Position = new UDim2();
			label.Active = false;
			label.Selectable = false;
			label.ScaleType = Enum.ScaleType.Slice;
			label.ResampleMode = Enum.ResamplerMode.Pixelated;
			label.SliceScale = skinPx() / SKIN_UNIT;
			// under every child a screen adds (kit content starts at ZIndex 1)
			label.ZIndex = -10 + i;
			const created = label;
			skinLayers.add(created);
			created.Destroying.Connect(() => skinLayers.delete(created));
			label.Parent = host;
			live.labels[i] = label;
		}
		label.Image = tex.id;
		label.SliceCenter = new Rect(tex.slice[0], tex.slice[1], tex.slice[2], tex.slice[3]);
		label.ImageColor3 = layer.tint;
		label.ImageTransparency = combine(worldTransparency(layer.transparency ?? 0), extra);
	}
}

/** draws `spec` on `host` (creates / updates / removes its skin layers); call it again on every state change */
export function paintSurface(host: GuiObject, spec: SurfaceSpec): void {
	let live = surfaces.get(host);
	if (live === undefined) {
		live = { spec, labels: [], extraT: 0 };
		surfaces.set(host, live);
		host.Destroying.Connect(() => surfaces.delete(host));
	} else {
		live.spec = spec;
	}
	applySurface(host, live);
}

/** removes the surface from `host` (back to a plain transparent object) */
export function clearSurface(host: GuiObject): void {
	const live = surfaces.get(host);
	if (live === undefined) return;
	for (const l of live.labels) l.Destroy();
	surfaces.delete(host);
	const s = findBoxStroke(host, "SurfaceBorder");
	if (s !== undefined) s.Enabled = false;
	host.BackgroundTransparency = 1;
}

/** extra transparency over the surface's own (HUD cards over the world, enter / exit fades) */
export function setSurfaceTransparency(host: GuiObject, transparency: number): void {
	const live = surfaces.get(host);
	if (live === undefined) {
		host.BackgroundTransparency = transparency;
		return;
	}
	live.extraT = math.clamp(transparency, 0, 1);
	applySurface(host, live);
}

/** tweens the whole surface (skin layers or the flat fallback) to `transparency` */
export function fadeSurface(host: GuiObject, time: number, transparency: number): void {
	const live = surfaces.get(host);
	if (live === undefined) {
		tweenTo(host, time, { BackgroundTransparency: transparency });
		return;
	}
	live.extraT = math.clamp(transparency, 0, 1);
	if (live.labels.size() > 0) {
		for (let i = 0; i < live.labels.size(); i++) {
			const base = worldTransparency(live.spec.layers[i]?.transparency ?? 0);
			tweenTo(live.labels[i], time, { ImageTransparency: combine(base, live.extraT) });
		}
		return;
	}
	tweenTo(host, time, { BackgroundTransparency: combine(worldTransparency(live.spec.bgT), live.extraT) });
	const s = findBoxStroke(host, "SurfaceBorder");
	if (s !== undefined) {
		tweenTo(s, time, { Transparency: combine(worldTransparency(live.spec.strokeT ?? 0), live.extraT) });
	}
}

/** the skin failed to load: every live surface goes back to the flat look */
function disableSkin(): void {
	if (!skinOn) return;
	skinOn = false;
	for (const [host, live] of surfaces) {
		if (host.Parent === undefined) surfaces.delete(host);
		else applySurface(host, live);
	}
}

/*
 * The textures are a handful of tiny images, fetched up front so the first panel is already skinned.
 *
 * Two things measured in Studio shape this:
 *  - Preloading by CONTENT STRING reports Failure for every one of them, while preloading the ImageLabels
 *    that will show them succeeds: given a string the engine has to guess the asset type, given the
 *    instance it knows which property is being filled. So we preload throwaway ImageLabels.
 *  - A fetch can miss and then succeed a moment later (same id, two runs, two answers). An ImageLabel with
 *    a valid id draws as soon as the fetch lands, so a transient miss needs NO fallback -- it would only
 *    cost the player the skin for the rest of the session. We therefore retry once and give up on the skin
 *    only when EVERY texture is still missing, which is what a moderated or deleted upload looks like.
 */
if (skinOn) {
	task.spawn(() => {
		const ids: Array<string> = [];
		for (const name of SKIN_TEXTURE_NAMES) {
			const id = SKIN_TEXTURES[name].id;
			if (id !== "") ids.push(id);
		}
		if (ids.size() === 0) return;

		/** preloads `list` through real ImageLabels; returns the ids that did not arrive */
		const fetchMissing = (list: Array<string>): Array<string> => {
			const holder = new Instance("Folder");
			holder.Parent = ContentProvider;
			const probes: Array<ImageLabel> = [];
			for (const id of list) {
				const probe = new Instance("ImageLabel");
				probe.Image = id;
				probe.Parent = holder;
				probes.push(probe);
			}
			const missing: Array<string> = [];
			pcall(() =>
				ContentProvider.PreloadAsync(probes, (id: string, status: Enum.AssetFetchStatus) => {
					if (status !== Enum.AssetFetchStatus.Success) missing.push(id);
				}),
			);
			holder.Destroy();
			return missing;
		};

		let missing = fetchMissing(ids);
		if (missing.size() > 0) {
			task.wait(RETRY_DELAY);
			missing = fetchMissing(missing);
		}
		if (missing.size() === 0) return;

		if (missing.size() >= ids.size()) {
			// none of them arrived twice over: the uploads themselves are unavailable
			warn(`[ui] skin textures unavailable (${missing.size()}/${ids.size()}): falling back to the flat UI`);
			disableSkin();
			return;
		}
		// some arrived: keep the skin, the rest draw as soon as the engine gets them
		warn(`[ui] ${missing.size()}/${ids.size()} skin textures are slow; keeping the skin`);
	});
}

// ---------------------------------------------------------------- surface recipes

export type RaisedState = "idle" | "hot" | "press";

/**
 * Raised control (buttons, active tabs, slider knob): flat face in `face`, a dark base (lip) and outline
 * under it and a light band on top. Pressed, the lip is gone and the face drops PRESS_DROP skin pixels.
 */
export function raisedSurface(face: Color3, state: RaisedState = "idle"): SurfaceSpec {
	const press = state === "press";
	const layers: Array<SkinLayerSpec> = [
		{ tex: press ? "btnFacePress" : "btnFace", tint: face },
		{ tex: press ? "btnShadePress" : "btnShade", tint: THEME.background },
	];
	if (!press) layers.push({ tex: state === "hot" ? "btnLightHot" : "btnLight", tint: THEME.foreground });
	return { layers, bg: face, bgT: 0, stroke: THEME.border, strokeT: 1, radius: RADIUS.lg };
}

/** Recessed surface (content wells, list rows, inactive tabs, tracks, chips): flat fill + 1 px border */
export function wellSurface(fill: Color3, border: Color3, fillT = 0, radius = RADIUS.md): SurfaceSpec {
	return {
		layers: [
			{ tex: "wellFill", tint: fill, transparency: fillT },
			{ tex: "wellBorder", tint: border },
		],
		bg: fill,
		bgT: fillT,
		stroke: border,
		strokeT: 0,
		radius,
	};
}

/** Window / card: flat interior, thick frame and a dark outer edge */
export function panelSurface(fill: Color3, frame: Color3, fillT = 0): SurfaceSpec {
	return {
		layers: [
			{ tex: "panelFill", tint: fill, transparency: fillT },
			{ tex: "panelFrame", tint: frame },
			{ tex: "panelEdge", tint: THEME.background },
		],
		bg: fill,
		bgT: fillT,
		stroke: frame,
		strokeT: 0,
		strokeW: BORDER.width,
		radius: RADIUS.lg,
	};
}

/** Title strip at the top of a panel */
export function stripSurface(color: Color3, transparency = 0): SurfaceSpec {
	return {
		layers: [{ tex: "strip", tint: color, transparency }],
		bg: color,
		bgT: transparency,
		radius: RADIUS.sm,
	};
}

/** Gamepad / keyboard focus ring, drawn outside the control */
export function focusSurface(color: Color3): SurfaceSpec {
	return {
		layers: [{ tex: "focusRing", tint: color }],
		bg: THEME.background,
		bgT: 1,
		stroke: color,
		strokeT: 0,
		strokeW: BORDER.ring,
		radius: RADIUS.lg,
	};
}

// ---------------------------------------------------------------- accessibility listeners

/*
 * Wired here, at the bottom, because a change has to repaint the live surfaces too and `surfaces` is declared
 * above. The three settings can be changed while the game is open, so they are listened to and not just read.
 */
function onPreferenceChange(): void {
	readPreferences();
	for (const [host, live] of surfaces) {
		if (host.Parent === undefined) surfaces.delete(host);
		else applySurface(host, live);
	}
	// text sizes, stroke widths and the registered world transparencies
	queueRefresh();
}

pcall(() => GuiService.GetPropertyChangedSignal("PreferredTransparency").Connect(onPreferenceChange));
pcall(() => GuiService.GetPropertyChangedSignal("PreferredTextSize").Connect(onPreferenceChange));
pcall(() => GuiService.GetPropertyChangedSignal("ReducedMotionEnabled").Connect(onPreferenceChange));
