// generated by tools/gen-ui-skin.mjs --assets — do not edit
// textures: design/ui-skin/manifest.json (tools/gen-ui-skin.mjs), asset ids: design/ui-skin/assets.json
// an empty id turns that texture off: the kit then draws the flat fallback (Frames + UIStroke)

export interface SkinTextureAsset {
	/** "rbxassetid://...", or "" when the texture was not uploaded */
	id: string;
	/** 9-slice edges of the uploaded image (SliceCenter) */
	slice: readonly [number, number, number, number];
}

/** upscale factor of the authored pixel grid: SliceScale = skin pixels / UNIT */
export const SKIN_UNIT = 4;

export type SkinTextureName =
	| "btnFace"
	| "btnShade"
	| "btnLight"
	| "btnLightHot"
	| "btnFacePress"
	| "btnShadePress"
	| "panelFill"
	| "panelFrame"
	| "panelEdge"
	| "strip"
	| "wellFill"
	| "wellBorder"
	| "focusRing";

export const SKIN_TEXTURES: Record<SkinTextureName, SkinTextureAsset> = {
	/** raised face (tint: the variant colour) */
	btnFace: { id: "rbxassetid://77372919950676", slice: [12, 12, 20, 20] },
	/** raised outline + bottom base/lip (tint: background) */
	btnShade: { id: "rbxassetid://131025498878856", slice: [12, 12, 20, 20] },
	/** top highlight, idle (tint: foreground) */
	btnLight: { id: "rbxassetid://82374218979377", slice: [12, 12, 20, 20] },
	/** top highlight + inner rim, hover/focus (tint: foreground) */
	btnLightHot: { id: "rbxassetid://133460335652831", slice: [12, 12, 20, 20] },
	/** pressed face, dropped 2 px (tint: the variant colour) */
	btnFacePress: { id: "rbxassetid://76171457192839", slice: [12, 12, 20, 20] },
	/** pressed outline, short lip, inner shadow (tint: background) */
	btnShadePress: { id: "rbxassetid://104553134487435", slice: [12, 12, 20, 20] },
	/** panel interior (tint: panel background) */
	panelFill: { id: "rbxassetid://136859074137464", slice: [20, 20, 28, 28] },
	/** 3 px panel frame (tint: frame colour) */
	panelFrame: { id: "rbxassetid://128833256863429", slice: [20, 20, 28, 28] },
	/** 1 px dark outer edge of a panel (tint: background) */
	panelEdge: { id: "rbxassetid://93927581389568", slice: [20, 20, 28, 28] },
	/** title strip with its dark rule (tint: frame colour) */
	strip: { id: "rbxassetid://115177268038346", slice: [8, 8, 16, 16] },
	/** recessed fill: wells, rows, tracks, chips (tint: fill colour) */
	wellFill: { id: "rbxassetid://136787192183874", slice: [8, 8, 16, 16] },
	/** 1 px border of a well / chip (tint: border colour) */
	wellBorder: { id: "rbxassetid://95723661018660", slice: [8, 8, 16, 16] },
	/** 2 px gamepad focus ring drawn outside a control (tint: ring) */
	focusRing: { id: "rbxassetid://94776590973665", slice: [16, 16, 24, 24] },
};

/** every texture of the skin, for the preload pass */
export const SKIN_TEXTURE_NAMES: Array<SkinTextureName> = ["btnFace", "btnShade", "btnLight", "btnLightHot", "btnFacePress", "btnShadePress", "panelFill", "panelFrame", "panelEdge", "strip", "wellFill", "wellBorder", "focusRing"];
