// generated by tools/gen-theme.mjs — do not edit
// source: design/tweakcn-theme.json ("Meu tema global")
// regenerate: `npm run theme` (or `npm run theme -- <tweakcn registry url>`)
// semantic roles, game colours and typography live in theme.ts

/** shadcn colour tokens (CSS --kebab-case -> camelCase) */
export interface ThemeColors {
	background: Color3;
	foreground: Color3;
	card: Color3;
	cardForeground: Color3;
	popover: Color3;
	popoverForeground: Color3;
	primary: Color3;
	primaryForeground: Color3;
	secondary: Color3;
	secondaryForeground: Color3;
	muted: Color3;
	mutedForeground: Color3;
	accent: Color3;
	accentForeground: Color3;
	destructive: Color3;
	destructiveForeground: Color3;
	border: Color3;
	input: Color3;
	ring: Color3;
	chart1: Color3;
	chart2: Color3;
	chart3: Color3;
	chart4: Color3;
	chart5: Color3;
}

export const THEME_NAME = "Meu tema global";

/** .dark tokens (the game UI uses this mode) */
export const DARK: ThemeColors = {
	/** background: oklch(0.1722 0.0041 106.8174) #10100e */
	background: Color3.fromRGB(16, 16, 14),
	/** foreground: oklch(0.9927 0.0364 107.0448) #ffffe3 */
	foreground: Color3.fromRGB(255, 255, 227),
	/** card: oklch(0.1722 0.0041 106.8174) #10100e */
	card: Color3.fromRGB(16, 16, 14),
	/** card-foreground: oklch(0.9927 0.0364 107.0448) #ffffe3 */
	cardForeground: Color3.fromRGB(255, 255, 227),
	/** popover: oklch(0.1722 0.0041 106.8174) #10100e */
	popover: Color3.fromRGB(16, 16, 14),
	/** popover-foreground: oklch(0.9927 0.0364 107.0448) #ffffe3 */
	popoverForeground: Color3.fromRGB(255, 255, 227),
	/** primary: oklch(0.9927 0.0364 107.0448) #ffffe3 */
	primary: Color3.fromRGB(255, 255, 227),
	/** primary-foreground: oklch(0.1722 0.0041 106.8174) #10100e */
	primaryForeground: Color3.fromRGB(16, 16, 14),
	/** secondary: oklch(0.4856 0.0171 107.0202) #606055 */
	secondary: Color3.fromRGB(96, 96, 85),
	/** secondary-foreground: oklch(0.9927 0.0364 107.0448) #ffffe3 */
	secondaryForeground: Color3.fromRGB(255, 255, 227),
	/** muted: oklch(0.1722 0.0041 106.8174) #10100e */
	muted: Color3.fromRGB(16, 16, 14),
	/** muted-foreground: oklch(0.6357 0.0218 107.0046) #8c8c7d */
	mutedForeground: Color3.fromRGB(140, 140, 125),
	/** accent: oklch(0.6357 0.0218 107.0046) #8c8c7d */
	accent: Color3.fromRGB(140, 140, 125),
	/** accent-foreground: oklch(0.9927 0.0364 107.0448) #ffffe3 */
	accentForeground: Color3.fromRGB(255, 255, 227),
	/** destructive: oklch(0.6368 0.2078 25.3313) #ef4444 */
	destructive: Color3.fromRGB(239, 68, 68),
	/** destructive-foreground: oklch(0.9927 0.0364 107.0448) #ffffe3 */
	destructiveForeground: Color3.fromRGB(255, 255, 227),
	/** border: oklch(0.4856 0.0171 107.0202) #606055 */
	border: Color3.fromRGB(96, 96, 85),
	/** input: oklch(0.4856 0.0171 107.0202) #606055 */
	input: Color3.fromRGB(96, 96, 85),
	/** ring: oklch(0.9927 0.0364 107.0448) #ffffe3 */
	ring: Color3.fromRGB(255, 255, 227),
	/** chart-1: oklch(0.5685 0.1187 154.9491) #2e8b57 */
	chart1: Color3.fromRGB(46, 139, 87),
	/** chart-2: oklch(0.5880 0.0993 245.7394) #4682b4 */
	chart2: Color3.fromRGB(70, 130, 180),
	/** chart-3: oklch(0.6344 0.1550 50.2665) #d2691e */
	chart3: Color3.fromRGB(210, 105, 30),
	/** chart-4: oklch(0.5338 0.2503 301.3750) #8a2be2 */
	chart4: Color3.fromRGB(138, 43, 226),
	/** chart-5: oklch(0.5265 0.1151 44.6044) #a0522d */
	chart5: Color3.fromRGB(160, 82, 45),
};

/** :root (light) tokens */
export const LIGHT: ThemeColors = {
	/** background: oklch(0.9702 0 0) #f5f5f5 */
	background: Color3.fromRGB(245, 245, 245),
	/** foreground: oklch(0.2178 0 0) #1a1a1a */
	foreground: Color3.fromRGB(26, 26, 26),
	/** card: oklch(1.0000 0 0) #ffffff */
	card: Color3.fromRGB(255, 255, 255),
	/** card-foreground: oklch(0.2178 0 0) #1a1a1a */
	cardForeground: Color3.fromRGB(26, 26, 26),
	/** popover: oklch(1.0000 0 0) #ffffff */
	popover: Color3.fromRGB(255, 255, 255),
	/** popover-foreground: oklch(0.2178 0 0) #1a1a1a */
	popoverForeground: Color3.fromRGB(26, 26, 26),
	/** primary: oklch(0.2178 0 0) #1a1a1a */
	primary: Color3.fromRGB(26, 26, 26),
	/** primary-foreground: oklch(1.0000 0 0) #ffffff */
	primaryForeground: Color3.fromRGB(255, 255, 255),
	/** secondary: oklch(0.9067 0 0) #e0e0e0 */
	secondary: Color3.fromRGB(224, 224, 224),
	/** secondary-foreground: oklch(0.2178 0 0) #1a1a1a */
	secondaryForeground: Color3.fromRGB(26, 26, 26),
	/** muted: oklch(0.9067 0 0) #e0e0e0 */
	muted: Color3.fromRGB(224, 224, 224),
	/** muted-foreground: oklch(0.5103 0 0) #666666 */
	mutedForeground: Color3.fromRGB(102, 102, 102),
	/** accent: oklch(0.9340 0 0) #e9e9e9 */
	accent: Color3.fromRGB(233, 233, 233),
	/** accent-foreground: oklch(0.2178 0 0) #1a1a1a */
	accentForeground: Color3.fromRGB(26, 26, 26),
	/** destructive: oklch(0.6368 0.2078 25.3313) #ef4444 */
	destructive: Color3.fromRGB(239, 68, 68),
	/** destructive-foreground: oklch(1.0000 0 0) #ffffff */
	destructiveForeground: Color3.fromRGB(255, 255, 255),
	/** border: oklch(0.8452 0 0) #cccccc */
	border: Color3.fromRGB(204, 204, 204),
	/** input: oklch(0.9067 0 0) #e0e0e0 */
	input: Color3.fromRGB(224, 224, 224),
	/** ring: oklch(0.2178 0 0) #1a1a1a */
	ring: Color3.fromRGB(26, 26, 26),
	/** chart-1: oklch(0.5685 0.1187 154.9491) #2e8b57 */
	chart1: Color3.fromRGB(46, 139, 87),
	/** chart-2: oklch(0.5880 0.0993 245.7394) #4682b4 */
	chart2: Color3.fromRGB(70, 130, 180),
	/** chart-3: oklch(0.6344 0.1550 50.2665) #d2691e */
	chart3: Color3.fromRGB(210, 105, 30),
	/** chart-4: oklch(0.5338 0.2503 301.3750) #8a2be2 */
	chart4: Color3.fromRGB(138, 43, 226),
	/** chart-5: oklch(0.5265 0.1151 44.6044) #a0522d */
	chart5: Color3.fromRGB(160, 82, 45),
};

/** sidebar (navigation) tokens: --sidebar-* without the prefix */
export interface SidebarColors {
	/** --sidebar */
	background: Color3;
	/** --sidebar-foreground */
	foreground: Color3;
	/** --sidebar-primary */
	primary: Color3;
	/** --sidebar-primary-foreground */
	primaryForeground: Color3;
	/** --sidebar-accent */
	accent: Color3;
	/** --sidebar-accent-foreground */
	accentForeground: Color3;
	/** --sidebar-border */
	border: Color3;
	/** --sidebar-ring */
	ring: Color3;
}

/** .dark sidebar tokens (navigation rails) */
export const DARK_SIDEBAR: SidebarColors = {
	/** sidebar: oklch(0.2178 0 0) #1a1a1a */
	background: Color3.fromRGB(26, 26, 26),
	/** sidebar-foreground: oklch(0.9702 0 0) #f5f5f5 */
	foreground: Color3.fromRGB(245, 245, 245),
	/** sidebar-primary: oklch(0.9702 0 0) #f5f5f5 */
	primary: Color3.fromRGB(245, 245, 245),
	/** sidebar-primary-foreground: oklch(0.2178 0 0) #1a1a1a */
	primaryForeground: Color3.fromRGB(26, 26, 26),
	/** sidebar-accent: oklch(0.3092 0 0) #303030 */
	accent: Color3.fromRGB(48, 48, 48),
	/** sidebar-accent-foreground: oklch(0.9702 0 0) #f5f5f5 */
	accentForeground: Color3.fromRGB(245, 245, 245),
	/** sidebar-border: oklch(0.3715 0 0) #404040 */
	border: Color3.fromRGB(64, 64, 64),
	/** sidebar-ring: oklch(0.9702 0 0) #f5f5f5 */
	ring: Color3.fromRGB(245, 245, 245),
};

/** :root (light) sidebar tokens */
export const LIGHT_SIDEBAR: SidebarColors = {
	/** sidebar: oklch(1.0000 0 0) #ffffff */
	background: Color3.fromRGB(255, 255, 255),
	/** sidebar-foreground: oklch(0.2178 0 0) #1a1a1a */
	foreground: Color3.fromRGB(26, 26, 26),
	/** sidebar-primary: oklch(0.2178 0 0) #1a1a1a */
	primary: Color3.fromRGB(26, 26, 26),
	/** sidebar-primary-foreground: oklch(1.0000 0 0) #ffffff */
	primaryForeground: Color3.fromRGB(255, 255, 255),
	/** sidebar-accent: oklch(0.9340 0 0) #e9e9e9 */
	accent: Color3.fromRGB(233, 233, 233),
	/** sidebar-accent-foreground: oklch(0.2178 0 0) #1a1a1a */
	accentForeground: Color3.fromRGB(26, 26, 26),
	/** sidebar-border: oklch(0.8452 0 0) #cccccc */
	border: Color3.fromRGB(204, 204, 204),
	/** sidebar-ring: oklch(0.2178 0 0) #1a1a1a */
	ring: Color3.fromRGB(26, 26, 26),
};

/** --radius: 0.25rem -> px (design units of the 1120x630 layout) */
export const RADIUS_PX = 4;
/** --spacing: 0.25rem -> px; Tailwind step unit (p-4 = 4 x SPACING_PX) */
export const SPACING_PX = 4;
/** --letter-spacing: 0em; informational: Roblox text has no tracking */
export const LETTER_SPACING_EM = 0;
/** --shadow-opacity: 0; the kit draws no shadows when this is 0 (flat, border-separated) */
export const SHADOW_OPACITY = 0;

/** Roblox font families (use with Font.new(family, weight)) */
export const FONT_FAMILIES = {
	/** font-sans: Geist -> BuilderSans */
	sans: "rbxasset://fonts/families/BuilderSans.json",
	/** font-mono: Geist is proportional -> its monospace sibling BuilderMono */
	mono: "rbxasset://fonts/families/BuilderMono.json",
	/** font-serif: Geist -> BuilderSans */
	serif: "rbxasset://fonts/families/BuilderSans.json",
};
