// generated by tools/gen-theme.mjs — do not edit
// source: design/tweakcn-theme.json ("Meu tema global")
// regenerate: `npm run theme` (or `npm run theme -- <tweakcn registry url>`)
// semantic roles, game colours and typography live in theme.ts

/** shadcn colour tokens + the Project Z extensions tab-active / cell / window / stat-* / bar-* (CSS --kebab-case -> camelCase) */
export interface ThemeColors {
	background: Color3;
	foreground: Color3;
	card: Color3;
	cardForeground: Color3;
	popover: Color3;
	popoverForeground: Color3;
	primary: Color3;
	primaryForeground: Color3;
	secondary: Color3;
	secondaryForeground: Color3;
	muted: Color3;
	mutedForeground: Color3;
	accent: Color3;
	accentForeground: Color3;
	destructive: Color3;
	destructiveForeground: Color3;
	border: Color3;
	input: Color3;
	ring: Color3;
	chart1: Color3;
	chart2: Color3;
	chart3: Color3;
	chart4: Color3;
	chart5: Color3;
	tabActive: Color3;
	cell: Color3;
	cellMutedForeground: Color3;
	window: Color3;
	statValue: Color3;
	statBonus: Color3;
	statEffect: Color3;
	statLevel: Color3;
	barHp: Color3;
	barFood: Color3;
	barXp: Color3;
	coinShade: Color3;
	coinShine: Color3;
	medal: Color3;
	medalShade: Color3;
}

export const THEME_NAME = "Meu tema global";

/** .dark tokens (the game UI uses this mode) */
export const DARK: ThemeColors = {
	/** background: #141414 #141414 */
	background: Color3.fromRGB(20, 20, 20),
	/** foreground: #fafafa #fafafa */
	foreground: Color3.fromRGB(250, 250, 250),
	/** card: #141414 #141414 */
	card: Color3.fromRGB(20, 20, 20),
	/** card-foreground: #fafafa #fafafa */
	cardForeground: Color3.fromRGB(250, 250, 250),
	/** popover: #141414 #141414 */
	popover: Color3.fromRGB(20, 20, 20),
	/** popover-foreground: #fafafa #fafafa */
	popoverForeground: Color3.fromRGB(250, 250, 250),
	/** primary: #597388 #597388 */
	primary: Color3.fromRGB(89, 115, 136),
	/** primary-foreground: #fafafa #fafafa */
	primaryForeground: Color3.fromRGB(250, 250, 250),
	/** secondary: #727272 #727272 */
	secondary: Color3.fromRGB(114, 114, 114),
	/** secondary-foreground: #fafafa #fafafa */
	secondaryForeground: Color3.fromRGB(250, 250, 250),
	/** muted: #141414 #141414 */
	muted: Color3.fromRGB(20, 20, 20),
	/** muted-foreground: #9c9c9c #9c9c9c */
	mutedForeground: Color3.fromRGB(156, 156, 156),
	/** accent: #5a5a5a #5a5a5a */
	accent: Color3.fromRGB(90, 90, 90),
	/** accent-foreground: #fafafa #fafafa */
	accentForeground: Color3.fromRGB(250, 250, 250),
	/** destructive: oklch(0.6368 0.2078 25.3313) #ef4444 */
	destructive: Color3.fromRGB(239, 68, 68),
	/** destructive-foreground: #fafafa #fafafa */
	destructiveForeground: Color3.fromRGB(250, 250, 250),
	/** border: #6b6b6b #6b6b6b */
	border: Color3.fromRGB(107, 107, 107),
	/** input: #6b6b6b #6b6b6b */
	input: Color3.fromRGB(107, 107, 107),
	/** ring: #fafafa #fafafa */
	ring: Color3.fromRGB(250, 250, 250),
	/** chart-1: oklch(0.6000 0.1187 154.9491) #399560 */
	chart1: Color3.fromRGB(57, 149, 96),
	/** chart-2: oklch(0.6094 0.0993 245.7394) #4c88bb */
	chart2: Color3.fromRGB(76, 136, 187),
	/** chart-3: oklch(0.6344 0.1550 50.2665) #d2691e */
	chart3: Color3.fromRGB(210, 105, 30),
	/** chart-4: oklch(0.6479 0.2503 301.3750) #ac57ff */
	chart4: Color3.fromRGB(172, 87, 255),
	/** chart-5: oklch(0.6224 0.1151 44.6044) #c06e4a */
	chart5: Color3.fromRGB(192, 110, 74),
	/** tab-active: #597388 #597388 */
	tabActive: Color3.fromRGB(89, 115, 136),
	/** cell: #565656 #565656 */
	cell: Color3.fromRGB(86, 86, 86),
	/** cell-muted-foreground: #b1b1b1 #b1b1b1 */
	cellMutedForeground: Color3.fromRGB(177, 177, 177),
	/** window: #262626 #262626 */
	window: Color3.fromRGB(38, 38, 38),
	/** stat-value: oklch(0.8800 0.1500 95.0000) #f6d653 */
	statValue: Color3.fromRGB(246, 214, 83),
	/** stat-bonus: oklch(0.7600 0.1500 155.0000) #52cd86 */
	statBonus: Color3.fromRGB(82, 205, 134),
	/** stat-effect: oklch(0.7400 0.1500 50.0000) #f58b4b */
	statEffect: Color3.fromRGB(245, 139, 75),
	/** stat-level: oklch(0.8000 0.0993 245.7394) #87c4fa */
	statLevel: Color3.fromRGB(135, 196, 250),
	/** bar-hp: oklch(0.5800 0.2078 25.3313) #da2d33 */
	barHp: Color3.fromRGB(218, 45, 51),
	/** bar-food: oklch(0.5700 0.1550 50.2665) #bc5500 */
	barFood: Color3.fromRGB(188, 85, 0),
	/** bar-xp: oklch(0.5564 0.0993 245.7394) #3c78aa */
	barXp: Color3.fromRGB(60, 120, 170),
	/** coin-shade: oklch(0.4800 0.1250 48.0000) #94430b */
	coinShade: Color3.fromRGB(148, 67, 11),
	/** coin-shine: oklch(0.8400 0.1300 72.0000) #ffbc64 */
	coinShine: Color3.fromRGB(255, 188, 100),
	/** medal: oklch(0.8300 0.1400 86.0000) #f0c04e */
	medal: Color3.fromRGB(240, 192, 78),
	/** medal-shade: oklch(0.5800 0.1100 78.0000) #9e711e */
	medalShade: Color3.fromRGB(158, 113, 30),
};

/** :root (light) tokens */
export const LIGHT: ThemeColors = {
	/** background: oklch(0.9702 0 0) #f5f5f5 */
	background: Color3.fromRGB(245, 245, 245),
	/** foreground: oklch(0.2178 0 0) #1a1a1a */
	foreground: Color3.fromRGB(26, 26, 26),
	/** card: oklch(1.0000 0 0) #ffffff */
	card: Color3.fromRGB(255, 255, 255),
	/** card-foreground: oklch(0.2178 0 0) #1a1a1a */
	cardForeground: Color3.fromRGB(26, 26, 26),
	/** popover: oklch(1.0000 0 0) #ffffff */
	popover: Color3.fromRGB(255, 255, 255),
	/** popover-foreground: oklch(0.2178 0 0) #1a1a1a */
	popoverForeground: Color3.fromRGB(26, 26, 26),
	/** primary: oklch(0.2178 0 0) #1a1a1a */
	primary: Color3.fromRGB(26, 26, 26),
	/** primary-foreground: oklch(1.0000 0 0) #ffffff */
	primaryForeground: Color3.fromRGB(255, 255, 255),
	/** secondary: oklch(0.9067 0 0) #e0e0e0 */
	secondary: Color3.fromRGB(224, 224, 224),
	/** secondary-foreground: oklch(0.2178 0 0) #1a1a1a */
	secondaryForeground: Color3.fromRGB(26, 26, 26),
	/** muted: oklch(0.9067 0 0) #e0e0e0 */
	muted: Color3.fromRGB(224, 224, 224),
	/** muted-foreground: oklch(0.5103 0 0) #666666 */
	mutedForeground: Color3.fromRGB(102, 102, 102),
	/** accent: oklch(0.9340 0 0) #e9e9e9 */
	accent: Color3.fromRGB(233, 233, 233),
	/** accent-foreground: oklch(0.2178 0 0) #1a1a1a */
	accentForeground: Color3.fromRGB(26, 26, 26),
	/** destructive: oklch(0.6368 0.2078 25.3313) #ef4444 */
	destructive: Color3.fromRGB(239, 68, 68),
	/** destructive-foreground: oklch(1.0000 0 0) #ffffff */
	destructiveForeground: Color3.fromRGB(255, 255, 255),
	/** border: oklch(0.8452 0 0) #cccccc */
	border: Color3.fromRGB(204, 204, 204),
	/** input: oklch(0.9067 0 0) #e0e0e0 */
	input: Color3.fromRGB(224, 224, 224),
	/** ring: oklch(0.2178 0 0) #1a1a1a */
	ring: Color3.fromRGB(26, 26, 26),
	/** chart-1: oklch(0.6000 0.1187 154.9491) #399560 */
	chart1: Color3.fromRGB(57, 149, 96),
	/** chart-2: oklch(0.6094 0.0993 245.7394) #4c88bb */
	chart2: Color3.fromRGB(76, 136, 187),
	/** chart-3: oklch(0.6344 0.1550 50.2665) #d2691e */
	chart3: Color3.fromRGB(210, 105, 30),
	/** chart-4: oklch(0.6479 0.2503 301.3750) #ac57ff */
	chart4: Color3.fromRGB(172, 87, 255),
	/** chart-5: oklch(0.6224 0.1151 44.6044) #c06e4a */
	chart5: Color3.fromRGB(192, 110, 74),
	/** tab-active: var(--chart-2) #4c88bb */
	tabActive: Color3.fromRGB(76, 136, 187),
	/** cell: var(--sidebar-accent) #e9e9e9 */
	cell: Color3.fromRGB(233, 233, 233),
	/** cell-muted-foreground: var(--muted-foreground) #666666 */
	cellMutedForeground: Color3.fromRGB(102, 102, 102),
	/** window: var(--sidebar) #ffffff */
	window: Color3.fromRGB(255, 255, 255),
	/** stat-value: var(--foreground) #1a1a1a */
	statValue: Color3.fromRGB(26, 26, 26),
	/** stat-bonus: var(--chart-1) #399560 */
	statBonus: Color3.fromRGB(57, 149, 96),
	/** stat-effect: var(--chart-3) #d2691e */
	statEffect: Color3.fromRGB(210, 105, 30),
	/** stat-level: var(--chart-2) #4c88bb */
	statLevel: Color3.fromRGB(76, 136, 187),
	/** bar-hp: var(--destructive) #ef4444 */
	barHp: Color3.fromRGB(239, 68, 68),
	/** bar-food: var(--chart-3) #d2691e */
	barFood: Color3.fromRGB(210, 105, 30),
	/** bar-xp: var(--chart-2) #4c88bb */
	barXp: Color3.fromRGB(76, 136, 187),
	/** coin-shade: var(--chart-3) #d2691e */
	coinShade: Color3.fromRGB(210, 105, 30),
	/** coin-shine: var(--chart-3) #d2691e */
	coinShine: Color3.fromRGB(210, 105, 30),
	/** medal: var(--stat-value) #1a1a1a */
	medal: Color3.fromRGB(26, 26, 26),
	/** medal-shade: var(--stat-value) #1a1a1a */
	medalShade: Color3.fromRGB(26, 26, 26),
};

/** sidebar (navigation) tokens: --sidebar-* without the prefix */
export interface SidebarColors {
	/** --sidebar */
	background: Color3;
	/** --sidebar-foreground */
	foreground: Color3;
	/** --sidebar-primary */
	primary: Color3;
	/** --sidebar-primary-foreground */
	primaryForeground: Color3;
	/** --sidebar-accent */
	accent: Color3;
	/** --sidebar-accent-foreground */
	accentForeground: Color3;
	/** --sidebar-border */
	border: Color3;
	/** --sidebar-ring */
	ring: Color3;
}

/** .dark sidebar tokens (navigation rails) */
export const DARK_SIDEBAR: SidebarColors = {
	/** sidebar: #1a1a1a #1a1a1a */
	background: Color3.fromRGB(26, 26, 26),
	/** sidebar-foreground: #f4f4f4 #f4f4f4 */
	foreground: Color3.fromRGB(244, 244, 244),
	/** sidebar-primary: #f4f4f4 #f4f4f4 */
	primary: Color3.fromRGB(244, 244, 244),
	/** sidebar-primary-foreground: #1b1b1b #1b1b1b */
	primaryForeground: Color3.fromRGB(27, 27, 27),
	/** sidebar-accent: #444444 #444444 */
	accent: Color3.fromRGB(68, 68, 68),
	/** sidebar-accent-foreground: #f4f4f4 #f4f4f4 */
	accentForeground: Color3.fromRGB(244, 244, 244),
	/** sidebar-border: #6b6b6b #6b6b6b */
	border: Color3.fromRGB(107, 107, 107),
	/** sidebar-ring: #f4f4f4 #f4f4f4 */
	ring: Color3.fromRGB(244, 244, 244),
};

/** :root (light) sidebar tokens */
export const LIGHT_SIDEBAR: SidebarColors = {
	/** sidebar: oklch(1.0000 0 0) #ffffff */
	background: Color3.fromRGB(255, 255, 255),
	/** sidebar-foreground: oklch(0.2178 0 0) #1a1a1a */
	foreground: Color3.fromRGB(26, 26, 26),
	/** sidebar-primary: oklch(0.2178 0 0) #1a1a1a */
	primary: Color3.fromRGB(26, 26, 26),
	/** sidebar-primary-foreground: oklch(1.0000 0 0) #ffffff */
	primaryForeground: Color3.fromRGB(255, 255, 255),
	/** sidebar-accent: oklch(0.9340 0 0) #e9e9e9 */
	accent: Color3.fromRGB(233, 233, 233),
	/** sidebar-accent-foreground: oklch(0.2178 0 0) #1a1a1a */
	accentForeground: Color3.fromRGB(26, 26, 26),
	/** sidebar-border: oklch(0.8452 0 0) #cccccc */
	border: Color3.fromRGB(204, 204, 204),
	/** sidebar-ring: oklch(0.2178 0 0) #1a1a1a */
	ring: Color3.fromRGB(26, 26, 26),
};

/** --radius: 0.25rem -> px (design units of the 1120x630 layout) */
export const RADIUS_PX = 4;
/** --spacing: 0.25rem -> px; Tailwind step unit (p-4 = 4 x SPACING_PX) */
export const SPACING_PX = 4;
/** --letter-spacing: 0em; informational: Roblox text has no tracking */
export const LETTER_SPACING_EM = 0;
/** --shadow-opacity: 0; the kit draws no shadows when this is 0 (flat, border-separated) */
export const SHADOW_OPACITY = 0;

/** Roblox font families (use with Font.new(family, weight)) */
export const FONT_FAMILIES = {
	/** font-sans: Geist -> BuilderSans */
	sans: "rbxasset://fonts/families/BuilderSans.json",
	/** font-mono: Geist is proportional -> its monospace sibling BuilderMono */
	mono: "rbxasset://fonts/families/BuilderMono.json",
	/** font-serif: Geist -> BuilderSans */
	serif: "rbxasset://fonts/families/BuilderSans.json",
};
