// generated by tools/gen-theme.mjs — do not edit
// source: design/tweakcn-theme.json ("Meu tema global")
// regenerate: `npm run theme` (or `npm run theme -- <tweakcn registry url>`)
// semantic roles, game colours and typography live in theme.ts

/** shadcn colour tokens (CSS --kebab-case -> camelCase) */
export interface ThemeColors {
	background: Color3;
	foreground: Color3;
	card: Color3;
	cardForeground: Color3;
	popover: Color3;
	popoverForeground: Color3;
	primary: Color3;
	primaryForeground: Color3;
	secondary: Color3;
	secondaryForeground: Color3;
	muted: Color3;
	mutedForeground: Color3;
	accent: Color3;
	accentForeground: Color3;
	destructive: Color3;
	destructiveForeground: Color3;
	border: Color3;
	input: Color3;
	ring: Color3;
	chart1: Color3;
	chart2: Color3;
	chart3: Color3;
	chart4: Color3;
	chart5: Color3;
}

export const THEME_NAME = "Meu tema global";

/** .dark tokens (the game UI uses this mode) */
export const DARK: ThemeColors = {
	/** background: oklch(0.1682 0.0045 264.4500) #0e0f11 */
	background: Color3.fromRGB(14, 15, 17),
	/** foreground: oklch(0.9880 0.0045 250.0000) #f9fbfe */
	foreground: Color3.fromRGB(249, 251, 254),
	/** card: oklch(0.1682 0.0045 264.4500) #0e0f11 */
	card: Color3.fromRGB(14, 15, 17),
	/** card-foreground: oklch(0.9880 0.0045 250.0000) #f9fbfe */
	cardForeground: Color3.fromRGB(249, 251, 254),
	/** popover: oklch(0.1682 0.0045 264.4500) #0e0f11 */
	popover: Color3.fromRGB(14, 15, 17),
	/** popover-foreground: oklch(0.9880 0.0045 250.0000) #f9fbfe */
	popoverForeground: Color3.fromRGB(249, 251, 254),
	/** primary: oklch(0.6000 0.1187 154.9491) #399560 */
	primary: Color3.fromRGB(57, 149, 96),
	/** primary-foreground: oklch(0.1682 0.0045 264.4500) #0e0f11 */
	primaryForeground: Color3.fromRGB(14, 15, 17),
	/** secondary: oklch(0.6117 0.0223 250.5100) #7a8591 */
	secondary: Color3.fromRGB(122, 133, 145),
	/** secondary-foreground: oklch(0.1682 0.0045 264.4500) #0e0f11 */
	secondaryForeground: Color3.fromRGB(14, 15, 17),
	/** muted: oklch(0.1682 0.0045 264.4500) #0e0f11 */
	muted: Color3.fromRGB(14, 15, 17),
	/** muted-foreground: oklch(0.6339 0.0200 250.0000) #818c96 */
	mutedForeground: Color3.fromRGB(129, 140, 150),
	/** accent: oklch(0.5447 0.0223 250.0000) #67717d */
	accent: Color3.fromRGB(103, 113, 125),
	/** accent-foreground: oklch(0.9880 0.0045 250.0000) #f9fbfe */
	accentForeground: Color3.fromRGB(249, 251, 254),
	/** destructive: oklch(0.6368 0.2078 25.3313) #ef4444 */
	destructive: Color3.fromRGB(239, 68, 68),
	/** destructive-foreground: oklch(0.1682 0.0045 264.4500) #0e0f11 */
	destructiveForeground: Color3.fromRGB(14, 15, 17),
	/** border: oklch(0.6117 0.0223 250.5100) #7a8591 */
	border: Color3.fromRGB(122, 133, 145),
	/** input: oklch(0.6117 0.0223 250.5100) #7a8591 */
	input: Color3.fromRGB(122, 133, 145),
	/** ring: oklch(0.9880 0.0045 250.0000) #f9fbfe */
	ring: Color3.fromRGB(249, 251, 254),
	/** chart-1: oklch(0.6000 0.1187 154.9491) #399560 */
	chart1: Color3.fromRGB(57, 149, 96),
	/** chart-2: oklch(0.6094 0.0993 245.7394) #4c88bb */
	chart2: Color3.fromRGB(76, 136, 187),
	/** chart-3: oklch(0.6344 0.1550 50.2665) #d2691e */
	chart3: Color3.fromRGB(210, 105, 30),
	/** chart-4: oklch(0.6479 0.2503 301.3750) #ac57ff */
	chart4: Color3.fromRGB(172, 87, 255),
	/** chart-5: oklch(0.6224 0.1151 44.6044) #c06e4a */
	chart5: Color3.fromRGB(192, 110, 74),
};

/** :root (light) tokens */
export const LIGHT: ThemeColors = {
	/** background: oklch(0.9702 0 0) #f5f5f5 */
	background: Color3.fromRGB(245, 245, 245),
	/** foreground: oklch(0.2178 0 0) #1a1a1a */
	foreground: Color3.fromRGB(26, 26, 26),
	/** card: oklch(1.0000 0 0) #ffffff */
	card: Color3.fromRGB(255, 255, 255),
	/** card-foreground: oklch(0.2178 0 0) #1a1a1a */
	cardForeground: Color3.fromRGB(26, 26, 26),
	/** popover: oklch(1.0000 0 0) #ffffff */
	popover: Color3.fromRGB(255, 255, 255),
	/** popover-foreground: oklch(0.2178 0 0) #1a1a1a */
	popoverForeground: Color3.fromRGB(26, 26, 26),
	/** primary: oklch(0.2178 0 0) #1a1a1a */
	primary: Color3.fromRGB(26, 26, 26),
	/** primary-foreground: oklch(1.0000 0 0) #ffffff */
	primaryForeground: Color3.fromRGB(255, 255, 255),
	/** secondary: oklch(0.9067 0 0) #e0e0e0 */
	secondary: Color3.fromRGB(224, 224, 224),
	/** secondary-foreground: oklch(0.2178 0 0) #1a1a1a */
	secondaryForeground: Color3.fromRGB(26, 26, 26),
	/** muted: oklch(0.9067 0 0) #e0e0e0 */
	muted: Color3.fromRGB(224, 224, 224),
	/** muted-foreground: oklch(0.5103 0 0) #666666 */
	mutedForeground: Color3.fromRGB(102, 102, 102),
	/** accent: oklch(0.9340 0 0) #e9e9e9 */
	accent: Color3.fromRGB(233, 233, 233),
	/** accent-foreground: oklch(0.2178 0 0) #1a1a1a */
	accentForeground: Color3.fromRGB(26, 26, 26),
	/** destructive: oklch(0.6368 0.2078 25.3313) #ef4444 */
	destructive: Color3.fromRGB(239, 68, 68),
	/** destructive-foreground: oklch(1.0000 0 0) #ffffff */
	destructiveForeground: Color3.fromRGB(255, 255, 255),
	/** border: oklch(0.8452 0 0) #cccccc */
	border: Color3.fromRGB(204, 204, 204),
	/** input: oklch(0.9067 0 0) #e0e0e0 */
	input: Color3.fromRGB(224, 224, 224),
	/** ring: oklch(0.2178 0 0) #1a1a1a */
	ring: Color3.fromRGB(26, 26, 26),
	/** chart-1: oklch(0.6000 0.1187 154.9491) #399560 */
	chart1: Color3.fromRGB(57, 149, 96),
	/** chart-2: oklch(0.6094 0.0993 245.7394) #4c88bb */
	chart2: Color3.fromRGB(76, 136, 187),
	/** chart-3: oklch(0.6344 0.1550 50.2665) #d2691e */
	chart3: Color3.fromRGB(210, 105, 30),
	/** chart-4: oklch(0.6479 0.2503 301.3750) #ac57ff */
	chart4: Color3.fromRGB(172, 87, 255),
	/** chart-5: oklch(0.6224 0.1151 44.6044) #c06e4a */
	chart5: Color3.fromRGB(192, 110, 74),
};

/** sidebar (navigation) tokens: --sidebar-* without the prefix */
export interface SidebarColors {
	/** --sidebar */
	background: Color3;
	/** --sidebar-foreground */
	foreground: Color3;
	/** --sidebar-primary */
	primary: Color3;
	/** --sidebar-primary-foreground */
	primaryForeground: Color3;
	/** --sidebar-accent */
	accent: Color3;
	/** --sidebar-accent-foreground */
	accentForeground: Color3;
	/** --sidebar-border */
	border: Color3;
	/** --sidebar-ring */
	ring: Color3;
}

/** .dark sidebar tokens (navigation rails) */
export const DARK_SIDEBAR: SidebarColors = {
	/** sidebar: oklch(0.2178 0.0060 250.0000) #181a1d */
	background: Color3.fromRGB(24, 26, 29),
	/** sidebar-foreground: oklch(0.9702 0.0045 250.0000) #f3f5f8 */
	foreground: Color3.fromRGB(243, 245, 248),
	/** sidebar-primary: oklch(0.9702 0.0045 250.0000) #f3f5f8 */
	primary: Color3.fromRGB(243, 245, 248),
	/** sidebar-primary-foreground: oklch(0.2178 0.0060 250.0000) #181a1d */
	primaryForeground: Color3.fromRGB(24, 26, 29),
	/** sidebar-accent: oklch(0.3900 0.0150 250.0000) #3f464d */
	accent: Color3.fromRGB(63, 70, 77),
	/** sidebar-accent-foreground: oklch(0.9702 0.0045 250.0000) #f3f5f8 */
	accentForeground: Color3.fromRGB(243, 245, 248),
	/** sidebar-border: oklch(0.5309 0.0200 250.0000) #646d78 */
	border: Color3.fromRGB(100, 109, 120),
	/** sidebar-ring: oklch(0.9702 0.0045 250.0000) #f3f5f8 */
	ring: Color3.fromRGB(243, 245, 248),
};

/** :root (light) sidebar tokens */
export const LIGHT_SIDEBAR: SidebarColors = {
	/** sidebar: oklch(1.0000 0 0) #ffffff */
	background: Color3.fromRGB(255, 255, 255),
	/** sidebar-foreground: oklch(0.2178 0 0) #1a1a1a */
	foreground: Color3.fromRGB(26, 26, 26),
	/** sidebar-primary: oklch(0.2178 0 0) #1a1a1a */
	primary: Color3.fromRGB(26, 26, 26),
	/** sidebar-primary-foreground: oklch(1.0000 0 0) #ffffff */
	primaryForeground: Color3.fromRGB(255, 255, 255),
	/** sidebar-accent: oklch(0.9340 0 0) #e9e9e9 */
	accent: Color3.fromRGB(233, 233, 233),
	/** sidebar-accent-foreground: oklch(0.2178 0 0) #1a1a1a */
	accentForeground: Color3.fromRGB(26, 26, 26),
	/** sidebar-border: oklch(0.8452 0 0) #cccccc */
	border: Color3.fromRGB(204, 204, 204),
	/** sidebar-ring: oklch(0.2178 0 0) #1a1a1a */
	ring: Color3.fromRGB(26, 26, 26),
};

/** --radius: 0.25rem -> px (design units of the 1120x630 layout) */
export const RADIUS_PX = 4;
/** --spacing: 0.25rem -> px; Tailwind step unit (p-4 = 4 x SPACING_PX) */
export const SPACING_PX = 4;
/** --letter-spacing: 0em; informational: Roblox text has no tracking */
export const LETTER_SPACING_EM = 0;
/** --shadow-opacity: 0; the kit draws no shadows when this is 0 (flat, border-separated) */
export const SHADOW_OPACITY = 0;

/** Roblox font families (use with Font.new(family, weight)) */
export const FONT_FAMILIES = {
	/** font-sans: Geist -> BuilderSans */
	sans: "rbxasset://fonts/families/BuilderSans.json",
	/** font-mono: Geist is proportional -> its monospace sibling BuilderMono */
	mono: "rbxasset://fonts/families/BuilderMono.json",
	/** font-serif: Geist -> BuilderSans */
	serif: "rbxasset://fonts/families/BuilderSans.json",
};
