// generated by tools/gen-sfx.mjs — do not edit
// banks: design/audio/manifest.json, asset ids: design/audio/assets.json (npm run cloud -- upload-audio)
// a bank without an id plays nothing of ours: every event on it keeps its library take (DESIGN_RULES SND-01)

export type AudioBank = "ui" | "items" | "weapons" | "impacts" | "cues";

/** "rbxassetid://...", or "" until the bank is uploaded (or while the upload is not this bank's WAV) */
export const AUDIO_BANK_IDS: Record<AudioBank, string> = {
	ui: "",
	items: "",
	weapons: "",
	impacts: "",
	cues: "",
};

/** one take: a window of its bank, in seconds */
export interface SynthTake {
	readonly startAt: number;
	readonly maxPlay: number;
}

export interface SynthSound {
	readonly bank: AudioBank;
	readonly takes: ReadonlyArray<SynthTake>;
	/** base volume in the mix (the take itself is loudness-normalised, design/audio/README.md) */
	readonly volume: number;
	readonly pitchMin: number;
	readonly pitchMax: number;
	/** a loop: the region of the bank that repeats (Sound.LoopRegion), to the sample */
	readonly loopStart?: number;
	readonly loopEnd?: number;
}

/** our own take of each of these catalogue events (shared/data/sounds.ts resolves them) */
export const SYNTH_SOUNDS: Record<string, SynthSound> = {
	uiHover: { bank: "ui", takes: [{ startAt: 0.19, maxPlay: 0.1 }], volume: 0.3, pitchMin: 0.98, pitchMax: 1.03 },
	uiClick: { bank: "ui", takes: [{ startAt: 0.5, maxPlay: 0.11 }], volume: 0.36, pitchMin: 0.98, pitchMax: 1.03 },
	uiOpen: { bank: "ui", takes: [{ startAt: 0.82, maxPlay: 0.277 }], volume: 0.32, pitchMin: 1, pitchMax: 1.02 },
	uiClose: { bank: "ui", takes: [{ startAt: 1.31, maxPlay: 0.22 }], volume: 0.28, pitchMin: 1, pitchMax: 1.02 },
	uiBuy: { bank: "ui", takes: [{ startAt: 1.74, maxPlay: 0.565 }], volume: 0.36, pitchMin: 1, pitchMax: 1 },
	uiError: { bank: "ui", takes: [{ startAt: 2.52, maxPlay: 0.263 }], volume: 0.34, pitchMin: 0.98, pitchMax: 1 },
	pickupItem: {
		bank: "items",
		takes: [{ startAt: 0.19, maxPlay: 0.194 }],
		volume: 0.4,
		pitchMin: 0.97,
		pitchMax: 1.05,
	},
	pickupAmmo: {
		bank: "items",
		takes: [
			{ startAt: 0.6, maxPlay: 0.175 },
			{ startAt: 0.99, maxPlay: 0.175 },
		],
		volume: 0.4,
		pitchMin: 0.96,
		pitchMax: 1.04,
	},
	pickupFood: {
		bank: "items",
		takes: [
			{ startAt: 1.38, maxPlay: 0.241 },
			{ startAt: 1.83, maxPlay: 0.241 },
		],
		volume: 0.4,
		pitchMin: 0.96,
		pitchMax: 1.05,
	},
	pickupMaterial: {
		bank: "items",
		takes: [
			{ startAt: 2.28, maxPlay: 0.224 },
			{ startAt: 2.72, maxPlay: 0.224 },
		],
		volume: 0.4,
		pitchMin: 0.95,
		pitchMax: 1.05,
	},
	pickupCoin: {
		bank: "items",
		takes: [{ startAt: 3.16, maxPlay: 0.441 }],
		volume: 0.36,
		pitchMin: 1,
		pitchMax: 1.03,
	},
	levelUp: { bank: "items", takes: [{ startAt: 3.81, maxPlay: 1.36 }], volume: 0.36, pitchMin: 1, pitchMax: 1 },
	craftDone: {
		bank: "items",
		takes: [{ startAt: 5.38, maxPlay: 0.74 }],
		volume: 0.34,
		pitchMin: 0.98,
		pitchMax: 1.02,
	},
	buildPlace: {
		bank: "items",
		takes: [
			{ startAt: 6.33, maxPlay: 0.34 },
			{ startAt: 6.88, maxPlay: 0.34 },
		],
		volume: 0.42,
		pitchMin: 0.95,
		pitchMax: 1.04,
	},
	buildDeny: { bank: "items", takes: [{ startAt: 7.43, maxPlay: 0.242 }], volume: 0.34, pitchMin: 1, pitchMax: 1 },
	shotPistol: {
		bank: "weapons",
		takes: [
			{ startAt: 0.19, maxPlay: 0.564 },
			{ startAt: 0.97, maxPlay: 0.563 },
			{ startAt: 1.75, maxPlay: 0.563 },
		],
		volume: 0.4,
		pitchMin: 0.96,
		pitchMax: 1.05,
	},
	shotRifle: {
		bank: "weapons",
		takes: [
			{ startAt: 2.53, maxPlay: 0.919 },
			{ startAt: 3.66, maxPlay: 0.911 },
			{ startAt: 4.79, maxPlay: 0.92 },
		],
		volume: 0.42,
		pitchMin: 0.96,
		pitchMax: 1.04,
	},
	shotShotgun: {
		bank: "weapons",
		takes: [
			{ startAt: 5.92, maxPlay: 1.161 },
			{ startAt: 7.29, maxPlay: 1.161 },
		],
		volume: 0.46,
		pitchMin: 0.95,
		pitchMax: 1.03,
	},
	shotMg: {
		bank: "weapons",
		takes: [
			{ startAt: 8.66, maxPlay: 0.34 },
			{ startAt: 9.22, maxPlay: 0.34 },
			{ startAt: 9.78, maxPlay: 0.34 },
		],
		volume: 0.3,
		pitchMin: 1,
		pitchMax: 1.1,
	},
	shotSniper: {
		bank: "weapons",
		takes: [
			{ startAt: 10.33, maxPlay: 1.558 },
			{ startAt: 12.1, maxPlay: 1.563 },
		],
		volume: 0.46,
		pitchMin: 0.97,
		pitchMax: 1.02,
	},
	shotBow: {
		bank: "weapons",
		takes: [
			{ startAt: 13.88, maxPlay: 0.49 },
			{ startAt: 14.58, maxPlay: 0.481 },
		],
		volume: 0.36,
		pitchMin: 0.96,
		pitchMax: 1.05,
	},
	shotElectric: {
		bank: "weapons",
		takes: [
			{ startAt: 15.28, maxPlay: 0.36 },
			{ startAt: 15.85, maxPlay: 0.36 },
		],
		volume: 0.34,
		pitchMin: 0.95,
		pitchMax: 1.05,
	},
	reloadStart: {
		bank: "weapons",
		takes: [{ startAt: 16.419, maxPlay: 0.276 }],
		volume: 0.36,
		pitchMin: 0.97,
		pitchMax: 1.03,
	},
	reloadEnd: {
		bank: "weapons",
		takes: [{ startAt: 16.91, maxPlay: 0.28 }],
		volume: 0.38,
		pitchMin: 0.97,
		pitchMax: 1.03,
	},
	weaponSwitch: {
		bank: "weapons",
		takes: [{ startAt: 17.4, maxPlay: 0.224 }],
		volume: 0.3,
		pitchMin: 0.96,
		pitchMax: 1.04,
	},
	emptyClick: {
		bank: "weapons",
		takes: [{ startAt: 17.84, maxPlay: 0.1 }],
		volume: 0.5,
		pitchMin: 0.98,
		pitchMax: 1.03,
	},
	meleeSwing: {
		bank: "weapons",
		takes: [
			{ startAt: 18.15, maxPlay: 0.241 },
			{ startAt: 18.599, maxPlay: 0.28 },
			{ startAt: 19.09, maxPlay: 0.22 },
		],
		volume: 0.34,
		pitchMin: 0.94,
		pitchMax: 1.08,
	},
	hitFlesh: {
		bank: "impacts",
		takes: [
			{ startAt: 0.19, maxPlay: 0.28 },
			{ startAt: 0.679, maxPlay: 0.28 },
			{ startAt: 1.17, maxPlay: 0.28 },
			{ startAt: 1.66, maxPlay: 0.28 },
		],
		volume: 0.34,
		pitchMin: 0.92,
		pitchMax: 1.08,
	},
	debrisMetal: {
		bank: "impacts",
		takes: [
			{ startAt: 2.15, maxPlay: 0.64 },
			{ startAt: 3, maxPlay: 0.64 },
			{ startAt: 3.85, maxPlay: 0.64 },
		],
		volume: 0.3,
		pitchMin: 0.92,
		pitchMax: 1.08,
	},
	debrisWood: {
		bank: "impacts",
		takes: [
			{ startAt: 4.7, maxPlay: 0.26 },
			{ startAt: 5.17, maxPlay: 0.26 },
			{ startAt: 5.64, maxPlay: 0.26 },
		],
		volume: 0.3,
		pitchMin: 0.92,
		pitchMax: 1.08,
	},
	useInject: {
		bank: "impacts",
		takes: [{ startAt: 6.11, maxPlay: 0.46 }],
		volume: 0.4,
		pitchMin: 0.98,
		pitchMax: 1.02,
	},
	footstepA: {
		bank: "impacts",
		takes: [
			{ startAt: 6.78, maxPlay: 0.181 },
			{ startAt: 7.17, maxPlay: 0.181 },
			{ startAt: 7.56, maxPlay: 0.176 },
		],
		volume: 0.3,
		pitchMin: 0.94,
		pitchMax: 1.06,
	},
	footstepB: {
		bank: "impacts",
		takes: [
			{ startAt: 7.95, maxPlay: 0.159 },
			{ startAt: 8.32, maxPlay: 0.156 },
			{ startAt: 8.69, maxPlay: 0.151 },
		],
		volume: 0.3,
		pitchMin: 0.94,
		pitchMax: 1.06,
	},
	stingerWave1: { bank: "cues", takes: [{ startAt: 0.19, maxPlay: 3.036 }], volume: 0.4, pitchMin: 1, pitchMax: 1 },
	stingerWave2: { bank: "cues", takes: [{ startAt: 3.44, maxPlay: 3.071 }], volume: 0.43, pitchMin: 1, pitchMax: 1 },
	stingerWave3: { bank: "cues", takes: [{ startAt: 6.73, maxPlay: 3.359 }], volume: 0.46, pitchMin: 1, pitchMax: 1 },
	stingerDawn: { bank: "cues", takes: [{ startAt: 10.3, maxPlay: 2.817 }], volume: 0.34, pitchMin: 1, pitchMax: 1 },
	heartbeat1: {
		bank: "cues",
		takes: [{ startAt: 13.33, maxPlay: 3.198 }],
		volume: 0.4,
		pitchMin: 1,
		pitchMax: 1,
		loopStart: 13.34,
		loopEnd: 16.497875,
	},
	heartbeat2: {
		bank: "cues",
		takes: [{ startAt: 16.74, maxPlay: 2.44 }],
		volume: 0.46,
		pitchMin: 1,
		pitchMax: 1,
		loopStart: 16.75,
		loopEnd: 19.15,
	},
	heartbeat3: {
		bank: "cues",
		takes: [{ startAt: 19.389, maxPlay: 1.915 }],
		volume: 0.52,
		pitchMin: 1,
		pitchMax: 1,
		loopStart: 19.4,
		loopEnd: 21.275,
	},
};
