/*
 * GENERATED by `npm run stamp` (tools/gen-version.mjs) from package.json -- do not edit. The CI stamps its build
 * with the commit; the committed copy says "dev".
 */

/** the game's version (package.json) */
export const GAME_VERSION = "0.1.0";
/** the commit this build was made from, or "dev" for a local build */
export const GAME_BUILD = "dev";
