// generated by tools/gen-world-art.mjs (tools/blood-art.mjs) — do not edit
// combat blood (DESIGN_RULES ART-15): design/world-art/blood.png; its id is WORLD_ART.blood (worldArtAssets.ts)

/** the atlas's size in texels (one texel = 4 world units) */
export const BLOOD_ATLAS_W = 96;
export const BLOOD_ATLAS_H = 264;

/**
 * The same cells three times, one band under the other: band 0 matte (greyscale, tinted as the stain dries),
 * band 1 a survivor's wet blood, band 2 the horde's. A cell's wet copy is `BLOOD_BAND_H` (or twice it) lower.
 */
export const BLOOD_BAND_H = 88;

/** drops (where a droplet landed): shape x 4 + flip */
export const BLOOD_DROP_FIRST = 0;
export const BLOOD_DROPS = 16;
/** splats (where a body bled: a kill, a big bite): shape x 4 + flip */
export const BLOOD_SPLAT_FIRST = 16;
export const BLOOD_SPLATS = 12;
/** smears (the spatter behind a hit): first + sector x BLOOD_SMEAR_SHAPES + shape; sector 0 = +x, 2 = +y */
export const BLOOD_SMEAR_FIRST = 28;
export const BLOOD_SMEAR_SHAPES = 2;

/**
 * Every cell of band 0: [x, y, w, h, ax, ay] in texels -- its corner, its size, and the point of it (fractional)
 * that lies on the hit: a drop's or a splat's middle, a smear's impact bead.
 */
export const BLOOD_CELLS: ReadonlyArray<readonly [number, number, number, number, number, number]> = [
	[0, 0, 6, 6, 3, 3],
	[7, 0, 6, 6, 3, 3],
	[14, 0, 6, 6, 3, 3],
	[21, 0, 6, 6, 3, 3],
	[28, 0, 6, 6, 3, 3],
	[35, 0, 6, 6, 3, 3],
	[42, 0, 6, 6, 3, 3],
	[49, 0, 6, 6, 3, 3],
	[56, 0, 6, 6, 3, 3],
	[63, 0, 6, 6, 3, 3],
	[70, 0, 6, 6, 3, 3],
	[77, 0, 6, 6, 3, 3],
	[84, 0, 6, 6, 3, 3],
	[0, 7, 6, 6, 3, 3],
	[7, 7, 6, 6, 3, 3],
	[14, 7, 6, 6, 3, 3],
	[21, 7, 14, 14, 7, 7],
	[36, 7, 14, 14, 7, 7],
	[51, 7, 14, 14, 7, 7],
	[66, 7, 14, 14, 7, 7],
	[81, 7, 14, 14, 7, 7],
	[0, 22, 14, 14, 7, 7],
	[15, 22, 14, 14, 7, 7],
	[30, 22, 14, 14, 7, 7],
	[45, 22, 14, 14, 7, 7],
	[60, 22, 14, 14, 7, 7],
	[75, 22, 14, 14, 7, 7],
	[0, 37, 14, 14, 7, 7],
	[15, 37, 16, 9, 3, 4.5],
	[32, 37, 16, 9, 3, 4.5],
	[49, 37, 13, 13, 3.5, 3.5],
	[63, 37, 13, 13, 3.5, 3.5],
	[77, 37, 9, 16, 4.5, 3],
	[0, 54, 9, 16, 4.5, 3],
	[10, 54, 13, 13, 9.5, 3.5],
	[24, 54, 13, 13, 9.5, 3.5],
	[38, 54, 16, 9, 13, 4.5],
	[55, 54, 16, 9, 13, 4.5],
	[72, 54, 13, 13, 9.5, 9.5],
	[0, 71, 13, 13, 9.5, 9.5],
	[14, 71, 9, 16, 4.5, 13],
	[24, 71, 9, 16, 4.5, 13],
	[34, 71, 13, 13, 3.5, 9.5],
	[48, 71, 13, 13, 3.5, 9.5],
];
