// generated by tools/gen-world-art.mjs (tools/tree-art.mjs) — do not edit
// the town's trees (DESIGN_RULES VEG-06): design/world-art/trees.png; its id is WORLD_ART.trees (worldArtAssets.ts)

/** the atlas's size in texels (one texel = 4 world units) */
export const TREE_ATLAS_W = 512;
export const TREE_ATLAS_H = 266;

/** band 0 holds the crowns' masks and the trunk; a crown's shade is the same cell `TREE_BAND_H` lower */
export const TREE_BAND_H = 133;

/**
 * Per kind (shared/data/trees.ts TREE_SPECIES order), per look: [x, y, n] -- the top-left corner of the crown's
 * mask in band 0 and the side of its square cell, in texels.
 */
export const TREE_CELLS: ReadonlyArray<ReadonlyArray<readonly [number, number, number]>> = [
	// round
	[
		[0, 0, 42],
		[43, 0, 42],
		[86, 0, 42],
		[129, 0, 42],
		[172, 0, 42],
		[215, 0, 42],
	],
	// lobed
	[
		[258, 0, 44],
		[303, 0, 44],
		[348, 0, 44],
		[393, 0, 44],
		[438, 0, 44],
		[0, 45, 44],
	],
	// wide
	[
		[45, 45, 48],
		[94, 45, 48],
		[143, 45, 48],
		[192, 45, 48],
		[241, 45, 48],
	],
	// column
	[
		[290, 45, 28],
		[319, 45, 28],
		[348, 45, 28],
		[377, 45, 28],
		[406, 45, 28],
	],
	// pine
	[
		[435, 45, 36],
		[472, 45, 36],
		[0, 94, 36],
		[37, 94, 36],
		[74, 94, 36],
		[111, 94, 36],
	],
	// young
	[
		[148, 94, 24],
		[173, 94, 24],
		[198, 94, 24],
		[223, 94, 24],
	],
	// shrub
	[
		[248, 94, 18],
		[267, 94, 18],
		[286, 94, 18],
		[305, 94, 18],
		[324, 94, 18],
		[343, 94, 18],
	],
	// dead
	[
		[362, 94, 38],
		[401, 94, 38],
		[440, 94, 38],
	],
];

/** the trunk's cell (band 0 only: its light is in its greys), [x, y, n]: the 44 u trunk at 4 u a texel */
export const TREE_TRUNK_CELL: readonly [number, number, number] = [479, 94, 11];
