// generated by tools/gen-world-art.mjs — do not edit
// textures: design/world-art/manifest.json, asset ids: design/world-art/assets.json (npm run cloud -- upload-art)
// an empty id turns that texture off: client/view/worldView.ts then draws that surface flat, as before the art

export interface WorldArtAsset {
	/** "rbxassetid://...", or "" until the texture is uploaded */
	id: string;
	/** size in texels (one texel = WORLD_TEXEL world units) */
	w: number;
	h: number;
	/** 9-slice centre in texels (slice textures only) */
	slice?: readonly [number, number, number, number];
}

/** world units per texel of the world art */
export const WORLD_TEXEL = 4;

export type WorldArtName =
	| "asphalt"
	| "asphaltLot"
	| "concrete"
	| "plaza"
	| "pavers"
	| "apron"
	| "grass"
	| "grassLong"
	| "dirt"
	| "soil"
	| "tactile"
	| "paint"
	| "kerbN"
	| "kerbS"
	| "kerbW"
	| "kerbE"
	| "forest"
	| "fenceH"
	| "fenceV"
	| "floorWood"
	| "floorTile"
	| "floorShop"
	| "wall"
	| "roofShingleH"
	| "roofShingleV"
	| "roofGravel"
	| "roofMembrane"
	| "eaves"
	| "parapet"
	| "shadowBox"
	| "canopy0"
	| "canopyShade0"
	| "canopy1"
	| "canopyShade1"
	| "canopy2"
	| "canopyShade2"
	| "car0"
	| "carTrim0"
	| "carDamage0"
	| "carWreck0"
	| "car1"
	| "carTrim1"
	| "carDamage1"
	| "carWreck1"
	| "car2"
	| "carTrim2"
	| "carDamage2"
	| "carWreck2"
	| "car3"
	| "carTrim3"
	| "carDamage3"
	| "carWreck3"
	| "bin"
	| "litter0"
	| "litter1"
	| "litter2"
	| "blood0"
	| "blood1"
	| "oil0"
	| "oil1"
	| "crack0"
	| "crack1"
	| "manhole"
	| "drain"
	| "pump"
	| "acUnit"
	| "vent"
	| "chimney"
	| "signSchool"
	| "signHospital"
	| "signGas"
	| "signPharmacy"
	| "signMarket"
	| "signGrocery"
	| "signGuns"
	| "signClothes"
	| "signDiner"
	| "helipad"
	| "machineTurret"
	| "machineTurretHead"
	| "machineShock"
	| "machineBattery"
	| "machineSolar"
	| "machineReactor"
	| "machineOil"
	| "machineLamp"
	| "machinePadTurret"
	| "machinePadLamp"
	| "machineDroneTurret"
	| "machineDroneLamp"
	| "machineBeacon"
	| "machineBeaconDish"
	| "machineCooker";

export const WORLD_ART: Record<WorldArtName, WorldArtAsset> = {
	/** tile: road asphalt: grain and tar blotches (cracks are decals: a crack here would repeat every tile) */
	asphalt: { id: "rbxassetid://136696200865006", w: 64, h: 64 },
	/** tile: parking-lot asphalt, a little more worn */
	asphaltLot: { id: "rbxassetid://101623737123119", w: 64, h: 64 },
	/** tile: sidewalk: 64-unit concrete slabs with joints */
	concrete: { id: "rbxassetid://125417248338973", w: 64, h: 64 },
	/** tile: downtown paving: 32-unit pavers */
	plaza: { id: "rbxassetid://71646231282470", w: 32, h: 32 },
	/** tile: footpaths to the doors: running-bond pavers */
	pavers: { id: "rbxassetid://122346741168951", w: 16, h: 16 },
	/** tile: gas forecourt / ambulance bay: poured concrete panels */
	apron: { id: "rbxassetid://96060481248281", w: 64, h: 64 },
	/** tile: mowed lawn */
	grass: { id: "rbxassetid://128959353163283", w: 64, h: 64 },
	/** tile: a yard nobody mowed for a week or two */
	grassLong: { id: "rbxassetid://109833880147310", w: 64, h: 64 },
	/** tile: packed earth: park paths, the school yard */
	dirt: { id: "rbxassetid://88069669305202", w: 32, h: 32 },
	/** tile: tree pits: bark mulch */
	soil: { id: "rbxassetid://138928866784074", w: 16, h: 16 },
	/** tile: tactile paving where a crosswalk lands */
	tactile: { id: "rbxassetid://106111012873721", w: 4, h: 4 },
	/** tile: road paint, worn (tinted: white zebras, yellow line) */
	paint: { id: "rbxassetid://88659727099879", w: 16, h: 16 },
	/** tile: kerb on a road's north edge (its shadow on the asphalt below) */
	kerbN: { id: "rbxassetid://88114414655458", w: 16, h: 4 },
	/** tile: kerb on a road's south edge */
	kerbS: { id: "rbxassetid://104343748202093", w: 16, h: 4 },
	/** tile: kerb on a road's west edge */
	kerbW: { id: "rbxassetid://91701233722319", w: 4, h: 16 },
	/** tile: kerb on a road's east edge */
	kerbE: { id: "rbxassetid://71264148250002", w: 4, h: 16 },
	/** tile: the forest outside the town fence */
	forest: { id: "rbxassetid://85144802348141", w: 64, h: 64 },
	/** tile: board fence along x */
	fenceH: { id: "rbxassetid://119203758037793", w: 16, h: 2 },
	/** tile: board fence along y */
	fenceV: { id: "rbxassetid://101826053299894", w: 2, h: 16 },
	/** tile: house floors: boards */
	floorWood: { id: "rbxassetid://101668958493756", w: 32, h: 32 },
	/** tile: hospital / pharmacy floor: checker tiles */
	floorTile: { id: "rbxassetid://138138688365178", w: 16, h: 16 },
	/** tile: shop floor: vinyl tiles */
	floorShop: { id: "rbxassetid://129815435078768", w: 32, h: 32 },
	/** tileTint: walls: plaster (tint: the wall colour) */
	wall: { id: "rbxassetid://122355100041127", w: 8, h: 8 },
	/** tileTint: pitched roof shingles, courses along x (tint: roof colour) */
	roofShingleH: { id: "rbxassetid://135793779204378", w: 32, h: 32 },
	/** tileTint: pitched roof shingles, courses along y */
	roofShingleV: { id: "rbxassetid://90130399432236", w: 32, h: 32 },
	/** tileTint: flat roof: tar and gravel (shops) */
	roofGravel: { id: "rbxassetid://100979575455672", w: 32, h: 32 },
	/** tileTint: flat roof: welded membrane (school, hospital, gas) */
	roofMembrane: { id: "rbxassetid://79521293665666", w: 64, h: 64 },
	/** slice: pitched roof rim: drip edge and fascia */
	eaves: { id: "rbxassetid://86266945168441", w: 12, h: 12, slice: [4, 4, 8, 8] },
	/** slice: flat roof rim: parapet, coping, inner face */
	parapet: { id: "rbxassetid://77285850845081", w: 12, h: 12, slice: [4, 4, 8, 8] },
	/** slice: soft rectangular drop shadow */
	shadowBox: { id: "rbxassetid://100011874413072", w: 16, h: 16, slice: [6, 6, 10, 10] },
	/** mask: tree crown 1: silhouette + leaves (tint: foliage) */
	canopy0: { id: "rbxassetid://73465981877902", w: 40, h: 40 },
	/** overlay: tree crown 1: light, shadow and outline */
	canopyShade0: { id: "rbxassetid://79729616067760", w: 40, h: 40 },
	/** mask: tree crown 2: silhouette + leaves (tint: foliage) */
	canopy1: { id: "rbxassetid://89590010697770", w: 40, h: 40 },
	/** overlay: tree crown 2: light, shadow and outline */
	canopyShade1: { id: "rbxassetid://78267299787002", w: 40, h: 40 },
	/** mask: tree crown 3: silhouette + leaves (tint: foliage) */
	canopy2: { id: "rbxassetid://100206983226107", w: 40, h: 40 },
	/** overlay: tree crown 3: light, shadow and outline */
	canopyShade2: { id: "rbxassetid://87939293634230", w: 40, h: 40 },
	/** mask: sedan: body (tint: paint) */
	car0: { id: "rbxassetid://90907187103557", w: 50, h: 25 },
	/** overlay: sedan: glass, lights, wheels, outline */
	carTrim0: { id: "rbxassetid://101227547206373", w: 50, h: 25 },
	/** overlay: sedan: smashed windshield, scratches */
	carDamage0: { id: "rbxassetid://91358709281295", w: 50, h: 25 },
	/** overlay: sedan: burnt out */
	carWreck0: { id: "rbxassetid://116358795706916", w: 50, h: 25 },
	/** mask: hatch: body (tint: paint) */
	car1: { id: "rbxassetid://93097391290703", w: 50, h: 25 },
	/** overlay: hatch: glass, lights, wheels, outline */
	carTrim1: { id: "rbxassetid://91017473943960", w: 50, h: 25 },
	/** overlay: hatch: smashed windshield, scratches */
	carDamage1: { id: "rbxassetid://77340649568922", w: 50, h: 25 },
	/** overlay: hatch: burnt out */
	carWreck1: { id: "rbxassetid://137645395462651", w: 50, h: 25 },
	/** mask: pickup: body (tint: paint) */
	car2: { id: "rbxassetid://119189575734127", w: 50, h: 25 },
	/** overlay: pickup: glass, lights, wheels, outline */
	carTrim2: { id: "rbxassetid://121720458024309", w: 50, h: 25 },
	/** overlay: pickup: smashed windshield, scratches */
	carDamage2: { id: "rbxassetid://75808892601718", w: 50, h: 25 },
	/** overlay: pickup: burnt out */
	carWreck2: { id: "rbxassetid://135701189659216", w: 50, h: 25 },
	/** mask: suv: body (tint: paint) */
	car3: { id: "rbxassetid://75904740720087", w: 50, h: 25 },
	/** overlay: suv: glass, lights, wheels, outline */
	carTrim3: { id: "rbxassetid://124630657972919", w: 50, h: 25 },
	/** overlay: suv: smashed windshield, scratches */
	carDamage3: { id: "rbxassetid://82829722323934", w: 50, h: 25 },
	/** overlay: suv: burnt out */
	carWreck3: { id: "rbxassetid://110973168366486", w: 50, h: 25 },
	/** sprite: wheelie bin */
	bin: { id: "rbxassetid://77342012293829", w: 9, h: 9 },
	/** sprite: spilled litter (flat) */
	litter0: { id: "rbxassetid://77488859025992", w: 12, h: 12 },
	/** sprite: spilled litter (flat) */
	litter1: { id: "rbxassetid://130241590136140", w: 12, h: 12 },
	/** sprite: spilled litter (flat) */
	litter2: { id: "rbxassetid://80452263452415", w: 12, h: 12 },
	/** sprite: dried blood */
	blood0: { id: "rbxassetid://114594767797040", w: 16, h: 12 },
	/** sprite: dried blood */
	blood1: { id: "rbxassetid://93633145448572", w: 16, h: 12 },
	/** sprite: oil stain */
	oil0: { id: "rbxassetid://102216726173704", w: 16, h: 12 },
	/** sprite: oil stain */
	oil1: { id: "rbxassetid://90928154923991", w: 16, h: 12 },
	/** sprite: asphalt crack */
	crack0: { id: "rbxassetid://99972894255656", w: 24, h: 8 },
	/** sprite: asphalt crack */
	crack1: { id: "rbxassetid://108565198333064", w: 24, h: 8 },
	/** sprite: manhole cover */
	manhole: { id: "rbxassetid://89997805152847", w: 8, h: 8 },
	/** sprite: storm drain */
	drain: { id: "rbxassetid://140705036278395", w: 8, h: 4 },
	/** sprite: fuel dispenser */
	pump: { id: "rbxassetid://125264841699354", w: 8, h: 6 },
	/** sprite: rooftop air conditioner */
	acUnit: { id: "rbxassetid://104235250371536", w: 13, h: 11 },
	/** sprite: roof vent */
	vent: { id: "rbxassetid://112712506613304", w: 7, h: 7 },
	/** sprite: brick chimney on a house roof */
	chimney: { id: "rbxassetid://113951165389471", w: 8, h: 8 },
	/** sprite: storefront sign (type 3): an open book on a chalkboard */
	signSchool: { id: "rbxassetid://98558286094610", w: 32, h: 20 },
	/** sprite: storefront sign (type 4): the white H of the hospital road sign, on blue */
	signHospital: { id: "rbxassetid://72752078983539", w: 32, h: 20 },
	/** sprite: storefront sign (type 5): a fuel pump, its hose and nozzle hanging on its side */
	signGas: { id: "rbxassetid://102981392384732", w: 24, h: 16 },
	/** sprite: storefront sign (type 6): a green cross lightbox */
	signPharmacy: { id: "rbxassetid://103233203209784", w: 24, h: 16 },
	/** sprite: storefront sign (type 7): a shopping cart */
	signMarket: { id: "rbxassetid://96888495851566", w: 32, h: 20 },
	/** sprite: storefront sign (type 8): a paper grocery bag with a baguette and an apple */
	signGrocery: { id: "rbxassetid://122210622314467", w: 24, h: 16 },
	/** sprite: storefront sign (type 9): a pistol */
	signGuns: { id: "rbxassetid://81619965285369", w: 24, h: 16 },
	/** sprite: storefront sign (type 10): a T-shirt */
	signClothes: { id: "rbxassetid://99147626160535", w: 24, h: 16 },
	/** sprite: storefront sign (type 11): a plate between a fork and a knife */
	signDiner: { id: "rbxassetid://135810788333250", w: 32, h: 20 },
	/** sprite: hospital roof: the heliport's red H on a white cross */
	helipad: { id: "rbxassetid://103885604953798", w: 64, h: 64 },
	/** sprite: the turret's mount: an octagonal steel plate, the ring the head turns on, four bolts */
	machineTurret: { id: "", w: 16, h: 16 },
	/** sprite: the turret's head: a blue dome and the barrel, pointing +x (it turns) */
	machineTurretHead: { id: "", w: 13, h: 8 },
	/** sprite: the electric turret: copper coil rings round a steel terminal */
	machineShock: { id: "", w: 16, h: 16 },
	/** sprite: the battery box: blue case, the gauge window, the two posts */
	machineBattery: { id: "", w: 10, h: 10 },
	/** sprite: the solar generator: nine blue cells in a steel frame */
	machineSolar: { id: "", w: 18, h: 18 },
	/** sprite: the nuclear reactor: the vessel, its hazard band, the dome and the core */
	machineReactor: { id: "", w: 20, h: 20 },
	/** sprite: the oil generator: the radiator grille, the red tank and its cap, the exhaust */
	machineOil: { id: "", w: 18, h: 18 },
	/** sprite: the lamp: a floodlight head on its plate */
	machineLamp: { id: "", w: 12, h: 12 },
	/** sprite: the turret drone's pad: the charging ring and its contacts */
	machinePadTurret: { id: "", w: 12, h: 12 },
	/** sprite: the lamp drone's pad */
	machinePadLamp: { id: "", w: 10, h: 10 },
	/** sprite: the turret drone: four rotors, the body and its gun, pointing +x (it turns) */
	machineDroneTurret: { id: "", w: 11, h: 11 },
	/** sprite: the lamp drone: four rotors and the lamp */
	machineDroneLamp: { id: "", w: 11, h: 11 },
	/** sprite: the signal generator's base: the plate and the mast */
	machineBeacon: { id: "", w: 12, h: 12 },
	/** sprite: the signal generator's dish, facing +x (it turns) */
	machineBeaconDish: { id: "", w: 6, h: 7 },
	/** sprite: the cooker: a steel top with two plates and the knobs */
	machineCooker: { id: "", w: 14, h: 12 },
};

/** every texture of the world art, for the preload pass */
export const WORLD_ART_NAMES: Array<WorldArtName> = [
	"asphalt",
	"asphaltLot",
	"concrete",
	"plaza",
	"pavers",
	"apron",
	"grass",
	"grassLong",
	"dirt",
	"soil",
	"tactile",
	"paint",
	"kerbN",
	"kerbS",
	"kerbW",
	"kerbE",
	"forest",
	"fenceH",
	"fenceV",
	"floorWood",
	"floorTile",
	"floorShop",
	"wall",
	"roofShingleH",
	"roofShingleV",
	"roofGravel",
	"roofMembrane",
	"eaves",
	"parapet",
	"shadowBox",
	"canopy0",
	"canopyShade0",
	"canopy1",
	"canopyShade1",
	"canopy2",
	"canopyShade2",
	"car0",
	"carTrim0",
	"carDamage0",
	"carWreck0",
	"car1",
	"carTrim1",
	"carDamage1",
	"carWreck1",
	"car2",
	"carTrim2",
	"carDamage2",
	"carWreck2",
	"car3",
	"carTrim3",
	"carDamage3",
	"carWreck3",
	"bin",
	"litter0",
	"litter1",
	"litter2",
	"blood0",
	"blood1",
	"oil0",
	"oil1",
	"crack0",
	"crack1",
	"manhole",
	"drain",
	"pump",
	"acUnit",
	"vent",
	"chimney",
	"signSchool",
	"signHospital",
	"signGas",
	"signPharmacy",
	"signMarket",
	"signGrocery",
	"signGuns",
	"signClothes",
	"signDiner",
	"helipad",
	"machineTurret",
	"machineTurretHead",
	"machineShock",
	"machineBattery",
	"machineSolar",
	"machineReactor",
	"machineOil",
	"machineLamp",
	"machinePadTurret",
	"machinePadLamp",
	"machineDroneTurret",
	"machineDroneLamp",
	"machineBeacon",
	"machineBeaconDish",
	"machineCooker",
];
