/*
 * Which pieces of the world art are live, and the flat fallback.
 *
 * The town's textures and sprites (design/world-art, generated by tools/gen-world-art.mjs) only exist in the game
 * once they are uploaded to Roblox (`npm run cloud -- upload-art`, which writes their ids into
 * design/world-art/assets.json and regenerates worldArtAssets.ts). Until then -- and whenever the client fails to
 * fetch them -- `artId` answers undefined and client/view/worldView.ts draws that surface exactly as it did before
 * the art existed: the same Frames, the same colours. Each texture falls back on its own, so a half-finished
 * upload shows what it has.
 *
 * The same rule as the UI skin (client/ui/skin.ts): a transient miss needs no fallback (an ImageLabel with a valid
 * id draws as soon as the fetch lands), so the art is given up only when every texture is still missing after a
 * retry, which is what a moderated or deleted upload looks like.
 *
 * Nothing here touches the engine at import time, so the Node suites and tools/render-map.mjs can load the view:
 * the fetch starts from `preloadWorldArt()`, called once by the client's boot (main.client.ts).
 */
import { WORLD_ART, WORLD_ART_NAMES, WorldArtName } from "./worldArtAssets";

/** ids handed in by a test or the render tool instead of the uploaded ones (undefined = use WORLD_ART) */
let override: Partial<Record<WorldArtName, string>> | undefined;
/** false once the uploads proved unreachable: every surface is drawn flat from then on */
let fetched = true;
/**
 * Character sheets (client/view/charArt.ts) that still failed to load after the retry. A town surface that is slow
 * to arrive is a blank patch for a moment; a zombie drawn from a sheet that never arrives would be an INVISIBLE
 * zombie (LEG-03, P3), so a character sheet that is still missing is given up on its own and its group -- the
 * survivors, the horde, a boss, the dogs or the birds -- goes back to the flat drawing for the session. So is the item icon
 * atlas: an icon that never arrives would be an empty tile, so client/ui/itemIcon.ts goes back to its Frames.
 */
const lost = new Set<WorldArtName>();
/** told whenever what `artId` answers may have changed (client/ui/itemIcon.ts repaints its live icons) */
const listeners: Array<() => void> = [];

/** calls `fn` after every change of what `artId` answers: an override, or a texture given up after the preload */
export function onWorldArtChange(fn: () => void): void {
	listeners.push(fn);
}

function changed(): void {
	for (const fn of listeners) fn();
}

/** the content id to draw `name` with, or undefined when that surface must be drawn flat */
export function artId(name: WorldArtName): string | undefined {
	if (!fetched) return undefined;
	if (lost.has(name)) return undefined;
	const id = override !== undefined ? override[name] : WORLD_ART[name].id;
	return id === undefined || id === "" ? undefined : id;
}

/** size in texels of a texture (tiles repeat every w x h texels) */
export function artSize(name: WorldArtName): { w: number; h: number } {
	return WORLD_ART[name];
}

/** 9-slice centre of a slice texture, in texels */
export function artSlice(name: WorldArtName): readonly [number, number, number, number] {
	return WORLD_ART[name].slice ?? [0, 0, WORLD_ART[name].w, WORLD_ART[name].h];
}

/**
 * Tests and tools/render-map.mjs: draw with these ids instead of the uploaded ones (an empty table = no art at
 * all, `undefined` = back to the uploads). Also clears a failed fetch.
 */
export function overrideWorldArt(ids: Partial<Record<WorldArtName, string>> | undefined): void {
	override = ids;
	fetched = true;
	lost.clear();
	changed();
}

/** the characters' sheets and masks (tools/character-art.mjs): gameplay needs them whole or not at all */
function isCharacterSheet(name: WorldArtName): boolean {
	return (
		name === "weapons" ||
		name === "zombies" ||
		name === "zombiesFill" ||
		name === "zombiesRim" ||
		name === "dogs" ||
		name === "birds" ||
		name.sub(1, 9) === "survivors" ||
		// the bosses' sheets and masks (ART-14): a boss that never arrives would be an invisible boss
		name.sub(1, 4) === "boss"
	);
}

/** true when at least one texture has an id (the preload has something to fetch) */
export function worldArtUploaded(): boolean {
	for (const name of WORLD_ART_NAMES) if (WORLD_ART[name].id !== "") return true;
	return false;
}

/** a missed texture fetch is often transient; this is how long we wait before asking again */
const RETRY_DELAY = 1;
let preloading = false;

/**
 * Warms the asset cache with every uploaded texture (so the first street is already textured) and gives the art
 * up when none of it can be fetched. Client only; safe to call more than once.
 */
export function preloadWorldArt(): void {
	if (preloading || !worldArtUploaded()) return;
	preloading = true;
	const ContentProvider = game.GetService("ContentProvider");
	task.spawn(() => {
		const ids: Array<string> = [];
		for (const name of WORLD_ART_NAMES) {
			const id = WORLD_ART[name].id;
			if (id !== "") ids.push(id);
		}
		// preloading real ImageLabels, not content strings: skin.ts measured that strings report Failure
		const fetchMissing = (list: Array<string>): Array<string> => {
			const holder = new Instance("Folder");
			holder.Parent = ContentProvider;
			const probes: Array<ImageLabel> = [];
			for (const id of list) {
				const probe = new Instance("ImageLabel");
				probe.Image = id;
				probe.Parent = holder;
				probes.push(probe);
			}
			const missing: Array<string> = [];
			pcall(() =>
				ContentProvider.PreloadAsync(probes, (id: string, status: Enum.AssetFetchStatus) => {
					if (status !== Enum.AssetFetchStatus.Success) missing.push(id);
				}),
			);
			holder.Destroy();
			return missing;
		};
		let missing = fetchMissing(ids);
		if (missing.size() > 0) {
			task.wait(RETRY_DELAY);
			missing = fetchMissing(missing);
		}
		if (missing.size() === 0) return;
		// fixed messages: the Error Report groups by message (docs/ANALYTICS.md §10), the counts are the log line
		print(`[world] art textures missing: ${missing.size()}/${ids.size()}`);
		if (missing.size() >= ids.size()) {
			warn("[world] art textures unavailable: drawing the town flat");
			fetched = false;
			changed();
			return;
		}
		for (const name of WORLD_ART_NAMES) {
			if (isCharacterSheet(name) && missing.includes(WORLD_ART[name].id)) {
				lost.add(name);
				warn(`[world] character sheet ${name} did not load: its characters are drawn flat`);
			}
		}
		if (missing.includes(WORLD_ART.itemIcons.id)) {
			lost.add("itemIcons");
			warn("[world] the item icon atlas did not load: the icons are drawn with Frames");
		}
		// the interiors' atlas: furniture that never arrives would be an invisible shelf that still stops the body
		// (P3, COL-01), so the rooms go back to their Frames
		if (WORLD_ART.furniture.id !== "" && missing.includes(WORLD_ART.furniture.id)) {
			lost.add("furniture");
			warn("[world] the interiors' atlas did not load: the furniture is drawn with Frames");
		}
		// the blood's atlas (ART-15): a stain that never arrives is a fight that leaves nothing, so the blood goes back
		// to its flat drawing
		if (WORLD_ART.blood.id !== "" && missing.includes(WORLD_ART.blood.id)) {
			lost.add("blood");
			warn("[world] the blood's atlas did not load: the blood is drawn flat");
		}
		// the trees' atlas (VEG-06): a crown that never arrives is a trunk that stops the body with nothing drawn on it
		// (P3, COL-01), so the trees go back to their flat drawing
		if (WORLD_ART.trees.id !== "" && missing.includes(WORLD_ART.trees.id)) {
			lost.add("trees");
			warn("[world] the trees' atlas did not load: the trees are drawn flat");
		}
		// the town's fixtures' atlas (ART-16): a market table or a dumpster that never arrives would be an invisible
		// thing that still stops the body (P3, COL-01), so the fixtures go back to their Frames
		if (WORLD_ART.townProps.id !== "" && missing.includes(WORLD_ART.townProps.id)) {
			lost.add("townProps");
			warn("[world] the town's fixtures' atlas did not load: the fixtures are drawn with Frames");
		}
		// the entrances' atlas (ART-17): a doorstep that never arrives would be a door with nothing in front of it, so
		// the entrances go back to their flat drawing
		if (WORLD_ART.entrances.id !== "" && missing.includes(WORLD_ART.entrances.id)) {
			lost.add("entrances");
			warn("[world] the entrances' atlas did not load: the doors are drawn flat");
		}
		if (lost.size() > 0) changed();
		warn("[world] some art textures are slow; keeping the art");
	});
}
