// generated by tools/gen-world-art.mjs — do not edit
// textures: design/world-art/manifest.json, asset ids: design/world-art/assets.json (npm run cloud -- upload-art)
// an empty id turns that texture off: client/view/worldView.ts then draws that surface flat, as before the art

export interface WorldArtAsset {
	/** "rbxassetid://...", or "" until the texture is uploaded */
	id: string;
	/** size in texels (one texel = WORLD_TEXEL world units) */
	w: number;
	h: number;
	/** 9-slice centre in texels (slice textures only) */
	slice?: readonly [number, number, number, number];
}

/** world units per texel of the world art */
export const WORLD_TEXEL = 4;

export type WorldArtName =
	| "asphalt"
	| "asphaltLot"
	| "concrete"
	| "plaza"
	| "pavers"
	| "apron"
	| "grass"
	| "grassLong"
	| "dirt"
	| "soil"
	| "tactile"
	| "paint"
	| "kerbN"
	| "kerbS"
	| "kerbW"
	| "kerbE"
	| "forest"
	| "fenceH"
	| "fenceV"
	| "floorWood"
	| "floorTile"
	| "floorShop"
	| "wall"
	| "roofShingleH"
	| "roofShingleV"
	| "roofGravel"
	| "roofMembrane"
	| "eaves"
	| "parapet"
	| "shadowBox"
	| "canopy0"
	| "canopyShade0"
	| "canopy1"
	| "canopyShade1"
	| "canopy2"
	| "canopyShade2"
	| "car0"
	| "carTrim0"
	| "carDamage0"
	| "carWreck0"
	| "car1"
	| "carTrim1"
	| "carDamage1"
	| "carWreck1"
	| "car2"
	| "carTrim2"
	| "carDamage2"
	| "carWreck2"
	| "car3"
	| "carTrim3"
	| "carDamage3"
	| "carWreck3"
	| "bin"
	| "litter0"
	| "litter1"
	| "litter2"
	| "blood0"
	| "blood1"
	| "oil0"
	| "oil1"
	| "crack0"
	| "crack1"
	| "manhole"
	| "drain"
	| "dispenser"
	| "acUnit"
	| "vent"
	| "chimney"
	| "signSchool"
	| "signHospital"
	| "signGas"
	| "signPharmacy"
	| "signMarket"
	| "signGrocery"
	| "signGuns"
	| "signClothes"
	| "signDiner"
	| "signCollege"
	| "signLibrary"
	| "signLab"
	| "signDorm"
	| "signHardware"
	| "signAutoRepair"
	| "signElectronics"
	| "signBakery"
	| "signPawn"
	| "signPost"
	| "signBank"
	| "signTownHall"
	| "signFire"
	| "signPolice"
	| "signOffice"
	| "helipad"
	| "gasCanopyN"
	| "gasCanopyS"
	| "gasCanopyW"
	| "gasCanopyE"
	| "signPrice"
	| "bicycle"
	| "motorcycle"
	| "machineTurret"
	| "machineTurretHead"
	| "machineShock"
	| "machineBattery"
	| "machineSolar"
	| "machineReactor"
	| "machineOil"
	| "machineLamp"
	| "machinePadTurret"
	| "machinePadLamp"
	| "machineDroneTurret"
	| "machineDroneLamp"
	| "machineBeacon"
	| "machineBeaconDish"
	| "machineCooker"
	| "floorCarpet"
	| "floorKitchen"
	| "floorBath"
	| "wallShade"
	| "survivorsA"
	| "survivorsAFill"
	| "survivorsARim"
	| "survivorsB"
	| "survivorsBFill"
	| "survivorsBRim"
	| "weapons"
	| "zombies"
	| "zombiesFill"
	| "zombiesRim"
	| "dogs"
	| "birds"
	| "bossGiant"
	| "bossGiantFill"
	| "bossGiantRim"
	| "bossHedgehog"
	| "bossHedgehogFill"
	| "bossHedgehogRim"
	| "bossCentipede"
	| "bossCentipedeFill"
	| "bossCentipedeRim"
	| "bossRafflesia"
	| "bossRafflesiaFill"
	| "bossRafflesiaRim"
	| "itemIcons"
	| "furniture"
	| "blood"
	| "townProps"
	| "wordmark";

export const WORLD_ART: Record<WorldArtName, WorldArtAsset> = {
	/** tile: road asphalt: grain and tar blotches (cracks are decals: a crack here would repeat every tile) */
	asphalt: { id: "rbxassetid://139947187986320", w: 64, h: 64 },
	/** tile: parking-lot asphalt, a little more worn */
	asphaltLot: { id: "rbxassetid://131239107246922", w: 64, h: 64 },
	/** tile: sidewalk: 64-unit concrete slabs with joints */
	concrete: { id: "rbxassetid://111427358755563", w: 64, h: 64 },
	/** tile: downtown paving: 32-unit pavers */
	plaza: { id: "rbxassetid://102643064267008", w: 32, h: 32 },
	/** tile: footpaths to the doors: running-bond pavers */
	pavers: { id: "rbxassetid://132631299646338", w: 16, h: 16 },
	/** tile: gas forecourt / ambulance bay: poured concrete panels */
	apron: { id: "rbxassetid://100267191209422", w: 64, h: 64 },
	/** tile: mowed lawn */
	grass: { id: "rbxassetid://80427374458004", w: 64, h: 64 },
	/** tile: a yard nobody mowed for a week or two */
	grassLong: { id: "rbxassetid://81388953288097", w: 64, h: 64 },
	/** tile: packed earth: park paths, the school yard */
	dirt: { id: "rbxassetid://125755328792312", w: 32, h: 32 },
	/** tile: tree pits: bark mulch */
	soil: { id: "rbxassetid://94646897957737", w: 16, h: 16 },
	/** tile: tactile paving where a crosswalk lands */
	tactile: { id: "rbxassetid://100166413819970", w: 4, h: 4 },
	/** tile: road paint, worn (tinted: white zebras, yellow line) */
	paint: { id: "rbxassetid://92406295373977", w: 16, h: 16 },
	/** tile: kerb on a road's north edge (its shadow on the asphalt below) */
	kerbN: { id: "rbxassetid://101511421124634", w: 16, h: 4 },
	/** tile: kerb on a road's south edge */
	kerbS: { id: "rbxassetid://89951142651915", w: 16, h: 4 },
	/** tile: kerb on a road's west edge */
	kerbW: { id: "rbxassetid://124833248981056", w: 4, h: 16 },
	/** tile: kerb on a road's east edge */
	kerbE: { id: "rbxassetid://78814696375156", w: 4, h: 16 },
	/** tile: the forest outside the town fence */
	forest: { id: "rbxassetid://91326499958479", w: 64, h: 64 },
	/** tile: board fence along x */
	fenceH: { id: "rbxassetid://138412336317689", w: 16, h: 2 },
	/** tile: board fence along y */
	fenceV: { id: "rbxassetid://75712248326810", w: 2, h: 16 },
	/** tile: house floors: boards */
	floorWood: { id: "rbxassetid://136167035387400", w: 32, h: 32 },
	/** tile: hospital / pharmacy floor: checker tiles */
	floorTile: { id: "rbxassetid://117700490808662", w: 16, h: 16 },
	/** tile: shop floor: vinyl tiles */
	floorShop: { id: "rbxassetid://98147886555678", w: 32, h: 32 },
	/** tileTint: walls: plaster (tint: the wall colour) */
	wall: { id: "rbxassetid://91890690308632", w: 8, h: 8 },
	/** tileTint: pitched roof shingles, courses along x (tint: roof colour) */
	roofShingleH: { id: "rbxassetid://121254808626668", w: 32, h: 32 },
	/** tileTint: pitched roof shingles, courses along y */
	roofShingleV: { id: "rbxassetid://87243143362861", w: 32, h: 32 },
	/** tileTint: flat roof: tar and gravel (shops) */
	roofGravel: { id: "rbxassetid://74993087626157", w: 32, h: 32 },
	/** tileTint: flat roof: welded membrane (school, hospital, gas) */
	roofMembrane: { id: "rbxassetid://125463832458495", w: 64, h: 64 },
	/** slice: pitched roof rim: drip edge and fascia */
	eaves: { id: "rbxassetid://129151899583010", w: 12, h: 12, slice: [4, 4, 8, 8] },
	/** slice: flat roof rim: parapet, coping, inner face */
	parapet: { id: "rbxassetid://106192217360435", w: 12, h: 12, slice: [4, 4, 8, 8] },
	/** slice: soft rectangular drop shadow */
	shadowBox: { id: "rbxassetid://126704842880759", w: 16, h: 16, slice: [6, 6, 10, 10] },
	/** mask: tree crown 1: silhouette + leaves (tint: foliage) */
	canopy0: { id: "rbxassetid://135695969741387", w: 40, h: 40 },
	/** overlay: tree crown 1: light, shadow and outline */
	canopyShade0: { id: "rbxassetid://112795457788106", w: 40, h: 40 },
	/** mask: tree crown 2: silhouette + leaves (tint: foliage) */
	canopy1: { id: "rbxassetid://94759302502078", w: 40, h: 40 },
	/** overlay: tree crown 2: light, shadow and outline */
	canopyShade1: { id: "rbxassetid://124845124258321", w: 40, h: 40 },
	/** mask: tree crown 3: silhouette + leaves (tint: foliage) */
	canopy2: { id: "rbxassetid://91170123216072", w: 40, h: 40 },
	/** overlay: tree crown 3: light, shadow and outline */
	canopyShade2: { id: "rbxassetid://93088950930991", w: 40, h: 40 },
	/** mask: sedan: body (tint: paint) */
	car0: { id: "rbxassetid://127118296635301", w: 50, h: 25 },
	/** overlay: sedan: glass, lights, wheels, outline */
	carTrim0: { id: "rbxassetid://136877247095838", w: 50, h: 25 },
	/** overlay: sedan: smashed windshield, scratches */
	carDamage0: { id: "rbxassetid://122941375766700", w: 50, h: 25 },
	/** overlay: sedan: burnt out */
	carWreck0: { id: "rbxassetid://81238785313822", w: 50, h: 25 },
	/** mask: hatch: body (tint: paint) */
	car1: { id: "rbxassetid://117984683875354", w: 50, h: 25 },
	/** overlay: hatch: glass, lights, wheels, outline */
	carTrim1: { id: "rbxassetid://135220244687740", w: 50, h: 25 },
	/** overlay: hatch: smashed windshield, scratches */
	carDamage1: { id: "rbxassetid://84660138593018", w: 50, h: 25 },
	/** overlay: hatch: burnt out */
	carWreck1: { id: "rbxassetid://94089899562906", w: 50, h: 25 },
	/** mask: pickup: body (tint: paint) */
	car2: { id: "rbxassetid://78626762304650", w: 50, h: 25 },
	/** overlay: pickup: glass, lights, wheels, outline */
	carTrim2: { id: "rbxassetid://129271563156608", w: 50, h: 25 },
	/** overlay: pickup: smashed windshield, scratches */
	carDamage2: { id: "rbxassetid://98615341526064", w: 50, h: 25 },
	/** overlay: pickup: burnt out */
	carWreck2: { id: "rbxassetid://74099595483767", w: 50, h: 25 },
	/** mask: suv: body (tint: paint) */
	car3: { id: "rbxassetid://123263422642170", w: 50, h: 25 },
	/** overlay: suv: glass, lights, wheels, outline */
	carTrim3: { id: "rbxassetid://104792167977459", w: 50, h: 25 },
	/** overlay: suv: smashed windshield, scratches */
	carDamage3: { id: "rbxassetid://117701098851376", w: 50, h: 25 },
	/** overlay: suv: burnt out */
	carWreck3: { id: "rbxassetid://118498588242035", w: 50, h: 25 },
	/** sprite: wheelie bin */
	bin: { id: "rbxassetid://140632839899508", w: 9, h: 9 },
	/** sprite: spilled litter (flat) */
	litter0: { id: "rbxassetid://81384883889550", w: 12, h: 12 },
	/** sprite: spilled litter (flat) */
	litter1: { id: "rbxassetid://106240577299149", w: 12, h: 12 },
	/** sprite: spilled litter (flat) */
	litter2: { id: "rbxassetid://108989596532824", w: 12, h: 12 },
	/** sprite: dried blood */
	blood0: { id: "rbxassetid://78229349933249", w: 16, h: 12 },
	/** sprite: dried blood */
	blood1: { id: "rbxassetid://107297349179269", w: 16, h: 12 },
	/** sprite: oil stain */
	oil0: { id: "rbxassetid://81641439232774", w: 16, h: 12 },
	/** sprite: oil stain */
	oil1: { id: "rbxassetid://132324497387006", w: 16, h: 12 },
	/** sprite: asphalt crack */
	crack0: { id: "rbxassetid://106669207312072", w: 24, h: 8 },
	/** sprite: asphalt crack */
	crack1: { id: "rbxassetid://79739241366295", w: 24, h: 8 },
	/** sprite: manhole cover */
	manhole: { id: "rbxassetid://96964095561833", w: 8, h: 8 },
	/** sprite: storm drain */
	drain: { id: "rbxassetid://96075237212369", w: 8, h: 4 },
	/** sprite: fuel dispenser, upright: the station sign's white cabinet, dark display, red stripe, hose and nozzle */
	dispenser: { id: "rbxassetid://80245658163921", w: 10, h: 13 },
	/** sprite: rooftop air conditioner */
	acUnit: { id: "rbxassetid://136406701811442", w: 13, h: 11 },
	/** sprite: roof vent */
	vent: { id: "rbxassetid://137900443333837", w: 7, h: 7 },
	/** sprite: brick chimney on a house roof */
	chimney: { id: "rbxassetid://101480024173884", w: 8, h: 8 },
	/** sprite: storefront sign (type 3): an open book on a chalkboard */
	signSchool: { id: "rbxassetid://114639792286723", w: 32, h: 20 },
	/** sprite: storefront sign (type 4): the white H of the hospital road sign, on blue */
	signHospital: { id: "rbxassetid://138502146199770", w: 32, h: 20 },
	/** sprite: storefront sign (type 5): a fuel pump, its hose and nozzle hanging on its side */
	signGas: { id: "rbxassetid://108554848118783", w: 24, h: 16 },
	/** sprite: storefront sign (type 6): a green cross lightbox */
	signPharmacy: { id: "rbxassetid://96112656262295", w: 24, h: 16 },
	/** sprite: storefront sign (type 7): a shopping cart */
	signMarket: { id: "rbxassetid://93005756413658", w: 32, h: 20 },
	/** sprite: storefront sign (type 8): a paper grocery bag with a baguette and an apple */
	signGrocery: { id: "rbxassetid://72537450007132", w: 24, h: 16 },
	/** sprite: storefront sign (type 9): a pistol */
	signGuns: { id: "rbxassetid://117357221086062", w: 24, h: 16 },
	/** sprite: storefront sign (type 10): a T-shirt */
	signClothes: { id: "rbxassetid://112674003076505", w: 24, h: 16 },
	/** sprite: storefront sign (type 11): a plate between a fork and a knife */
	signDiner: { id: "rbxassetid://128089711622782", w: 32, h: 20 },
	/** sprite: storefront sign (type 12): a mortarboard, its lit top and its cap, the gold tassel hanging off its corner, on the college's maroon */
	signCollege: { id: "rbxassetid://80455916168349", w: 24, h: 16 },
	/** sprite: storefront sign (type 13): books standing on a shelf, gold bands on their spines, on the college's maroon */
	signLibrary: { id: "rbxassetid://118093291454515", w: 24, h: 16 },
	/** sprite: storefront sign (type 14): a flask of green reagent and a test tube, on the college's maroon */
	signLab: { id: "rbxassetid://118500150708359", w: 24, h: 16 },
	/** sprite: storefront sign (type 15): a bunk bed, pillows and blankets on both bunks, on the college's maroon */
	signDorm: { id: "rbxassetid://101587899989297", w: 24, h: 16 },
	/** sprite: storefront sign (type 16): a claw hammer, its steel head over a wooden handle, on hardware orange */
	signHardware: { id: "", w: 24, h: 16 },
	/** sprite: storefront sign (type 17): a wheel: the black tyre, its white rim and the hub, on slate blue */
	signAutoRepair: { id: "", w: 24, h: 16 },
	/** sprite: storefront sign (type 18): a yellow lightning bolt, on indigo */
	signElectronics: { id: "", w: 24, h: 16 },
	/** sprite: storefront sign (type 19): a scored loaf of bread, on rose */
	signBakery: { id: "", w: 24, h: 16 },
	/** sprite: storefront sign (type 20): the pawnbroker's three gold balls hanging from their bar, on dark brown */
	signPawn: { id: "", w: 24, h: 16 },
	/** sprite: storefront sign (type 21): an envelope, its flap folded down, on post blue */
	signPost: { id: "", w: 24, h: 16 },
	/** sprite: storefront sign (type 22): a classical front: pediment, four columns and the steps, on bronze */
	signBank: { id: "", w: 24, h: 16 },
	/** sprite: storefront sign (type 23): the town hall: a clock tower over its two wings and the front door, on lavender */
	signTownHall: { id: "", w: 24, h: 16 },
	/** sprite: storefront sign (type 24): a yellow flame, its white-hot heart, on fire-engine red */
	signFire: { id: "", w: 24, h: 16 },
	/** sprite: storefront sign (type 25): a navy shield with a gold star, on pale blue */
	signPolice: { id: "", w: 24, h: 16 },
	/** sprite: storefront sign (type 26): a briefcase, its brass clasp, on sea-glass green */
	signOffice: { id: "", w: 24, h: 16 },
	/** sprite: hospital roof: the heliport's red H on a white cross */
	helipad: { id: "rbxassetid://94643764245261", w: 64, h: 64 },
	/** sprite: gas station canopy roof, street to the N: charcoal fascia with a red pinstripe, standing seams, fixtures, drains, weather */
	gasCanopyN: { id: "rbxassetid://125205539029145", w: 113, h: 29 },
	/** sprite: gas station canopy roof, street to the S: charcoal fascia with a red pinstripe, standing seams, fixtures, drains, weather */
	gasCanopyS: { id: "rbxassetid://108385533523804", w: 113, h: 29 },
	/** sprite: gas station canopy roof, street to the W: charcoal fascia with a red pinstripe, standing seams, fixtures, drains, weather */
	gasCanopyW: { id: "rbxassetid://115098962444579", w: 29, h: 113 },
	/** sprite: gas station canopy roof, street to the E: charcoal fascia with a red pinstripe, standing seams, fixtures, drains, weather */
	gasCanopyE: { id: "rbxassetid://121551836533975", w: 29, h: 113 },
	/** sprite: gas station price sign: a price pylon: the pump pictogram over three grade tabs and their dark price panels, on a steel post */
	signPrice: { id: "rbxassetid://128067960365536", w: 16, h: 25 },
	/** sprite: a bicycle from above, nose to +x: tyres, frame, pedals, saddle, bars */
	bicycle: { id: "rbxassetid://109042532253105", w: 18, h: 7 },
	/** sprite: a motorcycle from above, nose to +x: tank, seat, engine, exhaust, lamp */
	motorcycle: { id: "rbxassetid://82910695205219", w: 22, h: 8 },
	/** sprite: the turret's mount: an octagonal steel plate, the ring the head turns on, four bolts */
	machineTurret: { id: "rbxassetid://83961163882556", w: 16, h: 16 },
	/** sprite: the turret's head: a blue dome and the barrel, pointing +x (it turns) */
	machineTurretHead: { id: "rbxassetid://105237041592826", w: 13, h: 8 },
	/** sprite: the electric turret: copper coil rings round a steel terminal */
	machineShock: { id: "rbxassetid://136617266292268", w: 16, h: 16 },
	/** sprite: the battery box: blue case, the gauge window, the two posts */
	machineBattery: { id: "rbxassetid://99032517010832", w: 10, h: 10 },
	/** sprite: the solar generator: nine blue cells in a steel frame */
	machineSolar: { id: "rbxassetid://71820992740459", w: 18, h: 18 },
	/** sprite: the nuclear reactor: the vessel, its hazard band, the dome and the core */
	machineReactor: { id: "rbxassetid://124251372179356", w: 20, h: 20 },
	/** sprite: the oil generator: the radiator grille, the red tank and its cap, the exhaust */
	machineOil: { id: "rbxassetid://121680069491151", w: 18, h: 18 },
	/** sprite: the lamp: a floodlight head on its plate */
	machineLamp: { id: "rbxassetid://121600531471634", w: 12, h: 12 },
	/** sprite: the turret drone's pad: the charging ring and its contacts */
	machinePadTurret: { id: "rbxassetid://95516115101180", w: 12, h: 12 },
	/** sprite: the lamp drone's pad */
	machinePadLamp: { id: "rbxassetid://106435819341933", w: 10, h: 10 },
	/** sprite: the turret drone: four rotors, the body and its gun, pointing +x (it turns) */
	machineDroneTurret: { id: "rbxassetid://95984277760340", w: 11, h: 11 },
	/** sprite: the lamp drone: four rotors and the lamp */
	machineDroneLamp: { id: "rbxassetid://139066066075741", w: 11, h: 11 },
	/** sprite: the signal generator's base: the plate and the mast */
	machineBeacon: { id: "rbxassetid://84669381930230", w: 12, h: 12 },
	/** sprite: the signal generator's dish, facing +x (it turns) */
	machineBeaconDish: { id: "rbxassetid://114854108137842", w: 6, h: 7 },
	/** sprite: the cooker: a steel top with two plates and the knobs */
	machineCooker: { id: "rbxassetid://100036293760025", w: 14, h: 12 },
	/** tile: bedroom / office carpet: a low loop pile */
	floorCarpet: { id: "rbxassetid://76218697454378", w: 16, h: 16 },
	/** tile: kitchen floor: checker tiles */
	floorKitchen: { id: "rbxassetid://118028356616797", w: 16, h: 16 },
	/** tile: bathroom / cold room: small tiles */
	floorBath: { id: "rbxassetid://114108861727270", w: 16, h: 16 },
	/** slice: an interior wall's outline (its centre, tinted) and the shadow at its foot */
	wallShade: { id: "rbxassetid://115914959931221", w: 7, h: 7, slice: [3, 3, 4, 4] },
	/** sheet: survivors, plain and Santa: 4 grips x 3 strides, 5 swings, 3 crawls, whole body and arms in one cell (ART-09) */
	survivorsA: { id: "rbxassetid://72971918566679", w: 640, h: 800 },
	/** mask: survivorsA: white silhouettes of the same cells (tint: hit flash, poison) */
	survivorsAFill: { id: "rbxassetid://130233128777158", w: 640, h: 800 },
	/** mask: survivorsA: white outlines of the same cells (tint: the red hit outline, LEG-02) */
	survivorsARim: { id: "rbxassetid://119464774075098", w: 640, h: 800 },
	/** sheet: survivors, Zombie costume and Cowboy: 4 grips x 3 strides, 5 swings, 3 crawls, whole body and arms (ART-09) */
	survivorsB: { id: "rbxassetid://86243325431728", w: 640, h: 800 },
	/** mask: survivorsB: white silhouettes of the same cells (tint: hit flash, poison) */
	survivorsBFill: { id: "rbxassetid://92264708269652", w: 640, h: 800 },
	/** mask: survivorsB: white outlines of the same cells (tint: the red hit outline, LEG-02) */
	survivorsBRim: { id: "rbxassetid://71330821045410", w: 640, h: 800 },
	/** sheet: weapons in hand: each melee weapon swung and held, then the guns and bows (ART-09) */
	weapons: { id: "rbxassetid://90202612381580", w: 768, h: 840 },
	/** sheet: zombies: walker, spitter, exploder, charger, jumper x 3 strides; spitter wind-ups, jumper in the air, charger charging (ART-10) */
	zombies: { id: "rbxassetid://138455388765953", w: 768, h: 504 },
	/** mask: zombies: white silhouettes of the same cells (tint: hit flash, lit fuse) */
	zombiesFill: { id: "rbxassetid://121468047822975", w: 768, h: 504 },
	/** mask: zombies: white outlines of the same cells (tint: the hit outline, the lit fuse's yellow) */
	zombiesRim: { id: "rbxassetid://125308639707087", w: 768, h: 504 },
	/** sheet: pets: Carolina, Malamute, Doberman x 3 trot strides + 3 tail wags (ART-11) */
	dogs: { id: "rbxassetid://90855133643247", w: 576, h: 324 },
	/** sheet: pets: Pigeon, White pigeon, Eagle x landed + 4 wing spreads (ART-11) */
	birds: { id: "rbxassetid://103677264883916", w: 768, h: 360 },
	/** sheet: boss 3, the giant: 3 strides + the lunge x 32 headings (two bands of 16) (ART-14) */
	bossGiant: { id: "rbxassetid://119328056365175", w: 640, h: 320 },
	/** mask: bossGiant: white silhouettes of the same cells (tint: hit flash) */
	bossGiantFill: { id: "rbxassetid://97770426653085", w: 640, h: 320 },
	/** mask: bossGiant: white outlines of the same cells (tint: the hit outline) */
	bossGiantRim: { id: "rbxassetid://80843211195047", w: 640, h: 320 },
	/** sheet: boss 4, the hedgehog: 3 strides x 32 headings (two bands of 16) (ART-14) */
	bossHedgehog: { id: "rbxassetid://73507768340942", w: 640, h: 240 },
	/** mask: bossHedgehog: white silhouettes of the same cells (tint: hit flash) */
	bossHedgehogFill: { id: "rbxassetid://79135650137095", w: 640, h: 240 },
	/** mask: bossHedgehog: white outlines of the same cells (tint: the hit outline) */
	bossHedgehogRim: { id: "rbxassetid://119127789280354", w: 640, h: 240 },
	/** sheet: boss 1, the centipede: head (fangs shut, open), body segment x 3 leg beats, tail x 32 headings (ART-14) */
	bossCentipede: { id: "rbxassetid://136951627821617", w: 640, h: 480 },
	/** mask: bossCentipede: white silhouettes of the same cells (tint: hit flash) */
	bossCentipedeFill: { id: "rbxassetid://96385645324175", w: 640, h: 480 },
	/** mask: bossCentipede: white outlines of the same cells (tint: the hit outline) */
	bossCentipedeRim: { id: "rbxassetid://121384731032432", w: 640, h: 480 },
	/** sheet: boss 2, the rafflesia: 12 beats of its six vines sweeping round (it never turns) (ART-14) */
	bossRafflesia: { id: "rbxassetid://104897167530631", w: 816, h: 68 },
	/** mask: bossRafflesia: white silhouettes of the same cells (tint: hit flash) */
	bossRafflesiaFill: { id: "rbxassetid://76796714766849", w: 816, h: 68 },
	/** mask: bossRafflesia: white outlines of the same cells (tint: the hit outline) */
	bossRafflesiaRim: { id: "rbxassetid://125105479176447", w: 816, h: 68 },
	/** atlas: item icons: 99 icons, their dimmed copies and 11 glyphs (client/ui/itemIcon.ts) */
	itemIcons: { id: "rbxassetid://89487834990160", w: 288, h: 244 },
	/** atlas: interiors: 1707 cells of furniture, decoration and frames (client/view/interiorArt.ts) */
	furniture: { id: "", w: 1024, h: 923 },
	/** atlas: combat blood: 44 cells of drops, splats and smears, matte and wet (client/view/bloodView.ts) */
	blood: { id: "rbxassetid://138018740222052", w: 96, h: 264 },
	/** atlas: the town's fixtures: 306 cells of market, street, park, backyard and building-site pieces and their ground (client/view/townPropArt.ts) */
	townProps: { id: "", w: 1024, h: 662 },
	/** ui: the LAST TOWN wordmark: three 86 x 13 cells top to bottom, the ink (tint: background), the fill of LAST (tint: brand) and of TOWN (tint: foreground) (client/ui/logo.ts) */
	wordmark: { id: "rbxassetid://132745135799721", w: 86, h: 39 },
};

/** every texture of the world art (the item icon atlas too), for the preload pass */
export const WORLD_ART_NAMES: Array<WorldArtName> = [
	"asphalt",
	"asphaltLot",
	"concrete",
	"plaza",
	"pavers",
	"apron",
	"grass",
	"grassLong",
	"dirt",
	"soil",
	"tactile",
	"paint",
	"kerbN",
	"kerbS",
	"kerbW",
	"kerbE",
	"forest",
	"fenceH",
	"fenceV",
	"floorWood",
	"floorTile",
	"floorShop",
	"wall",
	"roofShingleH",
	"roofShingleV",
	"roofGravel",
	"roofMembrane",
	"eaves",
	"parapet",
	"shadowBox",
	"canopy0",
	"canopyShade0",
	"canopy1",
	"canopyShade1",
	"canopy2",
	"canopyShade2",
	"car0",
	"carTrim0",
	"carDamage0",
	"carWreck0",
	"car1",
	"carTrim1",
	"carDamage1",
	"carWreck1",
	"car2",
	"carTrim2",
	"carDamage2",
	"carWreck2",
	"car3",
	"carTrim3",
	"carDamage3",
	"carWreck3",
	"bin",
	"litter0",
	"litter1",
	"litter2",
	"blood0",
	"blood1",
	"oil0",
	"oil1",
	"crack0",
	"crack1",
	"manhole",
	"drain",
	"dispenser",
	"acUnit",
	"vent",
	"chimney",
	"signSchool",
	"signHospital",
	"signGas",
	"signPharmacy",
	"signMarket",
	"signGrocery",
	"signGuns",
	"signClothes",
	"signDiner",
	"signCollege",
	"signLibrary",
	"signLab",
	"signDorm",
	"signHardware",
	"signAutoRepair",
	"signElectronics",
	"signBakery",
	"signPawn",
	"signPost",
	"signBank",
	"signTownHall",
	"signFire",
	"signPolice",
	"signOffice",
	"helipad",
	"gasCanopyN",
	"gasCanopyS",
	"gasCanopyW",
	"gasCanopyE",
	"signPrice",
	"bicycle",
	"motorcycle",
	"machineTurret",
	"machineTurretHead",
	"machineShock",
	"machineBattery",
	"machineSolar",
	"machineReactor",
	"machineOil",
	"machineLamp",
	"machinePadTurret",
	"machinePadLamp",
	"machineDroneTurret",
	"machineDroneLamp",
	"machineBeacon",
	"machineBeaconDish",
	"machineCooker",
	"floorCarpet",
	"floorKitchen",
	"floorBath",
	"wallShade",
	"survivorsA",
	"survivorsAFill",
	"survivorsARim",
	"survivorsB",
	"survivorsBFill",
	"survivorsBRim",
	"weapons",
	"zombies",
	"zombiesFill",
	"zombiesRim",
	"dogs",
	"birds",
	"bossGiant",
	"bossGiantFill",
	"bossGiantRim",
	"bossHedgehog",
	"bossHedgehogFill",
	"bossHedgehogRim",
	"bossCentipede",
	"bossCentipedeFill",
	"bossCentipedeRim",
	"bossRafflesia",
	"bossRafflesiaFill",
	"bossRafflesiaRim",
	"itemIcons",
	"furniture",
	"blood",
	"townProps",
	"wordmark",
];
