/*
 * Which pieces of the world art are live, and the flat fallback.
 *
 * The town's textures and sprites (design/world-art, generated by tools/gen-world-art.mjs) only exist in the game
 * once they are uploaded to Roblox (`npm run cloud -- upload-art`, which writes their ids into
 * design/world-art/assets.json and regenerates worldArtAssets.ts). Until then -- and whenever the client fails to
 * fetch them -- `artId` answers undefined and client/view/worldView.ts draws that surface exactly as it did before
 * the art existed: the same Frames, the same colours. Each texture falls back on its own, so a half-finished
 * upload shows what it has.
 *
 * The same rule as the UI skin (client/ui/skin.ts): a transient miss needs no fallback (an ImageLabel with a valid
 * id draws as soon as the fetch lands), so the art is given up only when every texture is still missing after a
 * retry, which is what a moderated or deleted upload looks like.
 *
 * Nothing here touches the engine at import time, so the Node suites and tools/render-map.mjs can load the view:
 * the fetch starts from `preloadWorldArt()`, called once by the client's boot (main.client.ts).
 */
import { WORLD_ART, WORLD_ART_NAMES, WorldArtName } from "./worldArtAssets";

/** ids handed in by a test or the render tool instead of the uploaded ones (undefined = use WORLD_ART) */
let override: Partial<Record<WorldArtName, string>> | undefined;
/** false once the uploads proved unreachable: every surface is drawn flat from then on */
let fetched = true;

/** the content id to draw `name` with, or undefined when that surface must be drawn flat */
export function artId(name: WorldArtName): string | undefined {
	if (!fetched) return undefined;
	const id = override !== undefined ? override[name] : WORLD_ART[name].id;
	return id === undefined || id === "" ? undefined : id;
}

/** size in texels of a texture (tiles repeat every w x h texels) */
export function artSize(name: WorldArtName): { w: number; h: number } {
	return WORLD_ART[name];
}

/** 9-slice centre of a slice texture, in texels */
export function artSlice(name: WorldArtName): readonly [number, number, number, number] {
	return WORLD_ART[name].slice ?? [0, 0, WORLD_ART[name].w, WORLD_ART[name].h];
}

/**
 * Tests and tools/render-map.mjs: draw with these ids instead of the uploaded ones (an empty table = no art at
 * all, `undefined` = back to the uploads). Also clears a failed fetch.
 */
export function overrideWorldArt(ids: Partial<Record<WorldArtName, string>> | undefined): void {
	override = ids;
	fetched = true;
}

/** true when at least one texture has an id (the preload has something to fetch) */
export function worldArtUploaded(): boolean {
	for (const name of WORLD_ART_NAMES) if (WORLD_ART[name].id !== "") return true;
	return false;
}

/** a missed texture fetch is often transient; this is how long we wait before asking again */
const RETRY_DELAY = 1;
let preloading = false;

/**
 * Warms the asset cache with every uploaded texture (so the first street is already textured) and gives the art
 * up when none of it can be fetched. Client only; safe to call more than once.
 */
export function preloadWorldArt(): void {
	if (preloading || !worldArtUploaded()) return;
	preloading = true;
	const ContentProvider = game.GetService("ContentProvider");
	task.spawn(() => {
		const ids: Array<string> = [];
		for (const name of WORLD_ART_NAMES) {
			const id = WORLD_ART[name].id;
			if (id !== "") ids.push(id);
		}
		// preloading real ImageLabels, not content strings: skin.ts measured that strings report Failure
		const fetchMissing = (list: Array<string>): Array<string> => {
			const holder = new Instance("Folder");
			holder.Parent = ContentProvider;
			const probes: Array<ImageLabel> = [];
			for (const id of list) {
				const probe = new Instance("ImageLabel");
				probe.Image = id;
				probe.Parent = holder;
				probes.push(probe);
			}
			const missing: Array<string> = [];
			pcall(() =>
				ContentProvider.PreloadAsync(probes, (id: string, status: Enum.AssetFetchStatus) => {
					if (status !== Enum.AssetFetchStatus.Success) missing.push(id);
				}),
			);
			holder.Destroy();
			return missing;
		};
		let missing = fetchMissing(ids);
		if (missing.size() > 0) {
			task.wait(RETRY_DELAY);
			missing = fetchMissing(missing);
		}
		if (missing.size() === 0) return;
		if (missing.size() >= ids.size()) {
			warn(`[world] art textures unavailable (${missing.size()}/${ids.size()}): drawing the town flat`);
			fetched = false;
			return;
		}
		warn(`[world] ${missing.size()}/${ids.size()} art textures are slow; keeping the art`);
	});
}
