// generated by tools/gen-world-art.mjs — do not edit
// textures: design/world-art/manifest.json, asset ids: design/world-art/assets.json (npm run cloud -- upload-art)
// an empty id turns that texture off: client/view/worldView.ts then draws that surface flat, as before the art

export interface WorldArtAsset {
	/** "rbxassetid://...", or "" until the texture is uploaded */
	id: string;
	/** size in texels (one texel = WORLD_TEXEL world units) */
	w: number;
	h: number;
	/** 9-slice centre in texels (slice textures only) */
	slice?: readonly [number, number, number, number];
}

/** world units per texel of the world art */
export const WORLD_TEXEL = 4;

export type WorldArtName =
	| "asphalt"
	| "asphaltLot"
	| "concrete"
	| "plaza"
	| "pavers"
	| "apron"
	| "grass"
	| "grassLong"
	| "dirt"
	| "soil"
	| "tactile"
	| "paint"
	| "kerbN"
	| "kerbS"
	| "kerbW"
	| "kerbE"
	| "forest"
	| "fenceH"
	| "fenceV"
	| "floorWood"
	| "floorTile"
	| "floorShop"
	| "wall"
	| "roofShingleH"
	| "roofShingleV"
	| "roofGravel"
	| "roofMembrane"
	| "eaves"
	| "parapet"
	| "shadowBox"
	| "canopy0"
	| "canopyShade0"
	| "canopy1"
	| "canopyShade1"
	| "canopy2"
	| "canopyShade2"
	| "car0"
	| "carTrim0"
	| "carDamage0"
	| "carWreck0"
	| "car1"
	| "carTrim1"
	| "carDamage1"
	| "carWreck1"
	| "car2"
	| "carTrim2"
	| "carDamage2"
	| "carWreck2"
	| "car3"
	| "carTrim3"
	| "carDamage3"
	| "carWreck3"
	| "bin"
	| "litter0"
	| "litter1"
	| "litter2"
	| "blood0"
	| "blood1"
	| "oil0"
	| "oil1"
	| "crack0"
	| "crack1"
	| "manhole"
	| "drain"
	| "pump"
	| "acUnit"
	| "vent"
	| "chimney";

export const WORLD_ART: Record<WorldArtName, WorldArtAsset> = {
	/** tile: road asphalt: grain and tar blotches (cracks are decals: a crack here would repeat every tile) */
	asphalt: { id: "", w: 64, h: 64 },
	/** tile: parking-lot asphalt, a little more worn */
	asphaltLot: { id: "", w: 64, h: 64 },
	/** tile: sidewalk: 64-unit concrete slabs with joints */
	concrete: { id: "", w: 64, h: 64 },
	/** tile: downtown paving: 32-unit pavers */
	plaza: { id: "", w: 32, h: 32 },
	/** tile: footpaths to the doors: running-bond pavers */
	pavers: { id: "", w: 16, h: 16 },
	/** tile: gas forecourt / ambulance bay: poured concrete panels */
	apron: { id: "", w: 64, h: 64 },
	/** tile: mowed lawn */
	grass: { id: "", w: 64, h: 64 },
	/** tile: a yard nobody mowed for a week or two */
	grassLong: { id: "", w: 64, h: 64 },
	/** tile: packed earth: park paths, the school yard */
	dirt: { id: "", w: 32, h: 32 },
	/** tile: tree pits: bark mulch */
	soil: { id: "", w: 16, h: 16 },
	/** tile: tactile paving where a crosswalk lands */
	tactile: { id: "", w: 4, h: 4 },
	/** tile: road paint, worn (tinted: white zebras, yellow line) */
	paint: { id: "", w: 16, h: 16 },
	/** tile: kerb on a road's north edge (its shadow on the asphalt below) */
	kerbN: { id: "", w: 16, h: 4 },
	/** tile: kerb on a road's south edge */
	kerbS: { id: "", w: 16, h: 4 },
	/** tile: kerb on a road's west edge */
	kerbW: { id: "", w: 4, h: 16 },
	/** tile: kerb on a road's east edge */
	kerbE: { id: "", w: 4, h: 16 },
	/** tile: the forest outside the town fence */
	forest: { id: "", w: 64, h: 64 },
	/** tile: board fence along x */
	fenceH: { id: "", w: 16, h: 2 },
	/** tile: board fence along y */
	fenceV: { id: "", w: 2, h: 16 },
	/** tile: house floors: boards */
	floorWood: { id: "", w: 32, h: 32 },
	/** tile: hospital / pharmacy floor: checker tiles */
	floorTile: { id: "", w: 16, h: 16 },
	/** tile: shop floor: vinyl tiles */
	floorShop: { id: "", w: 32, h: 32 },
	/** tileTint: walls: plaster (tint: the wall colour) */
	wall: { id: "", w: 8, h: 8 },
	/** tileTint: pitched roof shingles, courses along x (tint: roof colour) */
	roofShingleH: { id: "", w: 32, h: 32 },
	/** tileTint: pitched roof shingles, courses along y */
	roofShingleV: { id: "", w: 32, h: 32 },
	/** tileTint: flat roof: tar and gravel (shops) */
	roofGravel: { id: "", w: 32, h: 32 },
	/** tileTint: flat roof: welded membrane (school, hospital, gas) */
	roofMembrane: { id: "", w: 64, h: 64 },
	/** slice: pitched roof rim: drip edge and fascia */
	eaves: { id: "", w: 12, h: 12, slice: [4, 4, 8, 8] },
	/** slice: flat roof rim: parapet, coping, inner face */
	parapet: { id: "", w: 12, h: 12, slice: [4, 4, 8, 8] },
	/** slice: soft rectangular drop shadow */
	shadowBox: { id: "", w: 16, h: 16, slice: [6, 6, 10, 10] },
	/** mask: tree crown 1: silhouette + leaves (tint: foliage) */
	canopy0: { id: "", w: 40, h: 40 },
	/** overlay: tree crown 1: light, shadow and outline */
	canopyShade0: { id: "", w: 40, h: 40 },
	/** mask: tree crown 2: silhouette + leaves (tint: foliage) */
	canopy1: { id: "", w: 40, h: 40 },
	/** overlay: tree crown 2: light, shadow and outline */
	canopyShade1: { id: "", w: 40, h: 40 },
	/** mask: tree crown 3: silhouette + leaves (tint: foliage) */
	canopy2: { id: "", w: 40, h: 40 },
	/** overlay: tree crown 3: light, shadow and outline */
	canopyShade2: { id: "", w: 40, h: 40 },
	/** mask: sedan: body (tint: paint) */
	car0: { id: "", w: 50, h: 25 },
	/** overlay: sedan: glass, lights, wheels, outline */
	carTrim0: { id: "", w: 50, h: 25 },
	/** overlay: sedan: smashed windshield, scratches */
	carDamage0: { id: "", w: 50, h: 25 },
	/** overlay: sedan: burnt out */
	carWreck0: { id: "", w: 50, h: 25 },
	/** mask: hatch: body (tint: paint) */
	car1: { id: "", w: 50, h: 25 },
	/** overlay: hatch: glass, lights, wheels, outline */
	carTrim1: { id: "", w: 50, h: 25 },
	/** overlay: hatch: smashed windshield, scratches */
	carDamage1: { id: "", w: 50, h: 25 },
	/** overlay: hatch: burnt out */
	carWreck1: { id: "", w: 50, h: 25 },
	/** mask: pickup: body (tint: paint) */
	car2: { id: "", w: 50, h: 25 },
	/** overlay: pickup: glass, lights, wheels, outline */
	carTrim2: { id: "", w: 50, h: 25 },
	/** overlay: pickup: smashed windshield, scratches */
	carDamage2: { id: "", w: 50, h: 25 },
	/** overlay: pickup: burnt out */
	carWreck2: { id: "", w: 50, h: 25 },
	/** mask: suv: body (tint: paint) */
	car3: { id: "", w: 50, h: 25 },
	/** overlay: suv: glass, lights, wheels, outline */
	carTrim3: { id: "", w: 50, h: 25 },
	/** overlay: suv: smashed windshield, scratches */
	carDamage3: { id: "", w: 50, h: 25 },
	/** overlay: suv: burnt out */
	carWreck3: { id: "", w: 50, h: 25 },
	/** sprite: wheelie bin */
	bin: { id: "", w: 9, h: 9 },
	/** sprite: spilled litter (flat) */
	litter0: { id: "", w: 12, h: 12 },
	/** sprite: spilled litter (flat) */
	litter1: { id: "", w: 12, h: 12 },
	/** sprite: spilled litter (flat) */
	litter2: { id: "", w: 12, h: 12 },
	/** sprite: dried blood */
	blood0: { id: "", w: 16, h: 12 },
	/** sprite: dried blood */
	blood1: { id: "", w: 16, h: 12 },
	/** sprite: oil stain */
	oil0: { id: "", w: 16, h: 12 },
	/** sprite: oil stain */
	oil1: { id: "", w: 16, h: 12 },
	/** sprite: asphalt crack */
	crack0: { id: "", w: 24, h: 8 },
	/** sprite: asphalt crack */
	crack1: { id: "", w: 24, h: 8 },
	/** sprite: manhole cover */
	manhole: { id: "", w: 8, h: 8 },
	/** sprite: storm drain */
	drain: { id: "", w: 8, h: 4 },
	/** sprite: fuel dispenser */
	pump: { id: "", w: 8, h: 6 },
	/** sprite: rooftop air conditioner */
	acUnit: { id: "", w: 13, h: 11 },
	/** sprite: roof vent */
	vent: { id: "", w: 7, h: 7 },
	/** sprite: brick chimney on a house roof */
	chimney: { id: "", w: 8, h: 8 },
};

/** every texture of the world art, for the preload pass */
export const WORLD_ART_NAMES: Array<WorldArtName> = [
	"asphalt",
	"asphaltLot",
	"concrete",
	"plaza",
	"pavers",
	"apron",
	"grass",
	"grassLong",
	"dirt",
	"soil",
	"tactile",
	"paint",
	"kerbN",
	"kerbS",
	"kerbW",
	"kerbE",
	"forest",
	"fenceH",
	"fenceV",
	"floorWood",
	"floorTile",
	"floorShop",
	"wall",
	"roofShingleH",
	"roofShingleV",
	"roofGravel",
	"roofMembrane",
	"eaves",
	"parapet",
	"shadowBox",
	"canopy0",
	"canopyShade0",
	"canopy1",
	"canopyShade1",
	"canopy2",
	"canopyShade2",
	"car0",
	"carTrim0",
	"carDamage0",
	"carWreck0",
	"car1",
	"carTrim1",
	"carDamage1",
	"carWreck1",
	"car2",
	"carTrim2",
	"carDamage2",
	"carWreck2",
	"car3",
	"carTrim3",
	"carDamage3",
	"carWreck3",
	"bin",
	"litter0",
	"litter1",
	"litter2",
	"blood0",
	"blood1",
	"oil0",
	"oil1",
	"crack0",
	"crack1",
	"manhole",
	"drain",
	"pump",
	"acUnit",
	"vent",
	"chimney",
];
