#!/usr/bin/env node
/*
 * The git side of the CI asset pipeline (.github/workflows/ci.yml, job `assets`; its tests: tools/test-assets-ci.mjs).
 *
 *   node tools/assets-ci.mjs drift
 *        After `npm run art:world`: fails when the generated art differs from the commit (someone changed the
 *        generator and did not run it). A PNG whose bytes differ but whose PIXELS are the same (another zlib) is
 *        put back as committed -- the upload dedupes by the committed file's sha1 -- and never counts as drift.
 *   node tools/assets-ci.mjs untouched <path>...
 *        Fails when any of these paths changed since the checkout: run right before the step that holds the Roblox
 *        key, it proves the upload runs the committed tools/cloud.mjs and nothing a dependency rewrote meanwhile.
 *   node tools/assets-ci.mjs commit --branch main --message "<msg>"
 *        Commits ONLY what an upload may change -- design/<kind>/assets.json and src/ files that start with
 *        "// generated by" -- and pushes it to the branch; anything else changed refuses the whole commit. If the
 *        branch moved during the upload: `git pull --rebase`, regenerate the modules from the merged assets.json,
 *        and push once more. Writes `sha=<the commit to build>` and `pushed=true|false` to $GITHUB_OUTPUT.
 *
 * Exit codes: 0 ok, 1 drift / something changed / refused / the push failed twice or the rebase conflicted.
 */
import { execFileSync, spawnSync } from "node:child_process";
import { appendFileSync, existsSync, readFileSync, realpathSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { decodePNG } from "./png-lite.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..");

/** what `npm run art:world` writes (the contact sheet is documentation, and --no-sheet skips it) */
export const ART_OUTPUTS = ["design/world-art", "src/client/view/worldArtAssets.ts", "src/client/ui/itemIconAtlas.ts"];

/** the modules an upload regenerates from its assets.json (after a rebase they are rebuilt from the merged one) */
export const REGENERATORS = [["tools/gen-world-art.mjs", "--assets"]];

/** who the bot commit is from (by environment: it wins over any user.name / user.email of the runner's config) */
const BOT_NAME = "github-actions[bot]";
const BOT_EMAIL = "41898282+github-actions[bot]@users.noreply.github.com";
const BOT_ENV = {
	GIT_AUTHOR_NAME: BOT_NAME,
	GIT_AUTHOR_EMAIL: BOT_EMAIL,
	GIT_COMMITTER_NAME: BOT_NAME,
	GIT_COMMITTER_EMAIL: BOT_EMAIL,
	GIT_EDITOR: "true",
};

function git(root, args, { allowFail = false } = {}) {
	const r = spawnSync("git", args, {
		cwd: root,
		encoding: "utf8",
		maxBuffer: 64 * 1024 * 1024,
		env: { ...process.env, ...BOT_ENV },
	});
	if (r.status !== 0 && !allowFail) {
		throw new Error(`git ${args.join(" ")}: ${(r.stderr || r.stdout || "").trim()}`);
	}
	return r;
}

/** `git status` of `paths` (every untracked file listed): [{ code: "XY", path }] */
export function gitStatus(root, paths = []) {
	const out = git(root, ["status", "--porcelain=v1", "-z", "--untracked-files=all", "--", ...paths]).stdout;
	const parts = out.split("\0").filter(p => p !== "");
	const rows = [];
	for (let i = 0; i < parts.length; i++) {
		const code = parts[i].slice(0, 2);
		rows.push({ code, path: parts[i].slice(3) });
		// a rename is followed by its old path
		if (code[0] === "R" || code[0] === "C") rows.push({ code, path: parts[++i] });
	}
	return rows;
}

/** two PNG files hold the same image (size and every RGBA byte), whatever their compression */
export function samePixels(a, b) {
	try {
		const x = decodePNG(a);
		const y = decodePNG(b);
		return x.w === y.w && x.h === y.h && Buffer.compare(Buffer.from(x.data), Buffer.from(y.data)) === 0;
	} catch {
		return false;
	}
}

/**
 * The generated art against the commit: { restored, drifted }. A modified PNG with the same pixels is checked out
 * again (restored); if any was, `regen` runs (worldArtAssets.ts keeps the atlas id only while its sha1 is the PNG's
 * on disk) and the TS files are looked at once more. Anything else that differs is drift.
 */
export function drift(root, { paths = ART_OUTPUTS, regen } = {}) {
	const restored = [];
	for (const row of gitStatus(root, paths)) {
		if (row.code !== " M" || !row.path.endsWith(".png")) continue;
		const committed = spawnSync("git", ["show", `HEAD:${row.path}`], { cwd: root, maxBuffer: 64 * 1024 * 1024 });
		if (committed.status !== 0) continue;
		if (samePixels(committed.stdout, readFileSync(join(root, row.path)))) {
			git(root, ["checkout", "--", row.path]);
			restored.push(row.path);
		}
	}
	if (restored.length > 0 && regen !== undefined) regen();
	return { restored, drifted: gitStatus(root, paths) };
}

/** the paths among `paths` that changed since the checkout (modified, added, deleted or untracked) */
export function untouched(root, paths) {
	return gitStatus(root, paths);
}

/** a change an upload may make: design/<kind>/assets.json, or a src/ file that says it is generated */
export function isUploadOutput(root, row) {
	if (row.code.includes("D")) return false;
	if (/^design\/[\w-]+\/assets\.json$/.test(row.path)) return true;
	if (!/^src\/[\w/.-]+\.ts$/.test(row.path)) return false;
	const file = join(root, row.path);
	return existsSync(file) && /^\/\/ generated by tools\//.test(readFileSync(file, "utf8").split("\n", 1)[0]);
}

/** a src/ module that `rev` has as generated (read from git: in a conflict the file on disk holds the markers) */
function generatedAt(root, rev, path) {
	if (!/^src\/[\w/.-]+\.ts$/.test(path)) return false;
	const r = git(root, ["show", `${rev}:${path}`], { allowFail: true });
	return r.status === 0 && /^\/\/ generated by tools\//.test(r.stdout.split("\n", 1)[0]);
}

/** what changed in the whole tree, split into what an upload may commit and what it may not */
export function classifyChanges(root) {
	const allowed = [];
	const refused = [];
	for (const row of gitStatus(root)) (isUploadOutput(root, row) ? allowed : refused).push(row.path);
	return { allowed, refused };
}

const head = root => git(root, ["rev-parse", "HEAD"]).stdout.trim();

/**
 * Commits the upload's outputs and pushes them to `branch`; once, when the branch moved meanwhile, pulls with
 * rebase, regenerates (`regen`) and pushes again. Returns { pushed, sha, rebased, error }.
 */
export function commitAndPush(root, { branch, message, remote = "origin", regen, log = console.log }) {
	const first = classifyChanges(root);
	if (first.refused.length > 0) {
		return {
			pushed: false,
			sha: head(root),
			error: `mudou algo que um upload não muda (nada foi commitado): ${first.refused.join(", ")}`,
		};
	}
	if (first.allowed.length === 0) {
		log("nada a commitar: nenhum id novo");
		return { pushed: false, sha: head(root) };
	}
	git(root, ["add", "--", ...first.allowed]);
	git(root, ["commit", "--quiet", "-m", message]);
	log(`commit ${head(root).slice(0, 7)}: ${first.allowed.join(", ")}`);
	let rebased = false;
	for (let attempt = 0; attempt < 2; attempt++) {
		const push = git(root, ["push", remote, `HEAD:refs/heads/${branch}`], { allowFail: true });
		if (push.status === 0) {
			log(`enviado para ${branch}${rebased ? " (depois de um rebase)" : ""}`);
			return { pushed: true, sha: head(root), rebased };
		}
		if (attempt === 1) break;
		log(`o push foi recusado (${branch} andou durante o upload?): git pull --rebase e mais uma tentativa`);
		const pull = git(root, ["pull", "--rebase", "--quiet", remote, branch], { allowFail: true });
		if (pull.status !== 0) {
			// a conflict only in generated modules is no conflict: they are rebuilt from the merged assets.json below.
			// One in assets.json itself (someone uploaded at the same time) is a real one: stop, upload nothing twice
			const conflicted = git(root, ["diff", "--name-only", "--diff-filter=U"], { allowFail: true })
				.stdout.split("\n")
				.filter(p => p !== "");
			const regenerable =
				regen !== undefined && conflicted.length > 0 && conflicted.every(p => generatedAt(root, "HEAD", p));
			let resolved = false;
			if (regenerable) {
				git(root, ["checkout", "--ours", "--", ...conflicted]);
				regen();
				git(root, ["add", "--", ...conflicted]);
				resolved = git(root, ["rebase", "--continue"], { allowFail: true }).status === 0;
			}
			if (!resolved) {
				git(root, ["rebase", "--abort"], { allowFail: true });
				return {
					pushed: false,
					sha: head(root),
					error:
						`o rebase sobre ${remote}/${branch} deu conflito em ${conflicted.join(", ") || "?"} (outro commit ` +
						`mexeu nos mesmos arquivos): ${(pull.stderr || pull.stdout).trim().split("\n")[0]}`,
				};
			}
			log(`conflito só nos módulos gerados (${conflicted.join(", ")}): refeitos a partir do assets.json`);
		}
		rebased = true;
		// the merged assets.json is the truth: the generated modules are rebuilt from it, not merged as text
		regen?.();
		const again = classifyChanges(root);
		if (again.refused.length > 0) {
			return { pushed: false, sha: head(root), error: `depois do rebase mudou: ${again.refused.join(", ")}` };
		}
		if (again.allowed.length > 0) {
			git(root, ["add", "--", ...again.allowed]);
			git(root, ["commit", "--quiet", "--amend", "--no-edit"]);
		}
	}
	return { pushed: false, sha: head(root), error: `o push para ${branch} foi recusado duas vezes` };
}

// ---------------------------------------------------------------- command line

function regenAll(root) {
	for (const [tool, ...args] of REGENERATORS) {
		if (existsSync(join(root, tool))) {
			execFileSync(process.execPath, [join(root, tool), ...args], { cwd: root, stdio: "inherit" });
		}
	}
}

const inActions = process.env.GITHUB_ACTIONS === "true";
const escapeData = s => String(s).replace(/%/g, "%25").replace(/\r/g, "%0D").replace(/\n/g, "%0A");
function error(title, message) {
	if (inActions) console.log(`::error title=${title}::${escapeData(message)}`);
	console.error(`ERRO: ${message}`);
}
function output(pairs) {
	const path = process.env.GITHUB_OUTPUT;
	const text = Object.entries(pairs)
		.map(([k, v]) => `${k}=${v}\n`)
		.join("");
	if (path) appendFileSync(path, text);
	else process.stdout.write(text);
}

function main(argv) {
	const [cmd, ...args] = argv;
	if (cmd === "drift") {
		const { restored, drifted } = drift(ROOT, { regen: () => regenAll(ROOT) });
		for (const p of restored)
			console.log(`  ${p}: só a compressão mudou (mesmos pixels); o arquivo do commit fica`);
		if (drifted.length > 0) {
			error(
				"arte gerada fora de dia",
				"a arte gerada não bate com o commit: rode `npm run art:world` e commite o resultado " +
					`(design/world-art, worldArtAssets.ts, itemIconAtlas.ts). Diferente: ${drifted.map(r => `${r.code.trim()} ${r.path}`).join(", ")}`,
			);
			return 1;
		}
		console.log("arte gerada: igual ao commit");
		return 0;
	}
	if (cmd === "untouched") {
		if (args.length === 0) {
			console.error("uso: node tools/assets-ci.mjs untouched <path>...");
			return 1;
		}
		const changed = untouched(ROOT, args);
		if (changed.length > 0) {
			error(
				"arquivos mudaram antes do upload",
				`mudaram desde o checkout (nada será enviado): ${changed.map(r => `${r.code.trim()} ${r.path}`).join(", ")}`,
			);
			return 1;
		}
		console.log(`intactos desde o checkout: ${args.join(" ")}`);
		return 0;
	}
	if (cmd === "commit") {
		const opt = name => {
			const i = args.indexOf(name);
			return i >= 0 ? args[i + 1] : undefined;
		};
		const branch = opt("--branch");
		const message = opt("--message");
		if (!branch || !message || !/\[skip ci\]/.test(message)) {
			console.error('uso: node tools/assets-ci.mjs commit --branch <branch> --message "<msg> [skip ci]"');
			return 1;
		}
		const r = commitAndPush(ROOT, { branch, message, regen: () => regenAll(ROOT) });
		// a commit that never reached the remote is no `sha` to build (the next job could not even fetch it): then the
		// workflow falls back to the commit it checked out
		output(r.error === undefined ? { sha: r.sha, pushed: String(r.pushed) } : { pushed: "false" });
		if (r.error !== undefined) {
			error("commit dos ids", r.error);
			return 1;
		}
		return 0;
	}
	console.log("uso: node tools/assets-ci.mjs <drift | untouched <path>... | commit --branch <b> --message <m>>");
	return cmd === undefined ? 0 : 1;
}

// run as a command (a test imports the functions above without running anything); by real path, so a symlink or
// a Windows junction to this file still runs it
const self = realpathSync(fileURLToPath(import.meta.url));
if (process.argv[1] !== undefined && existsSync(process.argv[1]) && realpathSync(process.argv[1]) === self) {
	process.exit(main(process.argv.slice(2)));
}
