#!/usr/bin/env node
/*
 * The game's version, from ONE source: package.json -> src/shared/version.ts (generated; never edit it by hand).
 *
 *   npm run stamp                     writes GAME_VERSION from package.json and GAME_BUILD "dev"
 *   npm run stamp -- --build <sha>    the same, with the commit the build is made from (the CI does this before
 *                                     compiling the place it publishes, so the About row names the build tested)
 *
 * Settings › About shows it (client/ui/settings.ts), so a player's report -- or the owner testing ProjectZ-ci.rbxl --
 * says which build it was. The committed file always has GAME_BUILD "dev": the CI checks the committed version is the
 * one package.json says, then stamps its own copy with the commit, and that copy is never committed.
 *
 * Pure Node (>= 18), no dependencies. The output is already in Prettier's style (format:check runs over src/).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "src", "shared", "version.ts");

const pkg = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8"));
const version = String(pkg.version ?? "");
if (!/^\d+\.\d+\.\d+$/.test(version)) {
	console.error(`package.json has no "version" (x.y.z): ${JSON.stringify(pkg.version)}`);
	process.exit(1);
}

const at = process.argv.indexOf("--build");
const raw = at >= 0 ? String(process.argv[at + 1] ?? "") : "dev";
// a commit id (or "dev"): hex, 7 characters is enough to find it, and nothing else reaches the source file
const build = raw === "dev" ? "dev" : raw.toLowerCase().slice(0, 7);
if (build !== "dev" && !/^[0-9a-f]{7}$/.test(build)) {
	console.error(`--build wants a commit id (hex): ${JSON.stringify(raw)}`);
	process.exit(1);
}

const out = `/*
 * GENERATED by \`npm run stamp\` (tools/gen-version.mjs) from package.json -- do not edit. The CI stamps its build
 * with the commit; the committed copy says "dev".
 */

/** the game's version (package.json) */
export const GAME_VERSION = "${version}";
/** the commit this build was made from, or "dev" for a local build */
export const GAME_BUILD = "${build}";
`;
writeFileSync(OUT, out, "utf8");
console.log(`${build === "dev" ? version : `${version} (${build})`} -> ${OUT}`);
