#!/usr/bin/env node
/*
 * Renders a piece of the town to PNG with the REAL drawing code, under Node.
 *
 *   npm run render:map -- --preset all --out docs/art/after          # the preset scenes + the overview
 *   npm run render:map -- --preset street --out /tmp/x --no-art       # force the flat fallback
 *   npm run render:map -- --x 9000 --y 7000 --w 1280 --h 800 --hour 22 --out /tmp/night.png
 *   npm run render:map -- --compare docs/art/before docs/art/after --out docs/art/compare
 *   npm run render:map -- --preset signs --out docs/art/signs/after   # every building type's sign, night, overview
 *   PZ_SRC=/path/to/other/src node tools/render-map.mjs ...           # render another checkout's code
 *
 * Options: --seed (town seed, default DESIGN.TOWN_SEED), --x --y --w --h (world rect, units), --scale (px per
 * unit, default 1), --hour (0-24, or day / dusk / night), --out (a .png, or a folder for presets), --preset
 * (street, downtown, park, school, gas, gas-night, wreck, campus, campus-quad, campus-night, street-night, overview, or
 * all; signs: sign-<type> for every building type, signs-night, signs-overview and downtown), --no-actors, --no-art,
 * --art <dir>
 * (the local PNGs the "after" renders sample, default design/world-art), --src <dir> (same as PZ_SRC), --hand <id>
 * and --gun <id> (EQUIPS ids the survivor holds and wears at night: 13 flashlight, 15 torchlight, 6 night vision --
 * lit by the game's own rule, shared/sim/survivorLight.ts, LUZ-04), --aim <degrees> (where the survivor faces).
 *
 * How it works: the town is generated by shared/game/world.ts `generateTown`, drawn by client/view/worldView.ts
 * through shared/engine/renderer.ts onto a fake Roblox GUI tree (tools/fake-gui.mjs), exactly as the client
 * does every frame; the zombies and the survivor go through client/view/humanoidView.ts and survivorView.ts, and
 * the night through the renderer's LightMap with the clock's own darkness (shared/sim/clock.ts darkAlphaAt).
 * What the renderer left VISIBLE in the tree -- Frames with their UICorner and UIStroke, the ImageLabels it
 * shows (Stretch, Tile, Slice, ImageRectOffset, ImageColor3, Pixelated) and the light map's gradient strips --
 * is then rasterised by the small software rasteriser below, in ZIndex order. Nothing is re-implemented: if the
 * drawing code changes, the picture changes.
 *
 * With world art present (src/client/view/worldArt.ts), the render hands the view "local:<name>" ids, which the
 * rasteriser reads from design/world-art/<name>.png: the "after" images show the real art before any upload.
 * On an older checkout without that module the town is simply drawn flat, which is what the "before" set is.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { decodePNG, encodePNG } from "./png-lite.mjs";
import { countSprites, rasterise } from "./gui-raster.mjs";
import { drawText } from "./pixel-font.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..");

// ---------------------------------------------------------------- arguments

function parseArgs(argv) {
	const out = { flags: new Set(), positional: [] };
	for (let i = 0; i < argv.length; i++) {
		const a = argv[i];
		if (a.startsWith("--")) {
			const key = a.slice(2);
			const next = argv[i + 1];
			if (["no-actors", "no-art", "quiet", "roof-off", "only-uploaded", "stack"].includes(key))
				out.flags.add(key);
			else if (key === "compare") {
				out.compare = [argv[i + 1], argv[i + 2]];
				i += 2;
			} else if (next !== undefined) {
				out[key] = next;
				i++;
			}
		} else out.positional.push(a);
	}
	return out;
}

const args = parseArgs(process.argv.slice(2));

// ---------------------------------------------------------------- compare mode (no src needed)

function fillRect(img, x, y, w, h, rgb) {
	for (let Y = Math.max(0, y); Y < Math.min(img.h, y + h); Y++) {
		for (let X = Math.max(0, x); X < Math.min(img.w, x + w); X++) {
			const i = (Y * img.w + X) * 4;
			img.data[i] = rgb[0];
			img.data[i + 1] = rgb[1];
			img.data[i + 2] = rgb[2];
			img.data[i + 3] = 255;
		}
	}
}

/** box-filter downscale by an integer-free factor (area average), keeps pixel art readable at 0.5..1 */
function resample(src, w, h) {
	const out = { w, h, data: Buffer.alloc(w * h * 4) };
	const fx = src.w / w;
	const fy = src.h / h;
	for (let y = 0; y < h; y++) {
		const y0 = y * fy;
		const y1 = y0 + fy;
		for (let x = 0; x < w; x++) {
			const x0 = x * fx;
			const x1 = x0 + fx;
			let r = 0;
			let g = 0;
			let b = 0;
			let n = 0;
			for (let sy = Math.floor(y0); sy < Math.ceil(y1); sy++) {
				const wy = Math.min(y1, sy + 1) - Math.max(y0, sy);
				for (let sx = Math.floor(x0); sx < Math.ceil(x1); sx++) {
					const wx = Math.min(x1, sx + 1) - Math.max(x0, sx);
					const k = wx * wy;
					const i = (Math.min(src.h - 1, sy) * src.w + Math.min(src.w - 1, sx)) * 4;
					r += src.data[i] * k;
					g += src.data[i + 1] * k;
					b += src.data[i + 2] * k;
					n += k;
				}
			}
			const o = (y * w + x) * 4;
			out.data[o] = Math.round(r / n);
			out.data[o + 1] = Math.round(g / n);
			out.data[o + 2] = Math.round(b / n);
			out.data[o + 3] = 255;
		}
	}
	return out;
}

const MAX_W = 1600;

function compare(beforeDir, afterDir, outDir) {
	mkdirSync(outDir, { recursive: true });
	const meta = existsSync(join(afterDir, "scenes.json"))
		? JSON.parse(readFileSync(join(afterDir, "scenes.json"), "utf8"))
		: {};
	const names = Object.keys(meta).length > 0 ? Object.keys(meta) : [];
	const made = [];
	for (const name of names) {
		const bPath = join(beforeDir, `${name}.png`);
		const aPath = join(afterDir, `${name}.png`);
		if (!existsSync(bPath) || !existsSync(aPath)) continue;
		let b = decodePNG(readFileSync(bPath));
		let a = decodePNG(readFileSync(aPath));
		const gap = 8;
		const head = 40;
		// --stack: the before above the after, each at full size (a game-zoom shot is read texel for texel);
		// otherwise side by side, each half fitting (MAX_W - 3 gaps) / 2, never upscaled
		const stack = args.flags.has("stack");
		const half = stack ? a.w : Math.min(a.w, Math.floor((MAX_W - gap * 3) / 2));
		const k = half / a.w;
		const hh = Math.round(a.h * k);
		if (k < 1) {
			b = resample(b, half, hh);
			a = resample(a, half, hh);
		}
		const W = stack ? half + gap * 2 : half * 2 + gap * 3;
		const H = stack ? (hh + head) * 2 + gap : hh + head + gap;
		const img = { w: W, h: H, data: Buffer.alloc(W * H * 4) };
		fillRect(img, 0, 0, W, H, [24, 24, 28]);
		const blit = (src, ox, oy) => {
			for (let y = 0; y < src.h; y++) {
				src.data.copy(img.data, ((oy + y) * W + ox) * 4, y * src.w * 4, (y + 1) * src.w * 4);
			}
		};
		const title = meta[name]?.title ?? name;
		const ax = stack ? gap : gap * 2 + half;
		const ay = stack ? head * 2 + hh : head;
		blit(b, gap, head);
		blit(a, ax, ay);
		drawText(img, `BEFORE - ${title}`, gap + 4, 12, 2, [235, 235, 235]);
		drawText(img, `AFTER - ${title}`, ax + 4, ay - 28, 2, [235, 235, 235]);
		const out = join(outDir, `${name}.png`);
		writeFileSync(out, encodePNG(img, true));
		made.push(out);
		console.log(`  ${basename(out)}  ${W}x${H}`);
	}
	if (made.length === 0) {
		console.error("compare: no scene has both a before and an after image (run the presets first)");
		process.exit(1);
	}
	return made;
}

if (args.compare !== undefined) {
	const out = resolve(args.out ?? join(ROOT, "docs", "art", "compare"));
	console.log(`compare ${args.compare[0]} | ${args.compare[1]} -> ${out}`);
	compare(resolve(args.compare[0]), resolve(args.compare[1]), out);
	process.exit(0);
}

// ---------------------------------------------------------------- load the real code

if (args.src !== undefined) process.env.PZ_SRC = resolve(args.src);
const { installShims } = await import("./luau-shim.mjs");
const { SRC, require } = installShims({ seed: 1 });
const { installFakeGui } = await import("./fake-gui.mjs");
const gui = installFakeGui();

const { COLORS, Z } = require(join(SRC, "shared/engine/colors.ts"));
const { Camera } = require(join(SRC, "shared/engine/camera.ts"));
const { Renderer, LightMap } = require(join(SRC, "shared/engine/renderer.ts"));
const { DESIGN } = require(join(SRC, "shared/engine/constants.ts"));
const { generateTown, buildingAt, hash01, pointInSolid, querySolids } = require(join(SRC, "shared/game/world.ts"));
const { darkAlphaAt } = require(join(SRC, "shared/sim/clock.ts"));
const { WorldView, SHELTER_SEE_THROUGH } = require(join(SRC, "client/view/worldView.ts"));
const HV = require(join(SRC, "client/view/humanoidView.ts"));
const SV = require(join(SRC, "client/view/survivorView.ts"));
const ART_MODULE = join(SRC, "client/view/worldArt.ts");
const worldArt = existsSync(ART_MODULE) ? require(ART_MODULE) : undefined;
// the signs' module: where a gas station's price pylon is drawn (the rect its fade tests), on a checkout that has it
const SIGNS_MODULE = join(SRC, "client/view/buildingSigns.ts");
const BS = existsSync(SIGNS_MODULE) ? require(SIGNS_MODULE) : undefined;
// the survivor's own light at night (DESIGN_RULES LUZ-04): the rule the game's light map uses, when the checkout has it
const LIGHT_MODULE = join(SRC, "shared/sim/survivorLight.ts");
const survivorLight = existsSync(LIGHT_MODULE) ? require(LIGHT_MODULE) : undefined;
const ART_DIR = resolve(args.art ?? join(ROOT, "design", "world-art"));

/** the id the render hands the view for texture `name`: read back from ART_DIR by the rasteriser */
const LOCAL = "local:";

function useLocalArt(on) {
	if (worldArt === undefined) return false;
	if (!on) {
		worldArt.overrideWorldArt({});
		return false;
	}
	const manifestPath = join(ART_DIR, "manifest.json");
	if (!existsSync(manifestPath)) return false;
	const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
	// --only-uploaded: what the owner's place shows today -- the textures with an asset id (assets.json, or the
	// file --uploaded names) drawn from their local PNGs, every newer one still flat until the next upload-art
	let uploaded;
	if (args.flags.has("only-uploaded") || args.uploaded !== undefined) {
		const file = resolve(args.uploaded ?? join(ART_DIR, "assets.json"));
		uploaded = existsSync(file) ? (JSON.parse(readFileSync(file, "utf8")).ids ?? {}) : {};
	}
	const ids = {};
	for (const t of manifest.textures) {
		if (uploaded !== undefined && !uploaded[t.name]) continue;
		ids[t.name] = LOCAL + t.name;
	}
	worldArt.overrideWorldArt(ids);
	return true;
}

// ---------------------------------------------------------------- scenes

const SEED = args.seed !== undefined ? Number(args.seed) : DESIGN.TOWN_SEED;
const CANOPY_SEE_THROUGH = 0.35;

function hourOf(v, fallback) {
	if (v === undefined) return fallback;
	if (v === "day") return 10;
	if (v === "dusk") return 19;
	if (v === "night") return 22;
	return Number(v);
}

function lotAt(world, x, y) {
	return world.lots.find(l => x >= l.x && x < l.x + l.w && y >= l.y && y < l.y + l.h);
}

function inRect(r, x, y) {
	return x >= r.x && x < r.x + r.w && y >= r.y && y < r.y + r.h;
}

/** what a point of the town is made of, for placing the actors of a scene */
function surfaceAt(world, x, y) {
	if (buildingAt(world, x, y) !== undefined) return "building";
	if (pointInSolid(world, x, y, 26) !== undefined) return "solid";
	for (const road of world.roads) {
		if (!inRect(road, x, y)) continue;
		for (const m of road.medians) if (inRect(m, x, y)) return "median";
		return "road";
	}
	const lot = lotAt(world, x, y);
	if (lot === undefined) return "border";
	for (const g of lot.ground) if (inRect(g, x, y)) return g.kind;
	for (const p of lot.paths) if (inRect(p, x, y)) return "dirt";
	if (inRect(lot.yard, x, y)) return lot.zone === "commercial" ? "plaza" : "grass";
	return "sidewalk";
}

/** first point of a spiral around (cx, cy), inside `rect`'s inner part, on one of `kinds`, away from `taken` */
function place(world, rect, cx, cy, kinds, taken) {
	const inset = 90;
	for (let i = 0; i < 4000; i++) {
		const a = i * 2.39996;
		const d = 14 * Math.sqrt(i) * 3;
		const x = Math.round(cx + Math.cos(a) * d);
		const y = Math.round(cy + Math.sin(a) * d);
		if (x < rect.x + inset || y < rect.y + inset || x > rect.x + rect.w - inset || y > rect.y + rect.h - inset)
			continue;
		if (!kinds.includes(surfaceAt(world, x, y))) continue;
		if (taken.some(p => Math.hypot(p.x - x, p.y - y) < 150)) continue;
		taken.push({ x, y });
		return { x, y };
	}
	return undefined;
}

function isParked(s) {
	if (s.heading === undefined) return true;
	const q = s.heading / (Math.PI / 2);
	return Math.abs(q - Math.round(q)) < 0.01;
}

function solidsIn(world, r) {
	return querySolids(world, r.x, r.y, r.x + r.w, r.y + r.h, []);
}

function sceneAround(cx, cy, w, h) {
	return { x: Math.round(cx - w / 2), y: Math.round(cy - h / 2), w, h };
}

const W = 1280;
const H = 800;

/** how much of the rect `s` covers inside `r` (0..1 of s) */
function visibleShare(s, r) {
	const w = Math.max(0, Math.min(s.x + s.w, r.x + r.w) - Math.max(s.x, r.x));
	const h = Math.max(0, Math.min(s.y + s.h, r.y + r.h) - Math.max(s.y, r.y));
	return (w * h) / Math.max(1, s.w * s.h);
}

function junctionsIn(world, r) {
	return world.junctions.filter(j => j.x < r.x + r.w && j.x + j.w > r.x && j.y < r.y + r.h && j.y + j.h > r.y).length;
}

/** a residential street mid-block: parked cars, street trees, houses with their front yards on one side */
function findStreet(world) {
	let best;
	let bestScore = -Infinity;
	for (const road of world.roads) {
		if (road.avenue || road.vertical) continue;
		const mid = road.y + road.h / 2;
		for (let t = road.x + 900; t < road.x + road.w - 900; t += 128) {
			const up = lotAt(world, t, road.y - 300);
			const down = lotAt(world, t, road.y + road.h + 300);
			if (up === undefined || down === undefined) continue;
			if (
				up.zone !== "residential" ||
				down.zone !== "residential" ||
				up.kind !== "block" ||
				down.kind !== "block"
			) {
				continue;
			}
			for (const dy of [-230, 230]) {
				const r = sceneAround(t, mid + dy, W, H);
				const list = solidsIn(world, r);
				const cars = list.filter(s => s.tags === "car" && isParked(s)).length;
				const wrecks = list.filter(s => s.tags === "car" && !isParked(s)).length;
				const trees = list.filter(s => s.kind === "tree").length;
				let houses = 0;
				for (const s of list) {
					if (s.kind === "building" && (s.buildingType === 1 || s.buildingType === 2))
						houses += visibleShare(s, r);
				}
				const bins = list.filter(s => s.tags === "trash").length;
				const score =
					3 * Math.min(cars, 4) +
					5 * Math.min(wrecks, 1) +
					Math.min(trees, 7) +
					6 * Math.min(houses, 2) +
					2 * Math.min(bins, 1) -
					12 * junctionsIn(world, r);
				if (score > bestScore) {
					bestScore = score;
					best = r;
				}
			}
		}
	}
	return best;
}

/** a downtown street crossing with its crosswalks and the shops on its corners */
function findDowntown(world) {
	let best;
	let bestScore = -Infinity;
	for (const j of world.junctions) {
		const around = [
			lotAt(world, j.x - 200, j.y - 200),
			lotAt(world, j.x + j.w + 200, j.y - 200),
			lotAt(world, j.x - 200, j.y + j.h + 200),
			lotAt(world, j.x + j.w + 200, j.y + j.h + 200),
		];
		const shops = around.filter(l => l !== undefined && l.zone === "commercial").length;
		if (shops < 3) continue;
		for (const [ox, oy] of [
			[-300, -170],
			[300, -170],
			[-300, 170],
			[300, 170],
		]) {
			const r = sceneAround(j.x + j.w / 2 + ox, j.y + j.h / 2 + oy, W, H);
			const list = solidsIn(world, r);
			let shopArea = 0;
			for (const s of list) if (s.kind === "building" && s.buildingType > 5) shopArea += visibleShare(s, r);
			const cars = list.filter(s => s.tags === "car").length;
			const bins = list.filter(s => s.tags === "trash").length;
			const avenue = world.roads.some(rd => rd.avenue && inRect(rd, j.x + 1, j.y + 1));
			const score = shopArea * 6 + Math.min(cars, 4) + Math.min(bins, 2) - (avenue ? 4 : 0);
			if (score > bestScore) {
				bestScore = score;
				best = r;
			}
		}
	}
	return best;
}

/** a 3000 x 2000 piece of town with the most variety: shops, houses, a park, a gas station, a school */
function findOverview(world) {
	let best;
	let bestScore = -Infinity;
	for (let cy = 2000; cy < world.height - 2000; cy += 500) {
		for (let cx = 2200; cx < world.width - 2200; cx += 500) {
			const r = sceneAround(cx, cy, 3000, 2000);
			const list = solidsIn(world, r);
			// (a plain object: the Luau shims turn Set.size into a method)
			const types = {};
			let houses = 0;
			for (const s of list) {
				if (s.kind !== "building" || visibleShare(s, r) < 0.6) continue;
				types[s.buildingType === 2 ? 1 : s.buildingType] = true;
				if (s.buildingType <= 2) houses++;
			}
			const park = world.lots.some(l => l.kind === "park" && visibleShare(l, r) > 0.35);
			const wrecks = list.filter(s => s.tags === "car" && !isParked(s)).length;
			const score =
				Object.keys(types).length * 4 + Math.min(houses, 6) + (park ? 10 : 0) + Math.min(wrecks, 2) * 2;
			if (score > bestScore) {
				bestScore = score;
				best = r;
			}
		}
	}
	return best;
}

function findPark(world) {
	for (const lot of world.lots) {
		if (lot.kind !== "park" || lot.paths.length < 2) continue;
		const v = lot.paths[0];
		const hz = lot.paths[1];
		return sceneAround(v.x + v.w / 2 + 160, hz.y + hz.h / 2 - 60, W, H);
	}
	return undefined;
}

function findBuilding(world, type) {
	for (const s of world.solids) {
		if (s.kind === "building" && s.buildingType === type) return s;
	}
	return undefined;
}

function findSchool(world) {
	const b = findBuilding(world, 3);
	if (b === undefined) return undefined;
	const lot = lotAt(world, b.x + b.w / 2, b.y + b.h / 2);
	const yard = lot?.ground.find(g => g.kind === "playground");
	const cx = yard !== undefined ? (b.x + b.w / 2 + yard.x + yard.w / 2) / 2 : b.x + b.w / 2;
	const cy = yard !== undefined ? (b.y + b.h / 2 + yard.y + yard.h / 2) / 2 : b.y + b.h / 2;
	return sceneAround(cx, cy, W, H);
}

/**
 * The college campus (DESIGN_RULES EDI-17): its whole block (the four buildings round the quad and the four streets
 * round the block) and a closer frame on the quad, centred on its fountain or statue. Undefined in a town without one.
 */
function findCampus(world) {
	const hall = findBuilding(world, 12);
	if (hall === undefined) return undefined;
	const lot = lotAt(world, hall.x + hall.w / 2, hall.y + hall.h / 2);
	if (lot === undefined) return undefined;
	const centre = world.solids.find(
		s => s.kind === "prop" && (s.tags === "fountain" || s.tags === "statue") && inRect(lot, s.x, s.y),
	);
	const qx = centre !== undefined ? centre.x + centre.w / 2 : lot.x + lot.w / 2;
	const qy = centre !== undefined ? centre.y + centre.h / 2 : lot.y + lot.h / 2;
	return {
		block: sceneAround(lot.x + lot.w / 2, lot.y + lot.h / 2, 2080, 2080),
		quad: sceneAround(qx, qy, W, H),
	};
}

function findGas(world) {
	const b = findBuilding(world, 5);
	if (b === undefined) return undefined;
	const lot = lotAt(world, b.x + b.w / 2, b.y + b.h / 2);
	const apron = lot?.ground.find(
		g => g.kind === "apron" && Math.hypot(g.x + g.w / 2 - b.x - b.w / 2, g.y + g.h / 2 - b.y - b.h / 2) < 900,
	);
	const cx = apron !== undefined ? (b.x + b.w / 2) * 0.35 + (apron.x + apron.w / 2) * 0.65 : b.x + b.w / 2;
	const cy = apron !== undefined ? (b.y + b.h / 2) * 0.35 + (apron.y + apron.h / 2) * 0.65 : b.y + b.h / 2;
	return sceneAround(cx, cy, W, H);
}

/**
 * A car abandoned askew in a lane and broken into, with blood by its door: the same hashes client/view/worldView.ts
 * `drawCarArt` reads (23: its state, 25: the blood), so the "after" picture shows what the game will show.
 */
function findWreck(world) {
	for (const s of world.solids) {
		if (s.tags !== "car" || isParked(s)) continue;
		const roll = hash01(s.x, s.y, 23);
		if (roll < 0.3 || roll >= 0.75 || hash01(s.x, s.y, 25) >= 0.5) continue;
		return sceneAround(s.x + s.w / 2 + 160, s.y + s.h / 2 - 60, W, H);
	}
	return undefined;
}

/** outward unit normal of a building's entrance wall */
function doorNormal(side) {
	if (side === "top") return { x: 0, y: -1 };
	if (side === "left") return { x: -1, y: 0 };
	if (side === "right") return { x: 1, y: 0 };
	return { x: 0, y: 1 };
}

const SIGN_TYPES = [
	[3, "school", "School"],
	[4, "hospital", "Hospital"],
	[5, "gas", "Gas station"],
	[6, "pharmacy", "Pharmacy"],
	[7, "market", "Market"],
	[8, "grocery", "Small market"],
	[9, "guns", "Gun shop"],
	[10, "clothes", "Clothing store"],
	[11, "diner", "Restaurant"],
	[12, "college", "Campus hall"],
	[13, "library", "Campus library"],
	[14, "lab", "Science lab"],
	[15, "dorm", "Dorm"],
];

/** the first building of `type`, preferring one that faces south (its sign reads the way the camera looks) */
function landmarkOf(world, type) {
	const all = world.solids.filter(s => s.kind === "building" && s.buildingType === type);
	return all.find(s => s.doorSide === "bottom") ?? all[0];
}

/**
 * The 3000 x 2000 piece of town (drawn at half scale) whose frame holds the entrances of the most kinds of
 * building that are not houses: the overview of the signs.
 */
function findSignsOverview(world) {
	const shops = world.solids.filter(s => s.kind === "building" && s.buildingType >= 3);
	let best;
	let bestScore = -Infinity;
	for (let cy = 1400; cy < world.height - 1400; cy += 250) {
		for (let cx = 1900; cx < world.width - 1900; cx += 250) {
			const r = sceneAround(cx, cy, 3000, 2000);
			const inner = { x: r.x + 150, y: r.y + 150, w: r.w - 300, h: r.h - 300 };
			const types = {};
			let doors = 0;
			for (const s of shops) {
				if (!inRect(inner, s.doorX ?? s.x + s.w / 2, s.doorY ?? s.y + s.h)) continue;
				types[s.buildingType === 8 ? 7.5 : s.buildingType] = true;
				doors++;
			}
			const score = Object.keys(types).length * 10 + Math.min(doors, 12);
			if (score > bestScore) {
				bestScore = score;
				best = r;
			}
		}
	}
	return best;
}

/**
 * The storefront signs (DESIGN_RULES ART-07): every building type that is not a house seen from its street -- the
 * frame holds the entrance, the sidewalk in front of it and the middle of the roof, where the old emblem was --, a
 * shop front at 22:00 with the survivor at its door, the overview with the most kinds of shop, and the downtown
 * crossing of the "all" set. Framed from the world alone, so an older checkout (--src) renders the same scenes
 * for the "before".
 */
function signScenes(world) {
	const out = [];
	let night;
	for (const [type, name, title] of SIGN_TYPES) {
		const b = landmarkOf(world, type);
		if (b === undefined) continue;
		const n = doorNormal(b.doorSide);
		const ox = (b.doorX ?? b.x + b.w / 2) + n.x * 160;
		const oy = (b.doorY ?? b.y + b.h) + n.y * 160;
		const cx = (ox + b.x + b.w / 2) / 2;
		const cy = (oy + b.y + b.h / 2) / 2;
		out.push({
			name: `sign-${name}`,
			title: `${title} from its street`,
			rect: sceneAround(cx, cy, 1152, 720),
			hour: 10,
		});
		if (type === 6) night = { b, n };
	}
	if (night !== undefined) {
		const { b, n } = night;
		const cx = (b.doorX ?? b.x + b.w / 2) + n.x * 90;
		const cy = (b.doorY ?? b.y + b.h) + n.y * 90;
		out.push({ name: "signs-night", title: "Pharmacy, 22:00", rect: sceneAround(cx, cy, 1152, 720), hour: 22 });
	}
	const overview = findSignsOverview(world);
	if (overview !== undefined) {
		out.push({
			name: "signs-overview",
			title: "Overview 3000 x 2000, half scale",
			rect: overview,
			hour: 10,
			scale: 0.5,
			noActors: true,
		});
	}
	for (const s of scenes(world)) if (s.name === "downtown") out.push(s);
	return out;
}

function scenes(world) {
	const street = findStreet(world);
	const downtown = findDowntown(world);
	const out = [];
	if (street) out.push({ name: "street", title: "Residential street", rect: street, hour: 10 });
	if (downtown) out.push({ name: "downtown", title: "Commercial crossing", rect: downtown, hour: 10 });
	const park = findPark(world);
	if (park) out.push({ name: "park", title: "Park", rect: park, hour: 10 });
	const school = findSchool(world);
	if (school) out.push({ name: "school", title: "School yard", rect: school, hour: 10 });
	const gas = findGas(world);
	if (gas) out.push({ name: "gas", title: "Gas station", rect: gas, hour: 10 });
	// the forecourt at night: the canopy and the price sign dark (no power, ART-07), read in the survivor's light
	if (gas) out.push({ name: "gas-night", title: "Gas station, 22:00", rect: gas, hour: 22 });
	const wreck = findWreck(world);
	if (wreck) out.push({ name: "wreck", title: "Abandoned car", rect: wreck, hour: 10 });
	const campus = findCampus(world);
	if (campus) {
		out.push({
			name: "campus",
			title: "College campus, its block",
			rect: campus.block,
			hour: 10,
			scale: 0.5,
			noActors: true,
		});
		out.push({ name: "campus-quad", title: "College campus, the quad", rect: campus.quad, hour: 10 });
		out.push({ name: "campus-night", title: "College campus, the quad at 22:00", rect: campus.quad, hour: 22 });
	}
	if (street) out.push({ name: "street-night", title: "Residential street, 22:00", rect: street, hour: 22 });
	const overview = findOverview(world);
	if (overview) {
		out.push({
			name: "overview",
			title: "Overview 3000 x 2000",
			rect: overview,
			hour: 10,
			scale: 0.5,
			noActors: true,
		});
	}
	return out;
}

// ---------------------------------------------------------------- the interiors set (docs/art/interiors)

/**
 * One building of each kind, seen from inside (its roof off, the survivor at a loot spot, a walker climbing in
 * through a window, one at the door, one in the next room), plus exterior shots of the new footprints and an
 * overview. `match` (a list of buildings of ANOTHER checkout, --match) restricts the picks to buildings standing
 * in both towns, so the "before" of the same scene shows the same building.
 */
const INTERIOR_KINDS = [
	{ name: "house-small", title: "House, small", pick: b => b.buildingType === 1 && b.w * b.h < 300000 },
	{ name: "house", title: "House, medium", pick: b => b.buildingType === 1 && b.w * b.h >= 300000 },
	{ name: "house-large", title: "House, large", pick: b => b.buildingType === 2 && b.w * b.h < 1000000 },
	{ name: "pharmacy", title: "Pharmacy", pick: b => b.buildingType === 6 },
	{ name: "market-small", title: "Corner market", pick: b => b.buildingType === 8 },
	{ name: "market", title: "Supermarket", pick: b => b.buildingType === 7 },
	{ name: "gunshop", title: "Gun shop", pick: b => b.buildingType === 9 },
	{ name: "cloth", title: "Clothing store", pick: b => b.buildingType === 10 },
	{ name: "restaurant", title: "Restaurant", pick: b => b.buildingType === 11 },
	{ name: "gas", title: "Gas station shop", pick: b => b.buildingType === 5 },
	{ name: "school", title: "School", pick: b => b.buildingType === 3 },
	{ name: "hospital", title: "Hospital", pick: b => b.buildingType === 4 },
	{ name: "college", title: "Campus hall", pick: b => b.buildingType === 12 },
	{ name: "library", title: "Campus library", pick: b => b.buildingType === 13 },
	{ name: "lab", title: "Science lab", pick: b => b.buildingType === 14 },
	{ name: "dorm", title: "Dorm", pick: b => b.buildingType === 15 },
];

function sameBox(a, b) {
	return Math.abs(a.x - b.x) < 1 && Math.abs(a.y - b.y) < 1 && a.w === b.w && a.h === b.h;
}

/** a free point for a body (radius 18) near (x, y), or undefined */
function freeNear(world, x, y) {
	for (let i = 0; i < 60; i++) {
		const a = i * 2.39996;
		const d = 6 * Math.sqrt(i) * 3;
		const px = Math.round(x + Math.cos(a) * d);
		const py = Math.round(y + Math.sin(a) * d);
		if (pointInSolid(world, px, py, 20) === undefined) return { x: px, y: py };
	}
	return undefined;
}

/**
 * The `rw` x `rh` world rect, centred on a building `pick` likes, that holds the most such buildings whole (ties:
 * the lowest id) -- in the "after" town; the "before" replays the same rects (--scenes)
 */
function findCluster(buildings, pick, rw, rh, match) {
	let best;
	let bestN = -1;
	const cands = buildings.filter(b => pick(b) && (match === undefined || match.some(m => sameBox(m, b))));
	for (const c of cands) {
		const r = sceneAround(c.x + c.w / 2, c.y + c.h / 2, rw, rh);
		let n = 0;
		for (const b of cands) if (b.x >= r.x && b.y >= r.y && b.x + b.w <= r.x + r.w && b.y + b.h <= r.y + r.h) n++;
		if (n > bestN) {
			bestN = n;
			best = r;
		}
	}
	return best;
}

function interiorScenes(world, match) {
	const out = [];
	const buildings = world.solids.filter(s => s.kind === "building");
	for (const kind of INTERIOR_KINDS) {
		let cands = buildings.filter(kind.pick);
		if (match !== undefined) cands = cands.filter(b => match.some(m => m.type === b.buildingType && sameBox(m, b)));
		if (cands.length === 0) continue;
		// the richest plan of its kind: most rooms, then most furniture
		const richness = b => (b.rooms?.length ?? 0) * 100 + (b.openings?.length ?? 0);
		cands.sort((a, b) => richness(b) - richness(a) || a.id - b.id);
		const b = cands[0];
		const scale = Math.max(0.45, Math.min(1.25, Math.min(W / (b.w + 360), H / (b.h + 280))));
		const rw = Math.round(W / scale);
		const rh = Math.round(H / scale);
		const rect = sceneAround(b.x + b.w / 2, b.y + b.h / 2, rw, rh);
		// the survivor stands where one searches (a loot spot), facing the room
		const spot = b.lootSpots?.[0] ?? { x: b.x + b.w / 2, y: b.y + b.h / 2 };
		const survivor = freeNear(world, spot.x, spot.y) ?? spot;
		const zombies = [];
		const win = (b.openings ?? []).find(o => o.kind === "window");
		if (win !== undefined) {
			// in the window's gap: climbing through (EDI-10)
			zombies.push({
				x: win.x + win.w / 2,
				y: win.y + win.h / 2,
				type: 1,
				angle: Math.atan2(survivor.y - win.y, survivor.x - win.x),
			});
		}
		const door = (b.openings ?? []).find(o => o.kind === "door" && !o.main) ?? (b.openings ?? []).find(o => o.main);
		if (door !== undefined) {
			const n = { top: [0, -1], bottom: [0, 1], left: [-1, 0], right: [1, 0] }[door.side];
			const p = freeNear(world, door.x + door.w / 2 + n[0] * 90, door.y + door.h / 2 + n[1] * 90);
			if (p !== undefined) zombies.push({ ...p, type: 4, angle: Math.atan2(-n[1], -n[0]) });
		}
		const other = (b.rooms ?? []).find(
			q => Math.hypot(q.x + q.w / 2 - survivor.x, q.y + q.h / 2 - survivor.y) > 260,
		);
		if (other !== undefined) {
			const p = freeNear(world, other.x + other.w / 2, other.y + other.h / 2);
			if (p !== undefined) zombies.push({ ...p, type: 1, angle: Math.atan2(survivor.y - p.y, survivor.x - p.x) });
		}
		out.push({
			name: kind.name,
			title: `${kind.title}, inside`,
			rect,
			hour: 10,
			scale,
			inside: { x: b.x + b.w / 2, y: b.y + b.h / 2, box: { x: b.x, y: b.y, w: b.w, h: b.h } },
			actors: { survivor: { ...survivor, angle: 0 }, zombies },
		});
	}
	// from outside, roofs on: the new footprints, and the marks of the doors and windows on the roofs' edges
	for (const [name, kindName, title] of [
		["ext-house", "house", "House, medium, from outside"],
		["ext-market", "market", "Supermarket from outside"],
	]) {
		const inner = out.find(s => s.name === kindName);
		if (inner === undefined) continue;
		out.push({ name, title, rect: inner.rect, hour: 10, scale: inner.scale, noActors: true });
	}
	const clusters = [
		["ext-houses", "Houses from above", b => b.buildingType === 1 || b.buildingType === 2, 2560, 1600, 0.5],
		["ext-shops", "Shops from above", b => b.buildingType >= 5, 2560, 1600, 0.5],
		["overview", "Overview 5120 x 3200", () => true, 5120, 3200, 0.25],
	];
	for (const [name, title, pick, rw, rh, scale] of clusters) {
		const rect = findCluster(buildings, pick, rw, rh, match);
		if (rect !== undefined) out.push({ name, title, rect, hour: 10, scale, noActors: true });
	}
	for (const [name, type, title] of [
		["ext-school", 3, "School from outside"],
		["ext-hospital", 4, "Hospital from outside"],
	]) {
		const b = buildings.find(
			s => s.buildingType === type && (match === undefined || match.some(m => sameBox(m, s))),
		);
		if (b === undefined) continue;
		const scale = Math.max(0.45, Math.min(1, Math.min(W / (b.w + 700), H / (b.h + 500))));
		out.push({
			name,
			title,
			rect: sceneAround(b.x + b.w / 2, b.y + b.h / 2, Math.round(W / scale), Math.round(H / scale)),
			hour: 10,
			scale,
			noActors: true,
		});
	}
	return out;
}

// ---------------------------------------------------------------- the rooms set (docs/art/rooms): at game zoom

/**
 * Every kind of room the plans make (shared/game/interiors.ts, EDI-08), seen from inside at the game's own zoom (1:
 * one texel of the art is 4 x 4 px), by day and at 22:00 in the survivor's light: `--preset rooms`. One house that
 * has all four of a home's rooms gives the four house shots; every other shot is the richest building of its type
 * that has the room, centred on it. The survivor stands in the room (at its loot spot when it has one), a walker
 * climbs in through the building's window nearest the room and another stands a little way off, so the legibility
 * of the bodies on the new floors is in every picture (LEG-03).
 */
const ROOM_SHOTS = [
	{ name: "house-living", title: "House: living room", types: [1, 2], room: "living" },
	{ name: "house-kitchen", title: "House: kitchen", types: [1, 2], room: "kitchen" },
	{ name: "house-bedroom", title: "House: bedroom", types: [1, 2], room: "bedroom" },
	{ name: "house-bath", title: "House: bathroom", types: [1, 2], room: "bath" },
	{ name: "house-dining", title: "House: dining room", types: [1, 2], room: "dining" },
	{ name: "market", title: "Supermarket: sales floor", types: [7], room: "sales" },
	{ name: "market-back", title: "Supermarket: cold room and stock", types: [7], room: "cold" },
	{ name: "corner-market", title: "Corner market", types: [8], room: "sales" },
	{ name: "pharmacy", title: "Pharmacy", types: [6], room: "sales" },
	{ name: "gunshop", title: "Gun shop and its vault", types: [9], room: "secure" },
	{ name: "cloth", title: "Clothing store", types: [10], room: "sales" },
	{ name: "restaurant", title: "Restaurant: dining room", types: [11], room: "diner" },
	{ name: "restaurant-kitchen", title: "Restaurant: kitchen", types: [11], room: "galley" },
	{ name: "gas", title: "Gas station shop", types: [5], room: "sales" },
	{ name: "gas-office", title: "Gas station: office", types: [5], room: "office" },
	{ name: "school", title: "School: classroom", types: [3], room: "classroom" },
	{ name: "school-corridor", title: "School: corridor and lockers", types: [3], room: "corridor" },
	{ name: "hospital-ward", title: "Hospital: ward", types: [4], room: "ward" },
	{ name: "hospital-treatment", title: "Hospital: treatment room", types: [4], room: "treatment" },
	{ name: "hospital-lobby", title: "Hospital: reception", types: [4], room: "lobby" },
	// the college campus (EDI-17)
	{ name: "college-lecture", title: "College: lecture room", types: [12], room: "lecture" },
	{ name: "college-corridor", title: "College: foyer and corridor", types: [12], room: "corridor" },
	{ name: "library-reading", title: "Library: reading room", types: [13], room: "reading" },
	{ name: "library-stacks", title: "Library: stacks", types: [13], room: "stacks" },
	{ name: "lab", title: "Science lab", types: [14], room: "lab" },
	{ name: "lab-store", title: "Science lab: chemicals store", types: [14], room: "chemstore" },
	{ name: "dorm-room", title: "Dorm: bunk room", types: [15], room: "dormroom" },
	{ name: "dorm-common", title: "Dorm: common room", types: [15], room: "common" },
];

/** the house the four house shots share: the most of a home's rooms, then the most rooms, then the lowest id */
function showHouse(buildings) {
	const home = ["living", "kitchen", "bedroom", "bath", "dining"];
	const score = b => {
		const kinds = new Set((b.rooms ?? []).map(q => q.kind));
		return home.filter(k => kinds.has(k)).length * 1000 + (b.rooms?.length ?? 0) * 10 - b.w * b.h * 1e-7;
	};
	const houses = buildings.filter(b => b.buildingType === 1 || b.buildingType === 2);
	houses.sort((a, b) => score(b) - score(a) || a.id - b.id);
	return houses[0];
}

/** the biggest rect of room kind `kind` in building `b` */
function roomOf(b, kind) {
	let best;
	for (const q of b.rooms ?? []) {
		if (q.kind !== kind) continue;
		if (best === undefined || q.w * q.h > best.w * best.h) best = q;
	}
	return best;
}

function roomScenes(world) {
	const out = [];
	const buildings = world.solids.filter(s => s.kind === "building");
	const house = showHouse(buildings);
	for (const shot of ROOM_SHOTS) {
		let b;
		if (shot.types.includes(1)) b = house;
		else {
			const cands = buildings.filter(s => shot.types.includes(s.buildingType) && roomOf(s, shot.room));
			const rich = s => (s.rooms?.length ?? 0) * 100 + (s.openings?.length ?? 0);
			cands.sort((p, q) => rich(q) - rich(p) || p.id - q.id);
			b = cands[0];
		}
		const q = b !== undefined ? roomOf(b, shot.room) : undefined;
		if (q === undefined) continue;
		const qx = q.x + q.w / 2;
		const qy = q.y + q.h / 2;
		// the survivor: at a loot spot in the room, else near its middle
		const spot = (b.lootSpots ?? []).find(p => inRect(q, p.x, p.y)) ?? { x: qx, y: qy };
		const survivor = freeNear(world, spot.x, spot.y) ?? spot;
		const zombies = [];
		let win;
		for (const o of b.openings ?? []) {
			if (o.kind !== "window") continue;
			const d = Math.hypot(o.x + o.w / 2 - qx, o.y + o.h / 2 - qy);
			if (d < 560 && (win === undefined || d < win.d)) win = { o, d };
		}
		if (win !== undefined) {
			const o = win.o;
			zombies.push({
				x: o.x + o.w / 2,
				y: o.y + o.h / 2,
				type: 1,
				angle: Math.atan2(survivor.y - o.y, survivor.x - o.x),
			});
		}
		// a walker a little way off in the same room (or the next), on free floor
		for (const [dx, dy] of [
			[170, 90],
			[-170, 90],
			[170, -90],
			[-170, -90],
			[240, 0],
			[-240, 0],
		]) {
			const p = freeNear(world, survivor.x + dx, survivor.y + dy);
			if (p === undefined || buildingAt(world, p.x, p.y) !== b) continue;
			if (Math.hypot(p.x - survivor.x, p.y - survivor.y) < 120) continue;
			zombies.push({ ...p, type: 1, angle: Math.atan2(survivor.y - p.y, survivor.x - p.x) });
			break;
		}
		const base = {
			rect: sceneAround(qx, qy, W, H),
			scale: 1,
			inside: { x: b.x + b.w / 2, y: b.y + b.h / 2, box: { x: b.x, y: b.y, w: b.w, h: b.h } },
			actors: { survivor: { ...survivor, angle: 0 }, zombies },
		};
		out.push({ name: shot.name, title: shot.title, hour: 10, ...base });
		out.push({ name: `${shot.name}-night`, title: `${shot.title}, 22:00`, hour: 22, ...base });
	}
	return out;
}

// ---------------------------------------------------------------- drawing a scene into the fake tree

function makeShadow(state) {
	const tmp = { x: 0, y: 0 };
	return (x, y, len) => {
		const t = state.hour;
		if (t > 6 && t < 18) {
			const rad = ((t / 24) * 360 - 225) * (Math.PI / 180);
			tmp.x = Math.cos(rad) * len;
			tmp.y = -Math.sin(rad) * len;
			return tmp;
		}
		const dx = x - state.lightX;
		const dy = y - state.lightY;
		const d = Math.hypot(dx, dy);
		if (d < 1) {
			tmp.x = 0;
			tmp.y = len * 0.5;
		} else {
			tmp.x = (dx / d) * len;
			tmp.y = (dy / d) * len;
		}
		return tmp;
	};
}

function actorsFor(world, scene) {
	const r = scene.rect;
	const cx = r.x + r.w / 2;
	const cy = r.y + r.h / 2;
	const taken = [];
	const survivor = place(world, r, cx, cy, ["sidewalk", "walk", "apron", "plaza", "dirt", "playground"], taken) ?? {
		x: cx,
		y: cy,
	};
	const zombies = [];
	const spots = [
		["road", "parking", "apron"],
		["grass", "verge", "playground", "dirt", "plaza"],
		["sidewalk", "walk", "drive"],
		["road", "grass", "plaza", "apron"],
	];
	for (let i = 0; i < spots.length; i++) {
		const p = place(world, r, cx + (i % 2 ? 260 : -260), cy + (i < 2 ? -120 : 140), spots[i], taken);
		if (p !== undefined)
			zombies.push({ ...p, type: i === 3 ? 4 : 1, angle: Math.atan2(survivor.y - p.y, survivor.x - p.x) });
	}
	// one walker under a tree, so the canopy's see-through (VEG-04) is in the picture
	const tree = solidsIn(world, { x: r.x + 160, y: r.y + 160, w: r.w - 320, h: r.h - 320 }).find(
		s => s.kind === "tree" && !taken.some(p => Math.hypot(p.x - s.x, p.y - s.y) < 200),
	);
	if (tree !== undefined) {
		const zx = tree.x + tree.w / 2 + 44;
		const zy = tree.y + tree.h / 2 + 30;
		if (pointInSolid(world, zx, zy, 18) === undefined) zombies.push({ x: zx, y: zy, type: 1, angle: 2.4, tree });
	}
	return { survivor, zombies };
}

function drawScene(world, scene, opts) {
	const scale = scene.scale ?? opts.scale ?? 1;
	const vw = Math.round(scene.rect.w * scale);
	const vh = Math.round(scene.rect.h * scale);
	const root = gui.make("Frame");
	root.Size = UDim2.fromOffset(vw, vh);
	const renderer = new Renderer(root, "Sprites");
	const dark = gui.make("Frame");
	dark.Parent = root;
	dark.BackgroundTransparency = 1;
	const cam = new Camera();
	cam.setView(vw, vh);
	renderer.setView(vw, vh);
	cam.zoom = scale;
	cam.x = scene.rect.x + scene.rect.w / 2;
	cam.y = scene.rect.y + scene.rect.h / 2;
	let actors = { survivor: undefined, zombies: [] };
	if (opts.actors && !scene.noActors) {
		if (scene.actors !== undefined) {
			// a saved cast (the interiors set): the same bodies in the before and the after, minus any that would
			// stand inside a solid of this town (a walker in a window that the older town does not have)
			const ok = p => pointInSolid(world, p.x, p.y, 12) === undefined;
			const s = scene.actors.survivor;
			actors = {
				survivor: s !== undefined && ok(s) ? { x: s.x, y: s.y } : undefined,
				zombies: scene.actors.zombies.filter(ok),
			};
		} else {
			actors = actorsFor(world, scene);
		}
	}
	// roofs off: every building of the scene (--roof-off), or the one the survivor is inside (an interior scene)
	const lifted = [];
	if (args.flags.has("roof-off")) {
		for (const s of solidsIn(world, scene.rect)) if (s.kind === "building") lifted.push(s);
	}
	if (scene.inside !== undefined) {
		const box = scene.inside.box;
		const b =
			buildingAt(world, scene.inside.x, scene.inside.y) ??
			world.solids.find(s => s.kind === "building" && box !== undefined && sameBox(s, box));
		if (b !== undefined) lifted.push(b);
	}
	for (const b of lifted) b.roofAlpha = 0;
	const state = { hour: scene.hour, lightX: actors.survivor?.x ?? cam.x, lightY: actors.survivor?.y ?? cam.y };
	const shadow = makeShadow(state);
	const view = new WorldView(shadow);
	view.clock = 0;
	// canopies over a body turn see-through, as GameLoop.updateCanopy eases them (VEG-04): tree crowns, and a gas
	// station's canopy and price pylon (EDI-16, rects: the pylon's drawn one, client/view/buildingSigns.ts)
	const fades = s => s.kind === "tree" || s.kind === "canopy" || s.tags === "gas_sign";
	for (const s of world.solids) if (fades(s)) s.canopyAlpha = 1;
	const bodies = [...actors.zombies, ...(actors.survivor ? [actors.survivor] : [])];
	for (const s of solidsIn(world, scene.rect)) {
		if (!fades(s)) continue;
		if (s.kind !== "tree") {
			const q = s.tags === "gas_sign" && BS !== undefined ? BS.priceSignRect(s, { x: 0, y: 0, w: 0, h: 0 }) : s;
			const under = b => b.x > q.x - 18 && b.x < q.x + q.w + 18 && b.y > q.y - 18 && b.y < q.y + q.h + 18;
			if (bodies.some(under)) s.canopyAlpha = SHELTER_SEE_THROUGH ?? CANOPY_SEE_THROUGH;
			continue;
		}
		const r2 = ((s.canopyR ?? 80) + 18) ** 2;
		const tx = s.x + s.w / 2;
		const ty = s.y + s.h / 2;
		if (bodies.some(b => (b.x - tx) ** 2 + (b.y - ty) ** 2 < r2)) s.canopyAlpha = CANOPY_SEE_THROUGH;
	}
	const v = cam.viewRect(32);
	renderer.beginFrame();
	view.drawGround(renderer, cam, v, world);
	view.drawSolids(renderer, cam, v, world);
	for (const z of actors.zombies) {
		const rad = z.type === 4 ? 17 : 16;
		const so = shadow(z.x, z.y, 10);
		renderer.drawCircle(cam, z.x + so.x, z.y + so.y, rad * 2.1, {
			color: COLORS.shadow,
			alpha: 0.3,
			zIndex: Z.actorShadow,
		});
		HV.drawHumanoid(renderer, cam, z.x, z.y, z.angle, rad / 18, HV.zombieColor(z.type), 0, 1, 0.8, Z.zombie);
	}
	let aim = 0;
	if (actors.survivor !== undefined) {
		const look = SV.createLook();
		look.x = actors.survivor.x;
		look.y = actors.survivor.y;
		const z0 = actors.zombies[0];
		look.angle = z0 !== undefined ? Math.atan2(z0.y - look.y, z0.x - look.x) : 0;
		if (opts.aim !== undefined) look.angle = opts.aim;
		aim = look.angle;
		const so = shadow(look.x, look.y, 10);
		look.shadowX = so.x;
		look.shadowY = so.y;
		SV.drawSurvivor(renderer, cam, look, SV.createSwingTrail());
	}
	renderer.endFrame();
	let darkness = darkAlphaAt(scene.hour, false, false);
	if (darkness > 0.004) {
		const lm = new LightMap(dark, COLORS.overlayNight);
		const lights = [];
		const s = actors.survivor;
		if (s !== undefined && survivorLight !== undefined) {
			// what gameLoop drawLight pushes for a survivor holding `--hand` and wearing `--gun` (LUZ-04)
			const save = { equipHand: opts.hand, equipGun: opts.gun, skillLevels: new Array(32).fill(0) };
			lights.push({ x: s.x, y: s.y, r: survivorLight.survivorLightRadius(save), inner: 0.4 });
			const cone = survivorLight.survivorCone(save);
			if (cone !== undefined)
				lights.push({
					x: s.x,
					y: s.y,
					r: cone.radius,
					inner: 0.35,
					angle: aim,
					cone: survivorLight.CONE_HALF_ANGLE,
				});
			if (survivorLight.wearsNightVision(save)) {
				lm.setColor(COLORS.overlayNightVision);
				darkness *= survivorLight.NIGHT_VISION_DARK;
			}
		} else if (s !== undefined) {
			lights.push({ x: s.x, y: s.y, r: 250, inner: 0.4 });
		}
		lm.update(cam, darkness, lights);
	}
	for (const b of lifted) b.roofAlpha = 1;
	return { root, renderer, dark, vw, vh, actors };
}

// ---------------------------------------------------------------- images for the rasteriser

const images = new Map();
let assetFiles;

/** the decoded PNG behind a content id: "local:<name>" or an uploaded id listed in design/world-art/assets.json */
function localImage(id) {
	if (images.has(id)) return images.get(id);
	let file;
	if (id.startsWith(LOCAL)) file = join(ART_DIR, `${id.slice(LOCAL.length)}.png`);
	else {
		if (assetFiles === undefined) {
			assetFiles = {};
			const assetsPath = join(ART_DIR, "assets.json");
			const ids = existsSync(assetsPath) ? (JSON.parse(readFileSync(assetsPath, "utf8")).ids ?? {}) : {};
			for (const [name, asset] of Object.entries(ids)) assetFiles[asset] = join(ART_DIR, `${name}.png`);
		}
		file = assetFiles[id];
	}
	let img;
	if (file !== undefined && existsSync(file)) img = decodePNG(readFileSync(file));
	else console.warn(`  (no local file for image ${id}: painted magenta)`);
	images.set(id, img);
	return img;
}

// ---------------------------------------------------------------- main

function renderOne(world, scene, outFile, opts) {
	const t0 = Date.now();
	const createdBefore = gui.stats.created;
	const drawn = drawScene(world, scene, opts);
	const img = rasterise(
		{ layer: drawn.renderer.layer, dark: drawn.dark, vw: drawn.vw, vh: drawn.vh },
		COLORS.bg,
		localImage,
	);
	mkdirSync(dirname(outFile), { recursive: true });
	writeFileSync(outFile, encodePNG(img, true));
	const counts = { ...countSprites(drawn.renderer.layer), instances: gui.stats.created - createdBefore };
	if (!args.flags.has("quiet")) {
		console.log(
			`  ${basename(outFile).padEnd(20)} ${`${img.w}x${img.h}`.padEnd(10)} ${String(counts.sprites).padStart(5)} sprites (${counts.images} images, ${counts.flat} flat)  ${Date.now() - t0} ms`,
		);
	}
	return { counts, actors: drawn.actors };
}

const world = generateTown(SEED);
const artOn = useLocalArt(!args.flags.has("no-art"));
const opts = {
	actors: !args.flags.has("no-actors"),
	scale: args.scale !== undefined ? Number(args.scale) : undefined,
	// the survivor's hand and gun-slot gadgets (EQUIPS ids: 13 flashlight, 15 torchlight, 6 night vision) and aim
	hand: args.hand !== undefined ? Number(args.hand) : -1,
	gun: args.gun !== undefined ? Number(args.gun) : -1,
	aim: args.aim !== undefined ? (Number(args.aim) * Math.PI) / 180 : undefined,
};
console.log(
	`render-map: seed ${SEED}, src ${SRC}${worldArt === undefined ? " (no world art module: flat)" : artOn ? `, art ${ART_DIR}` : " (world art off: flat)"}`,
);

if (args["dump-buildings"] !== undefined) {
	// the buildings of this checkout's town, for --match in another one (same scenes before and after)
	const list = world.solids
		.filter(s => s.kind === "building")
		.map(s => ({ x: s.x, y: s.y, w: s.w, h: s.h, type: s.buildingType }));
	writeFileSync(resolve(args["dump-buildings"]), `${JSON.stringify(list)}\n`);
	console.log(`  ${list.length} buildings -> ${args["dump-buildings"]}`);
	process.exit(0);
}

if (args.preset !== undefined || args.scenes !== undefined) {
	let wanted;
	if (args.scenes !== undefined) {
		// replay a saved scene list (the "before" of the interiors set renders exactly the "after"'s scenes)
		const saved = JSON.parse(readFileSync(resolve(args.scenes), "utf8"));
		wanted = Object.entries(saved).map(([name, s]) => ({ name, ...s }));
	} else if (args.preset === "interiors") {
		const match = args.match !== undefined ? JSON.parse(readFileSync(resolve(args.match), "utf8")) : undefined;
		wanted = interiorScenes(world, match);
	} else if (args.preset === "rooms") {
		wanted = roomScenes(world);
	} else {
		const all = scenes(world);
		const signs = signScenes(world);
		wanted =
			args.preset === "all"
				? all
				: args.preset === "signs"
					? signs
					: [...all, ...signs.filter(s => s.name.startsWith("sign"))].filter(s => s.name === args.preset);
		if (wanted.length === 0) {
			console.error(
				`no preset "${args.preset}" (have: ${[...all, ...signs].map(s => s.name).join(", ")}, all, signs, interiors)`,
			);
			process.exit(1);
		}
	}
	const outDir = resolve(args.out ?? join(ROOT, "docs", "art", "render"));
	const meta = {};
	for (const scene of wanted) {
		if (args.hour !== undefined) scene.hour = hourOf(args.hour, scene.hour);
		const res = renderOne(world, scene, join(outDir, `${scene.name}.png`), opts);
		meta[scene.name] = {
			title: scene.title,
			rect: scene.rect,
			hour: scene.hour,
			scale: scene.scale ?? opts.scale ?? 1,
			...(scene.inside !== undefined ? { inside: scene.inside } : {}),
			...(scene.actors !== undefined ? { actors: scene.actors } : {}),
			...(scene.noActors === true ? { noActors: true } : {}),
			counts: res.counts,
		};
	}
	const metaPath = join(outDir, "scenes.json");
	const prev = existsSync(metaPath) ? JSON.parse(readFileSync(metaPath, "utf8")) : {};
	writeFileSync(metaPath, `${JSON.stringify({ ...prev, ...meta }, undefined, "\t")}\n`);
} else {
	const w = Number(args.w ?? 1280);
	const h = Number(args.h ?? 800);
	const x = args.x !== undefined ? Number(args.x) : Math.round(world.width / 2 - w / 2);
	const y = args.y !== undefined ? Number(args.y) : Math.round(world.height / 2 - h / 2);
	const scene = { name: "custom", title: "custom", rect: { x, y, w, h }, hour: hourOf(args.hour, 10) };
	let out = resolve(args.out ?? join(ROOT, "docs", "art", "render", "custom.png"));
	if (!out.endsWith(".png")) out = join(out, "custom.png");
	renderOne(world, scene, out, opts);
}
